"use client";
import { useEffect, useState } from "react";

const blank = { dailySpendLimitUsd:"",monthlySpendLimitUsd:"",dailyTokenLimit:"",monthlyTokenLimit:"" };
export default function BudgetClient({ orgId }: { orgId: string }) {
  const [policy,setPolicy]=useState({ ...blank,warningThresholds:"50,75,90",enforceByoTokenLimits:true,modelAllowlistEnabled:false,providerAllowlistEnabled:false,killSwitch:false });
  const [usage,setUsage]=useState<Record<string,string>>({}); const [projected,setProjected]=useState<number|null>(null);
  const [layer,setLayer]=useState({scope:"feature",identifier:"research",provider:"",model:"",allowed:true,...blank});
  const [members,setMembers]=useState<Array<{userId:string;name:string;email:string}>>([]); const [message,setMessage]=useState("");
  async function load(){const r=await fetch(`/api/billing/budgets?orgId=${orgId}`);const d=await r.json();if(d.policy)setPolicy({...policy,...d.policy,warningThresholds:(d.policy.warningThresholds??[50,75,90]).join(",")});setUsage(d.usage??{});setProjected(d.projectedExhaustionDays??null);setMembers(d.members??[]);if(!r.ok)setMessage(d.error);}
  useEffect(()=>{void load();},[orgId]);
  async function save(body:Record<string,unknown>){const normalized={...body,orgId,dailySpendLimitUsd:body.dailySpendLimitUsd||null,monthlySpendLimitUsd:body.monthlySpendLimitUsd||null,dailyTokenLimit:body.dailyTokenLimit||null,monthlyTokenLimit:body.monthlyTokenLimit||null};const r=await fetch("/api/billing/budgets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(normalized)});const d=await r.json();setMessage(r.ok?"Budget controls saved and audited.":d.error);if(r.ok)await load();}
  return <main className="intel-app"><header className="intel-header"><div><span className="eyebrow">VANTAGE / API BUDGETS</span><h1>Hard limits before every call</h1></div><a href={`/team?orgId=${orgId}`}>Team controls →</a></header>
    {message&&<p className="telemetry-status">{message}</p>}<section className="metric-grid"><article><span>Spend today</span><strong>${Number(usage.dailySpend??0).toFixed(2)}</strong></article><article><span>Spend this month</span><strong>${Number(usage.monthlySpend??0).toFixed(2)}</strong></article><article><span>Tokens today</span><strong>{Number(usage.dailyTokens??0).toLocaleString()}</strong></article><article><span>Projected exhaustion</span><strong>{projected===null?"—":`${projected.toFixed(1)}d`}</strong></article></section>
    <section className="admin-grid"><form className="intel-panel" onSubmit={(e)=>{e.preventDefault();void save({scope:"org",...policy,warningThresholds:policy.warningThresholds.split(",").map(Number)})}}><span className="eyebrow">ORGANIZATION HARD LIMITS</span>
      <div className="budget-fields">{Object.entries(blank).map(([key])=><label key={key}>{key.replace(/([A-Z])/g," $1")}<input type="number" min="0" value={policy[key as keyof typeof blank] as string} onChange={(e)=>setPolicy({...policy,[key]:e.target.value})}/></label>)}</div>
      <label>Warning thresholds (%)<input value={policy.warningThresholds} onChange={(e)=>setPolicy({...policy,warningThresholds:e.target.value})}/></label>
      <label className="check-field"><input type="checkbox" checked={policy.enforceByoTokenLimits} onChange={(e)=>setPolicy({...policy,enforceByoTokenLimits:e.target.checked})}/> Apply token limits to BYOK/local</label>
      <label className="check-field"><input type="checkbox" checked={policy.modelAllowlistEnabled} onChange={(e)=>setPolicy({...policy,modelAllowlistEnabled:e.target.checked})}/> Enforce model allowlist</label>
      <label className="check-field"><input type="checkbox" checked={policy.providerAllowlistEnabled} onChange={(e)=>setPolicy({...policy,providerAllowlistEnabled:e.target.checked})}/> Enforce provider allowlist</label>
      <label className="check-field danger"><input type="checkbox" checked={policy.killSwitch} onChange={(e)=>setPolicy({...policy,killSwitch:e.target.checked})}/> Hard kill switch</label><button className="primary-action">Save org limits</button></form>
      <form className="intel-panel" onSubmit={(e)=>{e.preventDefault();const identity=layer.scope==="member"?{userId:layer.identifier}:layer.scope==="feature"?{feature:layer.identifier}:{provider:layer.provider,model:layer.model,allowed:layer.allowed};void save({...layer,...identity})}}><span className="eyebrow">LAYERED LIMIT</span>
        <label>Scope<select value={layer.scope} onChange={(e)=>setLayer({...layer,scope:e.target.value})}><option value="feature">Feature</option><option value="member">Member</option><option value="model">Provider + model</option></select></label>
        {layer.scope==="member"?<label>Member<select value={layer.identifier} onChange={(e)=>setLayer({...layer,identifier:e.target.value})}><option value="">Choose member</option>{members.map((m)=><option key={m.userId} value={m.userId}>{m.name} · {m.email}</option>)}</select></label>:layer.scope==="feature"?<label>Feature<input value={layer.identifier} onChange={(e)=>setLayer({...layer,identifier:e.target.value})} placeholder="strategy, cad, coding, research…"/></label>:<><label>Provider<input value={layer.provider} onChange={(e)=>setLayer({...layer,provider:e.target.value})}/></label><label>Model (* for provider cap)<input value={layer.model} onChange={(e)=>setLayer({...layer,model:e.target.value})}/></label><label className="check-field"><input type="checkbox" checked={layer.allowed} onChange={(e)=>setLayer({...layer,allowed:e.target.checked})}/> Allowed</label></>}
        <div className="budget-fields">{Object.entries(blank).map(([key])=><label key={key}>{key.replace(/([A-Z])/g," $1")}<input type="number" min="0" value={layer[key as keyof typeof blank] as string} onChange={(e)=>setLayer({...layer,[key]:e.target.value})}/></label>)}</div><button className="primary-action">Save layered limit</button></form>
    </section>
  </main>;
}
