import { createCipheriv,createDecipheriv,createHash,randomBytes } from "node:crypto";
import type { PoolClient } from "@neondatabase/serverless";
import { strToU8,zipSync,unzipSync,strFromU8 } from "fflate";
import { createExportRegistry,type ExportFilters,type ExportScope } from "./registry";
import { streamCsv } from "./csv";
export * from "./csv";export * from "./registry";
function key(){return createHash("sha256").update(process.env.EXPORT_ENCRYPTION_KEY??process.env.BETTER_AUTH_SECRET??"local-export-key").digest();}
function encrypt(data:Uint8Array){const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key(),iv);const encrypted=Buffer.concat([cipher.update(data),cipher.final()]);return`${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`;}
function decrypt(value:string){const[iv,tag,data]=value.split(".");if(!iv||!tag||!data)throw new Error("Invalid export archive");const cipher=createDecipheriv("aes-256-gcm",key(),Buffer.from(iv,"base64url"));cipher.setAuthTag(Buffer.from(tag,"base64url"));return new Uint8Array(Buffer.concat([cipher.update(Buffer.from(data,"base64url")),cipher.final()]));}
export async function createExportJob(client:PoolClient,input:{orgId:string;userId:string;scope:ExportScope;domains:string[]|"all";filters?:ExportFilters;reason?:string}){
 const recent=await client.query(`SELECT count(*)::int AS count FROM export_jobs WHERE requested_by=$1 AND created_at>now()-interval '1 hour'`,[input.userId]);if(Number(recent.rows[0]?.count??0)>=5)throw new Error("Export rate limit reached; try again later");
 const registry=createExportRegistry();const domains=input.domains==="all"?[...registry.values()].filter(item=>item.scope===input.scope).map(item=>item.id):[...new Set(input.domains)];if(!domains.length)throw new Error("Select at least one export");for(const id of domains){const adapter=registry.get(id);if(!adapter||adapter.scope!==input.scope)throw new Error(`Export domain is not authorized for ${input.scope} scope: ${id}`);}
 const job=await client.query<{id:string}>(`INSERT INTO export_jobs(org_id,requested_by,scope,domains,filters) VALUES($1,$2,$3,$4,$5::jsonb) RETURNING id`,[input.orgId,input.userId,input.scope,domains,JSON.stringify(input.filters??{})]);await client.query(`INSERT INTO export_audit_events(org_id,job_id,actor_user_id,action,reason,metadata) VALUES($1,$2,$3,'export.requested',$4,$5::jsonb)`,[input.orgId,job.rows[0]!.id,input.userId,input.reason??null,JSON.stringify({scope:input.scope,domains})]);return job.rows[0]!.id;
}
export async function processExportJob(client:PoolClient,jobId:string){
 const result=await client.query<{org_id:string;requested_by:string;scope:ExportScope;domains:string[];filters:ExportFilters}>(`UPDATE export_jobs SET status='running',progress=1,updated_at=now() WHERE id=$1 AND status='queued' RETURNING org_id,requested_by,scope,domains,filters`,[jobId]);const job=result.rows[0];if(!job)return;
 try{const registry=createExportRegistry(),files:Record<string,Uint8Array>={},manifest:{format:string;version:number;generatedAt:string;timezone:string;scope:ExportScope;files:Array<{name:string;domain:string;description:string;columns:string[]}>}={format:"Vantage Team Data Export",version:1,generatedAt:new Date().toISOString(),timezone:"UTC",scope:job.scope,files:[]};
  for(let index=0;index<job.domains.length;index++){const cancelled=await client.query(`SELECT cancel_requested_at FROM export_jobs WHERE id=$1`,[jobId]);if(cancelled.rows[0]?.cancel_requested_at){await client.query(`UPDATE export_jobs SET status='cancelled',progress=0,updated_at=now() WHERE id=$1`,[jobId]);return;}const adapter=registry.get(job.domains[index]!);if(!adapter||adapter.scope!==job.scope)throw new Error("Export adapter authorization changed");let csv="";for await(const chunk of streamCsv(adapter.columns,adapter.rows({client,orgId:job.org_id,userId:job.requested_by,scope:job.scope,filters:job.filters}),{excelBom:job.filters.excelBom}))csv+=chunk;files[adapter.fileName]=strToU8(csv);manifest.files.push({name:adapter.fileName,domain:adapter.id,description:adapter.description,columns:adapter.columns});await client.query(`UPDATE export_jobs SET progress=$2,updated_at=now() WHERE id=$1`,[jobId,Math.max(1,Math.floor(((index+1)/job.domains.length)*90))]);}
  files["manifest.json"]=strToU8(JSON.stringify(manifest,null,2));const archive=zipSync(files,{level:6});await client.query(`UPDATE export_jobs SET status='completed',progress=100,encrypted_archive=$2,expires_at=now()+interval '24 hours',size_bytes=$3,completed_at=now(),updated_at=now() WHERE id=$1`,[jobId,encrypt(archive),archive.byteLength]);await client.query(`INSERT INTO export_audit_events(org_id,job_id,actor_user_id,action,metadata) VALUES($1,$2,$3,'export.completed',$4::jsonb)`,[job.org_id,jobId,job.requested_by,JSON.stringify({sizeBytes:archive.byteLength,fileCount:manifest.files.length})]);await client.query(`INSERT INTO notifications(user_id,org_id,type,title,body,dedupe_key) VALUES($1,$2,'export_ready','Team export ready','Your private export archive is available for 24 hours.',$3) ON CONFLICT(dedupe_key) DO NOTHING`,[job.requested_by,job.org_id,`export-ready:${jobId}`]);
 }catch(error){await client.query(`UPDATE export_jobs SET status='failed',error=$2,updated_at=now() WHERE id=$1`,[jobId,error instanceof Error?error.message:"Export failed"]);throw error;}
}
export async function downloadExport(client:PoolClient,token:string){const hash=createHash("sha256").update(token).digest("hex");const result=await client.query<{id:string;encrypted_archive:string;requested_by:string;org_id:string}>(`SELECT id,encrypted_archive,requested_by,org_id FROM export_jobs WHERE download_token_hash=$1 AND status='completed' AND expires_at>now()`,[hash]);const job=result.rows[0];if(!job)throw new Error("Export link is invalid or expired");await client.query(`INSERT INTO export_audit_events(org_id,job_id,actor_user_id,action) VALUES($1,$2,$3,'export.downloaded')`,[job.org_id,job.id,job.requested_by]);return decrypt(job.encrypted_archive);}
export async function issueExportDownload(client:PoolClient,jobId:string,userId:string){const token=randomBytes(32).toString("base64url"),hash=createHash("sha256").update(token).digest("hex");const result=await client.query(`UPDATE export_jobs SET download_token_hash=$3 WHERE id=$1 AND requested_by=$2 AND status='completed' AND expires_at>now() RETURNING id`,[jobId,userId,hash]);if(!result.rowCount)throw new Error("Completed export is unavailable");return token;}
export async function expireExports(client:PoolClient){return client.query(`UPDATE export_jobs SET status='expired',encrypted_archive=NULL,download_token_hash=NULL,updated_at=now() WHERE expires_at<=now() AND encrypted_archive IS NOT NULL`);}
export function inspectExportManifest(archive:Uint8Array){const files=unzipSync(archive);if(!files["manifest.json"])throw new Error("Export manifest missing");return JSON.parse(strFromU8(files["manifest.json"])) as unknown;}
