import type {
  CapabilityContext,
  CapabilityDetection,
  CapabilityReport,
  ConnectorCapability,
} from "./capability.js";
import { cloudUrl } from "./endpoints.js";
import { dirExists, fileExists, joinPath, readIfExists, type FileSystemLike } from "./ports.js";

/**
 * agent-sync capability — keep the team's shared agent configuration (rules, subagents,
 * skills, MCP servers, suggested permissions) synced into Claude Code and Cursor on this
 * machine, from GET /api/agent-config/bundle authenticated with the connector's device
 * token. The bundle is scoped server-side to THIS device's user: team-wide items plus
 * items shared with them personally.
 *
 * The pure builders below are ported 1:1 from
 * packages/vantage-cad-cli/src/agent-sync.ts (which stays untouched) — same markers, same
 * vantage- namespace rule, same "permissions are never auto-merged" security stance.
 * Cursor formats verified 2026-08 against https://cursor.com/docs/context/rules,
 * https://cursor.com/docs/context/mcp and https://cursor.com/docs/skills (full citations
 * in apps/web/lib/agent-config/cursor-formats.ts).
 */

export const VANTAGE_BEGIN_MARKER = "<!-- BEGIN VANTAGE TEAM AGENT CONFIG -->";
export const VANTAGE_END_MARKER = "<!-- END VANTAGE TEAM AGENT CONFIG -->";
export const VANTAGE_MCP_PREFIX = "vantage-";
export const TEAM_RULES_FILE = ".claude/vantage-team-rules.md";
export const PERMISSIONS_SUGGESTION_FILE = ".claude/vantage-permissions.suggested.json";
export const CURSOR_RULES_DIR = ".cursor/rules/vantage";
export const CURSOR_SKILLS_DIR = ".cursor/skills/vantage";
export const CURSOR_MCP_FILE = ".cursor/mcp.json";
/** Marks a file as Vantage-managed: sync only ever prunes files carrying it. */
export const CURSOR_GENERATED_BANNER =
  "<!-- Generated by `vantage-cad agent sync` — edit at /team/agent-config, not here. -->";

export const AGENT_CONFIG_BUNDLE_SCHEMA = "vantage.agent-config/v1";
export const AGENT_SYNC_INTERVAL_MS = 15 * 60_000;

export type AgentConfigBundle = {
  schema: string;
  orgId: string;
  generatedAt: string;
  rules: Array<{ name: string; description: string | null; markdown: string; version: number }>;
  subagents: Array<{ name: string; description: string | null; markdown: string; version: number }>;
  mcpServers: Array<{ name: string; description: string | null; entry: Record<string, unknown>; version: number }>;
  permissions: Array<{
    name: string;
    description: string | null;
    snippet: { allow?: string[]; deny?: string[]; ask?: string[] };
    version: number;
  }>;
  skills: Array<{ name: string; description: string | null; markdown: string; version: number }>;
};

const SAFE_NAME = /^[a-z0-9][a-z0-9-]{0,63}$/;

export function safeConfigName(name: string): string | null {
  return SAFE_NAME.test(name) ? name : null;
}

/**
 * Idempotently install `block` between the VANTAGE markers in a CLAUDE.md body.
 * Everything outside the markers is preserved byte-for-byte; a half-present
 * marker pair is an error (never guess at a corrupt file).
 */
export function applyVantageMarkerBlock(existing: string, block: string): string {
  const begin = existing.indexOf(VANTAGE_BEGIN_MARKER);
  const end = existing.indexOf(VANTAGE_END_MARKER);
  const wrapped = `${VANTAGE_BEGIN_MARKER}\n${block.trim()}\n${VANTAGE_END_MARKER}`;
  if (begin === -1 && end === -1) {
    if (!existing) return `${wrapped}\n`;
    return `${existing.replace(/\n*$/, "\n\n")}${wrapped}\n`;
  }
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error(
      `CLAUDE.md has a corrupt VANTAGE marker pair (found ${begin === -1 ? "END without BEGIN" : end === -1 ? "BEGIN without END" : "END before BEGIN"}). Fix or remove the markers, then re-run sync.`,
    );
  }
  const before = existing.slice(0, begin);
  const after = existing.slice(end + VANTAGE_END_MARKER.length);
  return `${before}${wrapped}${after}`;
}

export function buildClaudeMdBlock(): string {
  return [
    "Team agent rules synced from Vantage (/team/agent-config).",
    "Do not edit between these markers — `vantage-cad agent sync` rewrites this block.",
    `@${TEAM_RULES_FILE}`,
  ].join("\n");
}

export type RuleScope = {
  body: string;
  description: string | null;
  globs: string[] | null;
  alwaysApply: boolean | null;
};

/**
 * A rules item MAY start with an optional YAML frontmatter block declaring
 * Cursor scoping metadata (description / globs / alwaysApply — the MDC fields
 * from https://cursor.com/docs/context/rules). Claude Code output uses only
 * the body; the Cursor writer turns the metadata into MDC frontmatter.
 */
export function parseRuleScope(markdown: string): RuleScope {
  const normalized = markdown.replace(/\r\n/g, "\n");
  const none: RuleScope = { body: normalized, description: null, globs: null, alwaysApply: null };
  if (!normalized.startsWith("---\n")) return none;
  const end = normalized.indexOf("\n---", 4);
  if (end === -1) return none;
  const rawFields = normalized.slice(4, end);
  const body = normalized.slice(normalized.indexOf("\n", end + 1) + 1);
  const scope: RuleScope = { body, description: null, globs: null, alwaysApply: null };
  const clean = (value: string) => value.trim().replace(/^["']|["']$/g, "");
  const lines = rawFields.split("\n");
  for (let i = 0; i < lines.length; i += 1) {
    const match = /^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/.exec(lines[i]!);
    if (!match) continue;
    const key = match[1]!;
    if (key === "globs" && !match[2]!.trim()) {
      // YAML block list form: globs:\n  - src/**\n  - "**/*.java"
      const list: string[] = [];
      while (i + 1 < lines.length && /^\s+-\s+/.test(lines[i + 1]!)) {
        i += 1;
        list.push(clean(lines[i]!.replace(/^\s+-\s+/, "")));
      }
      scope.globs = list.filter(Boolean).length ? list.filter(Boolean) : null;
      continue;
    }
    const value = clean(match[2]!);
    if (key === "description" && value) scope.description = value;
    else if (key === "globs" && value) {
      // Cursor docs: "Separate multiple patterns with commas."
      const globs = value.split(",").map(clean).filter(Boolean);
      scope.globs = globs.length ? globs : null;
    } else if (key === "alwaysApply") {
      if (value === "true") scope.alwaysApply = true;
      else if (value === "false") scope.alwaysApply = false;
    }
  }
  return scope;
}

export function buildTeamRulesMarkdown(bundle: AgentConfigBundle): string | null {
  const sections = bundle.rules
    // Claude Code gets the rule BODY only — Cursor scoping frontmatter is
    // metadata for .mdc generation, not agent context.
    .map((rule) => ({ name: rule.name, body: parseRuleScope(rule.markdown).body.trim() }))
    .filter((rule) => rule.body)
    .map((rule) => `## ${rule.name}\n\n${rule.body}`);
  if (!sections.length) return null;
  return [CURSOR_GENERATED_BANNER, "# Team agent rules", ...sections, ""].join("\n\n");
}

/** YAML double-quoted scalar (JSON string escaping is valid YAML). */
function yamlQuote(value: string): string {
  return JSON.stringify(value);
}

/**
 * One shared rule → one `.cursor/rules/vantage/<name>.mdc` file (MDC format
 * per https://cursor.com/docs/context/rules). Rules without declared globs are
 * team-wide always-on (`alwaysApply: true`); declared globs make the rule
 * Auto Attached; an explicit alwaysApply in the rule's scope frontmatter wins.
 */
export function buildCursorRuleMdc(rule: {
  name: string;
  description: string | null;
  markdown: string;
}): { filename: string; content: string } | null {
  if (!safeConfigName(rule.name)) return null;
  const scope = parseRuleScope(rule.markdown);
  const body = scope.body.trim();
  if (!body) return null;
  const description = scope.description ?? rule.description;
  const alwaysApply = scope.alwaysApply ?? !scope.globs;
  const frontmatter = ["---"];
  if (description) frontmatter.push(`description: ${yamlQuote(description)}`);
  if (scope.globs) frontmatter.push(`globs: ${scope.globs.join(",")}`);
  frontmatter.push(`alwaysApply: ${alwaysApply}`, "---");
  return {
    filename: `${rule.name}.mdc`,
    content: `${frontmatter.join("\n")}\n\n${CURSOR_GENERATED_BANNER}\n\n${body}\n`,
  };
}

/**
 * Cursor requires a skill folder to match the SKILL.md frontmatter `name`
 * ("Must match the parent folder name." — https://cursor.com/docs/skills).
 * Prefer the frontmatter name when filename-safe; fall back to the item name.
 */
export function cursorSkillFolder(markdown: string, itemName: string): string | null {
  const match = /^---\n[\s\S]*?^name:\s*["']?([A-Za-z0-9-]+)["']?\s*$/m.exec(markdown.replace(/\r\n/g, "\n"));
  const fromFrontmatter = match?.[1] ?? "";
  if (fromFrontmatter && safeConfigName(fromFrontmatter)) return fromFrontmatter;
  return safeConfigName(itemName);
}

export type McpMergeResult = {
  json: string;
  added: string[];
  updated: string[];
  removed: string[];
  unchanged: string[];
};

/**
 * Deep-merge team MCP servers into an existing .mcp.json. Only keys under the
 * `vantage-` namespace are ever written or pruned; every other server and every
 * unknown top-level key survives byte-for-byte (modulo JSON re-serialization).
 */
export function mergeMcpServers(
  existingJson: string | null,
  servers: AgentConfigBundle["mcpServers"],
  label = ".mcp.json",
): McpMergeResult {
  let root: Record<string, unknown> = {};
  if (existingJson && existingJson.trim()) {
    const parsed: unknown = JSON.parse(existingJson);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error(`${label} exists but is not a JSON object — fix it before syncing`);
    }
    root = parsed as Record<string, unknown>;
  }
  const mcpServers =
    root.mcpServers && typeof root.mcpServers === "object" && !Array.isArray(root.mcpServers)
      ? { ...(root.mcpServers as Record<string, unknown>) }
      : {};

  const wanted = new Map<string, Record<string, unknown>>();
  for (const server of servers) {
    const name = safeConfigName(server.name);
    if (!name) continue;
    wanted.set(`${VANTAGE_MCP_PREFIX}${name}`, server.entry);
  }

  const added: string[] = [];
  const updated: string[] = [];
  const removed: string[] = [];
  const unchanged: string[] = [];

  for (const key of Object.keys(mcpServers)) {
    if (!key.startsWith(VANTAGE_MCP_PREFIX)) continue; // never touch a team's other servers
    if (!wanted.has(key)) {
      delete mcpServers[key];
      removed.push(key);
    }
  }
  for (const [key, entry] of wanted) {
    if (!(key in mcpServers)) {
      mcpServers[key] = entry;
      added.push(key);
    } else if (JSON.stringify(mcpServers[key]) !== JSON.stringify(entry)) {
      mcpServers[key] = entry;
      updated.push(key);
    } else {
      unchanged.push(key);
    }
  }

  const json = `${JSON.stringify({ ...root, mcpServers }, null, 2)}\n`;
  return { json, added, updated, removed, unchanged };
}

export function buildPermissionsSuggestion(bundle: AgentConfigBundle): string | null {
  if (!bundle.permissions.length) return null;
  const allow = new Set<string>();
  const deny = new Set<string>();
  const ask = new Set<string>();
  for (const item of bundle.permissions) {
    for (const rule of item.snippet.allow ?? []) allow.add(rule);
    for (const rule of item.snippet.deny ?? []) deny.add(rule);
    for (const rule of item.snippet.ask ?? []) ask.add(rule);
  }
  const suggestion = {
    note: "Suggested by your team via Vantage (/team/agent-config). Review each rule, then merge it into .claude/settings.json permissions yourself — a wrong permissions merge is a security change, so Vantage never applies it automatically.",
    generatedAt: bundle.generatedAt,
    permissions: {
      ...(allow.size ? { allow: [...allow].sort() } : {}),
      ...(deny.size ? { deny: [...deny].sort() } : {}),
      ...(ask.size ? { ask: [...ask].sort() } : {}),
    },
  };
  return `${JSON.stringify(suggestion, null, 2)}\n`;
}

/** Runtime validation for the fetched bundle — never trust a shape blindly. */
export function parseAgentConfigBundle(raw: unknown): AgentConfigBundle {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) {
    throw new Error("Agent-config bundle is not an object");
  }
  const value = raw as Record<string, unknown>;
  if (value.schema !== AGENT_CONFIG_BUNDLE_SCHEMA) {
    throw new Error("Server returned an unknown agent-config bundle schema");
  }
  const arr = (key: string) => (Array.isArray(value[key]) ? (value[key] as never[]) : []);
  return {
    schema: AGENT_CONFIG_BUNDLE_SCHEMA,
    orgId: typeof value.orgId === "string" ? value.orgId : "",
    generatedAt: typeof value.generatedAt === "string" ? value.generatedAt : "",
    rules: arr("rules"),
    subagents: arr("subagents"),
    mcpServers: arr("mcpServers"),
    permissions: arr("permissions"),
    skills: arr("skills"),
  };
}

/* ------------------------------------------------------------------ */
/* Materialization (fs-injected port of syncClaude/syncCursor)         */
/* ------------------------------------------------------------------ */

export type AgentSyncTargets = { claude: boolean; cursor: boolean };

export async function detectAgentTargets(fs: FileSystemLike, dir: string): Promise<AgentSyncTargets> {
  return {
    claude: (await dirExists(fs, joinPath(dir, ".claude"))) || (await fileExists(fs, joinPath(dir, "CLAUDE.md"))),
    cursor: await dirExists(fs, joinPath(dir, ".cursor")),
  };
}

type WriteOutcome = "written" | "updated" | "unchanged";

async function writeManaged(fs: FileSystemLike, path: string, content: string): Promise<WriteOutcome> {
  const existing = await readIfExists(fs, path);
  if (existing === content) return "unchanged";
  const parent = path.split("/").slice(0, -1).join("/");
  if (parent) await fs.mkdir(parent, { recursive: true });
  await fs.writeFile(path, content);
  return existing === null ? "written" : "updated";
}

/**
 * Remove stale .mdc files from the managed Cursor rules folder. Only files
 * carrying the generated banner are ever deleted — a user-authored file that
 * strayed into .cursor/rules/vantage/ is left alone and reported.
 */
export async function pruneManagedMdcDir(
  fs: FileSystemLike,
  dirPath: string,
  keep: Set<string>,
): Promise<{ pruned: string[]; kept: string[] }> {
  const pruned: string[] = [];
  const kept: string[] = [];
  let entries: string[];
  try {
    entries = await fs.readdir(dirPath);
  } catch {
    return { pruned, kept };
  }
  for (const entry of entries) {
    if (!entry.endsWith(".mdc") || keep.has(entry)) continue;
    const fullPath = joinPath(dirPath, entry);
    const content = await readIfExists(fs, fullPath);
    if (content === null || !content.includes(CURSOR_GENERATED_BANNER)) {
      kept.push(entry);
      continue;
    }
    await fs.rm(fullPath);
    pruned.push(entry);
  }
  return { pruned, kept };
}

export type AgentSyncSummary = string[];

/**
 * Materialize a bundle into one repository directory for the given targets.
 * Same file layout as `vantage-cad agent sync` so the two tools can hand off:
 * Claude Code → .claude/agents, .claude/skills, .claude/vantage-team-rules.md,
 * the marked CLAUDE.md import block, namespaced .mcp.json merge, and the
 * NEVER-auto-applied permissions suggestion file. Cursor → managed .mdc rules,
 * skills, and .cursor/mcp.json with the identical vantage-prefix-only rule.
 */
export async function materializeAgentConfig(
  fs: FileSystemLike,
  dir: string,
  bundle: AgentConfigBundle,
  targets: AgentSyncTargets,
): Promise<AgentSyncSummary> {
  const summary: AgentSyncSummary = [];
  const report = (path: string, outcome: WriteOutcome) => summary.push(`${outcome}: ${path}`);

  const syncMcpFile = async (path: string, label: string) => {
    const merge = mergeMcpServers(await readIfExists(fs, path), bundle.mcpServers, label);
    const changed = merge.added.length + merge.updated.length + merge.removed.length > 0;
    if (!changed) report(label, "unchanged");
    else {
      const parent = path.split("/").slice(0, -1).join("/");
      if (parent) await fs.mkdir(parent, { recursive: true });
      await fs.writeFile(path, merge.json);
      report(label, "updated");
    }
    for (const key of merge.added) summary.push(`+ mcpServers.${key}`);
    for (const key of merge.updated) summary.push(`~ mcpServers.${key}`);
    for (const key of merge.removed) summary.push(`- mcpServers.${key} (no longer in team config)`);
  };

  if (targets.claude) {
    for (const subagent of bundle.subagents) {
      const name = safeConfigName(subagent.name);
      if (!name) {
        summary.push(`skipped: subagent with unsafe name ${JSON.stringify(subagent.name)}`);
        continue;
      }
      report(
        `.claude/agents/${name}.md`,
        await writeManaged(fs, joinPath(dir, ".claude", "agents", `${name}.md`), `${subagent.markdown.trim()}\n`),
      );
    }
    for (const skill of bundle.skills) {
      const name = safeConfigName(skill.name);
      if (!name) {
        summary.push(`skipped: skill with unsafe name ${JSON.stringify(skill.name)}`);
        continue;
      }
      report(
        `.claude/skills/${name}/SKILL.md`,
        await writeManaged(fs, joinPath(dir, ".claude", "skills", name, "SKILL.md"), `${skill.markdown.trim()}\n`),
      );
    }
    const rulesMarkdown = buildTeamRulesMarkdown(bundle);
    if (rulesMarkdown) {
      report(TEAM_RULES_FILE, await writeManaged(fs, joinPath(dir, TEAM_RULES_FILE), rulesMarkdown));
      const claudeMdPath = joinPath(dir, "CLAUDE.md");
      const existing = (await readIfExists(fs, claudeMdPath)) ?? "";
      const next = applyVantageMarkerBlock(existing, buildClaudeMdBlock());
      if (next === existing) report("CLAUDE.md", "unchanged");
      else {
        await fs.writeFile(claudeMdPath, next);
        report("CLAUDE.md", existing ? "updated" : "written");
      }
    } else {
      summary.push("skipped: no team rules published yet");
    }
    if (bundle.mcpServers.length) await syncMcpFile(joinPath(dir, ".mcp.json"), ".mcp.json");
    // Permissions → suggestion file ONLY, never an automatic settings.json merge.
    const suggestion = buildPermissionsSuggestion(bundle);
    if (suggestion) {
      report(
        PERMISSIONS_SUGGESTION_FILE,
        await writeManaged(fs, joinPath(dir, PERMISSIONS_SUGGESTION_FILE), suggestion),
      );
    }
  }

  if (targets.cursor) {
    const wanted = new Set<string>();
    for (const rule of bundle.rules) {
      const file = buildCursorRuleMdc(rule);
      if (!file) {
        summary.push(`skipped: rule ${JSON.stringify(rule.name)} (empty body or unsafe name)`);
        continue;
      }
      wanted.add(file.filename);
      report(
        `${CURSOR_RULES_DIR}/${file.filename}`,
        await writeManaged(fs, joinPath(dir, CURSOR_RULES_DIR, file.filename), file.content),
      );
    }
    // Prune rules that left the team config — banner-carrying files only.
    const prune = await pruneManagedMdcDir(fs, joinPath(dir, CURSOR_RULES_DIR), wanted);
    for (const entry of prune.pruned) summary.push(`removed: ${CURSOR_RULES_DIR}/${entry} (no longer in team config)`);
    for (const entry of prune.kept) summary.push(`left alone: ${CURSOR_RULES_DIR}/${entry} (not generated by sync)`);

    for (const skill of bundle.skills) {
      const folder = cursorSkillFolder(skill.markdown, skill.name);
      if (!folder) {
        summary.push(`skipped: skill with unsafe name ${JSON.stringify(skill.name)}`);
        continue;
      }
      report(
        `${CURSOR_SKILLS_DIR}/${folder}/SKILL.md`,
        await writeManaged(fs, joinPath(dir, CURSOR_SKILLS_DIR, folder, "SKILL.md"), `${skill.markdown.trim()}\n`),
      );
    }
    if (bundle.mcpServers.length) await syncMcpFile(joinPath(dir, CURSOR_MCP_FILE), CURSOR_MCP_FILE);
    // Honest skips: no Cursor-native equivalent — never invent a format.
    for (const subagent of bundle.subagents) {
      summary.push(`skipped: subagent ${subagent.name} (no Cursor equivalent; synced for Claude Code only)`);
    }
    if (bundle.permissions.length) {
      summary.push("skipped: permissions (no Cursor equivalent; see the Claude Code suggestion file)");
    }
  }

  return summary;
}

/* ------------------------------------------------------------------ */
/* Capability                                                          */
/* ------------------------------------------------------------------ */

export class AgentSyncCapability implements ConnectorCapability {
  readonly id = "agent-sync" as const;
  readonly label = "Team agent config sync";

  private lastSyncAt: number | null = null;
  private lastSummary: AgentSyncSummary = [];
  private lastError: string | null = null;

  constructor(private readonly options: { intervalMs?: number } = {}) {}

  async detect(ctx: CapabilityContext): Promise<CapabilityDetection> {
    const dirs = ctx.config.agentSync?.dirs ?? [];
    if (dirs.length === 0) {
      return {
        available: false,
        detail: "Setup required: add at least one repository directory to sync team agent config into.",
      };
    }
    const missing: string[] = [];
    for (const dir of dirs) {
      if (!(await dirExists(ctx.fs, dir))) missing.push(dir);
    }
    if (missing.length === dirs.length) {
      return { available: false, detail: `None of the configured directories exist: ${missing.join(", ")}` };
    }
    return {
      available: true,
      detail: `Syncing into ${dirs.length - missing.length} of ${dirs.length} configured director${dirs.length === 1 ? "y" : "ies"}.`,
      data: { dirs, missing },
    };
  }

  private async syncOnce(ctx: CapabilityContext): Promise<void> {
    const response = await ctx.transport.getJson(cloudUrl(ctx.config.baseUrl, ctx.endpoints.agentConfigBundle), {
      token: ctx.config.deviceToken,
    });
    if (!response.ok) {
      throw new Error(
        typeof response.data.error === "string" ? response.data.error : `Bundle fetch failed (HTTP ${response.status})`,
      );
    }
    const bundle = parseAgentConfigBundle(response.data);
    const summary: AgentSyncSummary = [];
    for (const dir of ctx.config.agentSync?.dirs ?? []) {
      if (!(await dirExists(ctx.fs, dir))) {
        summary.push(`skipped: ${dir} (directory does not exist)`);
        continue;
      }
      const flag = ctx.config.agentSync?.agent;
      const targets =
        flag === "claude"
          ? { claude: true, cursor: false }
          : flag === "cursor"
            ? { claude: false, cursor: true }
            : flag === "all"
              ? { claude: true, cursor: true }
              : await detectAgentTargets(ctx.fs, dir);
      // Nothing detected and nothing forced: keep the CLI's behavior (Claude Code).
      const effective = targets.claude || targets.cursor ? targets : { claude: true, cursor: false };
      const dirSummary = await materializeAgentConfig(ctx.fs, dir, bundle, effective);
      summary.push(...dirSummary.map((line) => `${dir}: ${line}`));
    }
    this.lastSummary = summary;
    this.lastSyncAt = ctx.clock.now();
    this.lastError = null;
  }

  async start(ctx: CapabilityContext): Promise<void> {
    const interval = this.options.intervalMs ?? AGENT_SYNC_INTERVAL_MS;
    while (!ctx.signal.aborted) {
      try {
        await this.syncOnce(ctx);
        ctx.log(`agent-sync: synced (${this.lastSummary.length} item(s)).`);
      } catch (error) {
        // Sync is a bonus, never a blocker: report and retry on the next interval.
        this.lastError = error instanceof Error ? error.message : String(error);
        ctx.log(`agent-sync: ${this.lastError} (will retry)`);
      }
      await ctx.clock.sleep(interval, ctx.signal);
    }
  }

  async stop(): Promise<void> {
    // The loop honors ctx.signal; nothing else to release.
  }

  status(): CapabilityReport {
    if (this.lastError) return { detail: `Last sync failed: ${this.lastError}`, data: { lastSyncAt: this.lastSyncAt } };
    if (this.lastSyncAt === null) return { detail: "No sync has completed yet." };
    return {
      detail: `Last sync wrote/verified ${this.lastSummary.length} item(s).`,
      data: { lastSyncAt: this.lastSyncAt, summary: this.lastSummary.slice(0, 50) },
    };
  }
}
