/**
 * Section help — how / why / when for every workbench and major tool.
 *
 * This is the in-app answer to "what is this screen for and when do I use it",
 * rendered inline by `components/help-tip.tsx` beside the hub tab bar and in full
 * on /docs. It is deliberately NOT prose: one sentence of what, one sentence of
 * why, the season moment, and at most five numbered steps.
 *
 * Rules for entries:
 * - Describe only what the surface actually does today. No roadmap, no invented
 *   capabilities, no fabricated metrics (the product itself does not fill in data,
 *   and neither does its help).
 * - `id` is `${hub}.${tabId}` so duplicate tab ids across hubs (impact, code,
 *   batteries, fmea…) stay distinct.
 * - Long-form tutorials still live in `articles.ts`; this registry is the
 *   task-first layer on top of it.
 */

import type { ProductHubDef } from "../nav/hubs";

export type SectionHelpHubId = ProductHubDef["id"];

export const SEASON_MOMENTS = [
  { id: "preseason", label: "Before season", blurb: "Offseason setup, carry-over, and training." },
  { id: "kickoff", label: "Kickoff week", blurb: "Game release through the first design decisions." },
  { id: "build", label: "Build season", blurb: "Design, build, code, money, and outreach." },
  { id: "pre-comp", label: "Week before comp", blurb: "Pack, inspect, brief, and rehearse." },
  { id: "comp-day", label: "Competition day", blurb: "Between matches, in the pit and the stands." },
  { id: "after", label: "After the season", blurb: "Retro, reporting, and handoff." },
] as const;

export type SeasonMoment = (typeof SEASON_MOMENTS)[number]["id"];

export type SectionHelpLink = {
  label: string;
  /** In-app path. Always starts with "/". */
  href: string;
};

export type SectionHelpEntry = {
  /** `${hub}.${tabId}` — unique across the registry. */
  id: string;
  hub: SectionHelpHubId;
  /** Tab id inside `PRODUCT_HUBS` for that hub. */
  tab: string;
  title: string;
  /** One sentence: what this surface is. */
  what: string;
  /** One sentence: the job it does for the team. */
  why: string;
  /** One sentence: the season moment it belongs to. */
  when: string;
  /** Season moments this section belongs to, for the /docs filter. */
  moments: SeasonMoment[];
  /** 1–5 numbered steps. */
  how: string[];
  /** Up to 3 short tips. */
  tips?: string[];
  related: SectionHelpLink[];
};

export const SECTION_HELP: SectionHelpEntry[] = [
  // ---------------------------------------------------------------- Competition
  {
    id: "competition.command",
    hub: "competition",
    tab: "command",
    title: "Event day",
    what: "The event-day board: your next match, countdown, bumper colour, partners, opponents, and pit cues for the active event.",
    why: "It keeps the drive team and pit reading the same next-three-matches picture instead of three phones and a paper schedule.",
    when: "Competition day, from load-in until the last match of the day.",
    moments: ["comp-day"],
    how: [
      "Connect The Blue Alliance and pick the active event under Team → Data — this tab follows that event.",
      "Open Event day; the next match card fills in from the posted schedule.",
      "Send the drive team to My Day for their own next-match view, and the pit to Pit.",
      "Work the pre-match briefing before each match, and the pre-match checklist in the pit.",
    ],
    tips: [
      "Blank cards mean the schedule is not synced yet.",
      "Keep the event selected all weekend; switching events resets the board's scope.",
    ],
    related: [
      { label: "My Day", href: "/my-day" },
      { label: "Pre-match briefing", href: "/briefing" },
      { label: "Team data & TBA sync", href: "/team/data" },
    ],
  },
  {
    id: "competition.briefing",
    hub: "competition",
    tab: "briefing",
    title: "Pre-match briefing",
    what: "One page per upcoming match: match card, game plan, your scouted alliance, opponents, the linked whiteboard play, drive-team readiness, and opponent film.",
    why: "It turns scouting, strategy, and film into the two-minute conversation the drive team has in the queue line.",
    when: "Competition day, in the queue for each match.",
    moments: ["comp-day"],
    how: [
      "Open it from Event day (or /briefing) with the active event set.",
      "Read the match card and alliance rows — every number is sourced from TBA/Statbotics or your own scouting.",
      "Attach the whiteboard play you want to run so the plan matches the board.",
      "Skim opponent film and the drive-team readiness row before you queue.",
    ],
    tips: [
      "Match Copilot was folded into this page — /match-copilot lands here.",
      "Sections stay empty when there is no scouting on a team; empty means unscouted, not average.",
    ],
    related: [
      { label: "Event day", href: "/command" },
      { label: "Match strategy cards", href: "/match-strategy-cards" },
      { label: "Match video", href: "/match-video-index" },
    ],
  },
  {
    id: "competition.schedule",
    hub: "competition",
    tab: "schedule",
    title: "Match schedule",
    what: "The posted qualification and playoff schedule for the active event, with filters for played and upcoming matches.",
    why: "It is the shared source of truth for when you play and who you play, so scouts and pit crew can plan shifts around it.",
    when: "Competition day, and the evening before once the schedule posts.",
    moments: ["pre-comp", "comp-day"],
    how: [
      "Set the active event and let reference sync pull the schedule.",
      "Filter to upcoming matches for queueing, or played matches to review.",
      "Hand the surrounding matches to scouting so shift coverage lines up.",
    ],
    tips: ["Matches appear only after the schedule is posted and synced."],
    related: [
      { label: "Event day", href: "/command" },
      { label: "Scout shifts", href: "/shift-balancer" },
    ],
  },
  {
    id: "competition.my-day",
    hub: "competition",
    tab: "my-day",
    title: "My Day",
    what: "A single-person view of your next match, bumper colour, partners, and opponents, pulled from The Blue Alliance.",
    why: "It gives each student the one thing they need next without making them read the whole event board.",
    when: "Competition day, on a phone in the pit or the stands.",
    moments: ["comp-day"],
    how: [
      "Open My Day with the active event set.",
      "Check bumper colour and match number before you head to the queue.",
      "Jump to the pre-match briefing when you need the full plan.",
    ],
    related: [
      { label: "Event day", href: "/command" },
      { label: "Pre-match briefing", href: "/briefing" },
    ],
  },
  {
    id: "competition.rankings",
    hub: "competition",
    tab: "rankings",
    title: "Rankings & playoffs",
    what: "Event rankings and the playoff bracket for the active event, sourced from TBA/Statbotics sync.",
    why: "It tells you where you actually stand before alliance selection instead of guessing from the arena screen.",
    when: "Competition day, especially the morning of alliance selection.",
    moments: ["comp-day"],
    how: [
      "Sync TBA/Statbotics under Team → Data.",
      "Read rankings between match blocks; brackets appear once playoffs begin.",
      "Carry the standings into the alliance desk and pick list.",
    ],
    related: [
      { label: "Alliance desk", href: "/alliance-selection-desk" },
      { label: "Rank projection", href: "/ranking-projection" },
    ],
  },
  {
    id: "competition.scouting",
    hub: "competition",
    tab: "scouting",
    title: "Scouting",
    what: "The match and pit scouting workbench — forms fill on the device, stay local until you sync, then feed strategy.",
    why: "Everything downstream (pick list, briefings, dossiers) is only as good as the scout entries collected here.",
    when: "Competition day; set up the forms and train scouts in the week before.",
    moments: ["pre-comp", "comp-day"],
    how: [
      "Publish a match and a pit form version under Forms before the event.",
      "Assign shifts so every match has coverage.",
      "Scouts open Scouting on their device and submit per match — entries queue offline.",
      "Sync when signal allows, then check Coverage for zero and thin cells.",
    ],
    tips: [
      "Venue Wi-Fi is unreliable by design of the venue, not the app — offline queueing is the normal path.",
      "Run Training mode with rookies before day one so their first real match is not their first form.",
    ],
    related: [
      { label: "Forms", href: "/scouting/forms" },
      { label: "Coverage", href: "/scout-coverage-live" },
      { label: "Training mode", href: "/scout-training-mode" },
    ],
  },
  {
    id: "competition.forms",
    hub: "competition",
    tab: "forms",
    title: "Scouting forms",
    what: "Where owners and admins configure, preview, and publish versioned match and pit scouting schemas.",
    why: "A published version is what scouts see and what analysis groups by, so schema changes stay traceable instead of silently shifting your data.",
    when: "Before the season and in the week before each event.",
    moments: ["preseason", "pre-comp"],
    how: [
      "Open Forms and start a draft match or pit schema.",
      "Configure fields and which are required, then preview.",
      "Publish the version — scouts and Coverage stay blank until a real version exists.",
      "Re-publish a new version rather than editing a live one mid-event.",
    ],
    tips: ["Keep the form short enough to finish inside one match — long forms lose the last 20 seconds."],
    related: [
      { label: "Scouting", href: "/scouting" },
      { label: "Schema A/B", href: "/scouting-schema-ab" },
      { label: "Data quality", href: "/data-quality-scorecard" },
    ],
  },
  {
    id: "competition.scout-coverage-live",
    hub: "competition",
    tab: "scout-coverage-live",
    title: "Scout coverage",
    what: "Live view of zero and thin match/team cells based on real scout-entry counts, with nudges for the coordinator.",
    why: "It catches the gap while you can still fill it, instead of discovering an unscouted alliance partner at selection.",
    when: "Competition day, checked every few match blocks.",
    moments: ["comp-day"],
    how: [
      "Open Coverage with the active event set.",
      "Look for zero cells first, then thin ones.",
      "Reassign a scout from Shifts to close the gap.",
    ],
    related: [
      { label: "Shifts", href: "/shift-balancer" },
      { label: "Scouting", href: "/scouting" },
    ],
  },
  {
    id: "competition.strategy",
    hub: "competition",
    tab: "strategy",
    title: "Strategy",
    what: "Match and event strategy built from The Blue Alliance, Statbotics, and your own scout notes — win/loss reads, matchup factors, and pick-list inputs.",
    why: "It is where scouting stops being a spreadsheet and becomes a decision the drive team can act on.",
    when: "Competition day between match blocks, and the evening before each event day.",
    moments: ["pre-comp", "comp-day"],
    how: [
      "Sync reference data and collect scout entries first — strategy stays blank without them.",
      "Open Strategy for the matchup read and the factors behind it.",
      "Push conclusions into the pick list and match strategy cards.",
      "Re-check after each block; Rating alerts flag teams whose form moved.",
    ],
    tips: ["Every claim shows its source — if a factor has no citation, treat it as unsupported."],
    related: [
      { label: "Pick list", href: "/picklist-collab" },
      { label: "Alliance desk", href: "/alliance-selection-desk" },
      { label: "Rating alerts", href: "/epa-trend-alerts" },
    ],
  },
  {
    id: "competition.video-analysis",
    hub: "competition",
    tab: "video-analysis",
    title: "Video",
    what: "Paste a match or pit video for the video Pi. You get a timeline with timestamps. Scouted numbers do not change until a person confirms.",
    why: "Film review should land on the match notes as 'from video', not silently rewrite what a scout typed.",
    when: "Competition day and the night after, as soon as match video exists.",
    moments: ["comp-day", "after"],
    how: [
      "Pair a Pi with the video role at Team → AI relays.",
      "Paste a YouTube, TBA, uploaded file, or pit camera link.",
      "Wait for the timeline. Each event is labelled from video.",
      "Tap Confirm to keep it as video evidence. That does not overwrite scout counts.",
    ],
    tips: ["If no video Pi is online the video stays Waiting and the page says so."],
    related: [
      { label: "AI relays", href: "/team/relays" },
      { label: "Match notes", href: "/match-notes-timeline" },
    ],
  },
  {
    id: "competition.alliance-selection-desk",
    hub: "competition",
    tab: "alliance-selection-desk",
    title: "Alliance desk",
    what: "The live pick board — shared slots, attached scout evidence, TBA conflict flags, and a drive-team export.",
    why: "Alliance selection happens in minutes; this keeps the whole strategy table on one board instead of shouting across the stands.",
    when: "Competition day, the hour before alliance selection.",
    moments: ["comp-day"],
    how: [
      "Build the ranked list in Pick list before selection opens.",
      "Open the desk so everyone at the table sees the same slots.",
      "Attach scout evidence to picks you will have to defend.",
      "Export the final board to the drive team before you walk to the field.",
    ],
    tips: ["Conflict flags come from TBA state — clear them before selection starts, not during."],
    related: [
      { label: "Pick clock", href: "/pick-clock" },
      { label: "Pick list", href: "/picklist-collab" },
      { label: "Justifier", href: "/picklist-justifier" },
    ],
  },
  {
    id: "competition.pick-clock",
    hub: "competition",
    tab: "pick-clock",
    title: "Pick clock",
    what: "Next-best-pick and the reason for it, sized for the 45-second alliance selection timer.",
    why: "When the clock is running you need one name and one sentence, not a table.",
    when: "Competition day, during alliance selection itself.",
    moments: ["comp-day"],
    how: [
      "Have a pick list and scout data in place. The clock stays blank until those exist.",
      "Open Pick clock at the table when selection begins.",
      "Read the next pick and its why, then confirm with the desk.",
    ],
    related: [
      { label: "Alliance desk", href: "/alliance-selection-desk" },
      { label: "Pick list", href: "/picklist-collab" },
    ],
  },
  {
    id: "competition.intel",
    hub: "competition",
    tab: "intel",
    title: "Research",
    what: "Look up another FRC team by number or name. Season scores, our scouting, and public notes stay blank until they exist.",
    why: "It answers \"who is this team\" before you meet them in a match or at a pick.",
    when: "The week before an event, and between blocks on competition day.",
    moments: ["pre-comp", "comp-day"],
    how: [
      "Search for a team number or name.",
      "Read season scores — they stay blank until this team's records are on file.",
      "Find public notes only for the handful of teams that matter, and check the citations.",
    ],
    tips: ["Public-note lookups use team credits; run them on the teams that matter, not the whole event."],
    related: [
      { label: "Team dossier", href: "/dossier" },
      { label: "Watchlist", href: "/opponent-watchlist" },
    ],
  },
  {
    id: "competition.dossier",
    hub: "competition",
    tab: "dossier",
    title: "Team dossier",
    what: "Fact cards for one team — TBA identity, EPA and records from Statbotics/TBA, and your own scout notes, each with a citation.",
    why: "It is the single page you hand a scout or a drive coach when they ask \"what do we know about 1234\".",
    when: "The week before an event, and before a pick or a playoff match.",
    moments: ["pre-comp", "comp-day"],
    how: [
      "Open a team from Intel or search directly.",
      "Read the fact cards; every one names its source.",
      "Add your scout notes so the next person sees them too.",
    ],
    related: [
      { label: "Research", href: "/intel" },
      { label: "Drive-team tags", href: "/team-tags" },
    ],
  },
  {
    id: "competition.match-checklist",
    hub: "competition",
    tab: "match-checklist",
    title: "Pre-match checklist",
    what: "A one-tap timed checklist per match — bumper colour, battery strap, SB50 lock, tether, code — completed in the pit before each match.",
    why: "The failures that cost matches are the boring ones, and a timed checklist is what stops a team from hanging the wrong bumpers twice.",
    when: "Competition day, before every single match.",
    moments: ["comp-day"],
    how: [
      "Start a checklist for the upcoming match.",
      "Tap each item as it is physically verified — progress comes only from real checks.",
      "Clear the last item before the robot leaves the pit.",
    ],
    tips: ["Do not pre-tick items you plan to do; the timing record is only useful if it is honest."],
    related: [
      { label: "Pit command", href: "/pit" },
      { label: "Charge plan", href: "/battery-rotation" },
    ],
  },
  {
    id: "competition.pit",
    hub: "competition",
    tab: "pit",
    title: "Pit command",
    what: "The pit board — work in progress, the robot release board, and who is responsible for the next fix.",
    why: "It keeps a crowded pit from losing track of what still has to happen before the robot is released to queue.",
    when: "Competition day, all day.",
    moments: ["comp-day"],
    how: [
      "Open Pit command on the pit display or a tablet.",
      "Log work as it starts, not after it finishes.",
      "Use the release board to declare the robot ready before queueing.",
      "Send anything that recurs to repair triage and FMEA.",
    ],
    related: [
      { label: "Repair triage", href: "/pit-repair-triage" },
      { label: "Pre-match checklist", href: "/match-checklist" },
      { label: "FMEA", href: "/fmea" },
    ],
  },

  // ---------------------------------------------------------------------- Team
  {
    id: "team.calendar",
    hub: "team",
    tab: "calendar",
    title: "Calendar",
    what: "Subteam calendars for practices, build sessions, deadlines, and events, filterable by group or viewed whole-team.",
    why: "It is the answer to \"when are we meeting and who has to be there\" without a group chat archaeology dig.",
    when: "All season, starting in the preseason when you set the meeting rhythm.",
    moments: ["preseason", "kickoff", "build", "pre-comp", "after"],
    how: [
      "Create subteams so events can be scoped to a group.",
      "Add an event with a date and, when it repeats, a repeat rule.",
      "Assign members so the right people see it in Coming up.",
      "Filter by subteam when the whole-team view gets noisy.",
    ],
    tips: ["Editing one occurrence of a repeating event asks whether you mean this one or the series."],
    related: [
      { label: "People", href: "/attendance" },
      { label: "Season plan", href: "/season-planning-workspace" },
    ],
  },
  {
    id: "team.messages",
    hub: "team",
    tab: "messages",
    title: "Chat",
    what: "The team channel plus private messages, scoped to this team.",
    why: "Team decisions stay with the team instead of in a personal chat app nobody can search next year.",
    when: "All season.",
    moments: ["preseason", "kickoff", "build", "pre-comp", "comp-day", "after"],
    how: [
      "Open Chat — your team channel opens with this team.",
      "Start a private message for a one-to-one thread.",
      "Invite anyone who is missing under Team admin.",
    ],
    tips: ["People only appear once they have accepted an invite to this team."],
    related: [
      { label: "Team admin", href: "/team/admin" },
      { label: "Calendar", href: "/team/calendar" },
    ],
  },
  {
    id: "team.attendance",
    hub: "team",
    tab: "attendance",
    title: "People & attendance",
    what: "One-tap attendance marks against real workspace members for practices and meetings.",
    why: "Attendance is the evidence behind hours, awards, and the \"who is actually here\" question mentors ask every session.",
    when: "Every meeting from preseason through the last event.",
    moments: ["preseason", "kickoff", "build", "pre-comp", "after"],
    how: [
      "Invite teammates so the roster is real before you start marking.",
      "Open People at the start of a session and mark who showed up.",
      "Use the Hours kiosk instead when you want students to sign themselves in.",
      "Read the engagement digest for who needs a check-in.",
    ],
    tips: ["Totals stay empty until you mark someone — there are no assumed presence rates."],
    related: [
      { label: "Hours kiosk", href: "/hours" },
      { label: "My hours", href: "/hours-self-view" },
      { label: "Team admin", href: "/team/admin" },
    ],
  },
  {
    id: "team.hours",
    hub: "team",
    tab: "hours",
    title: "Hours kiosk",
    what: "A scan-in station plus the mentor engagement digest — top contributors, goal progress, and who needs a check-in.",
    why: "Self scan-in gets hour totals that survive a scholarship or award question, without a mentor holding a clipboard.",
    when: "Build season, at the shop door.",
    moments: ["preseason", "build", "pre-comp"],
    how: [
      "Open Hours and press Shop kiosk to put the shop machine on the scan screen.",
      "Students scan or type their code to sign in and out.",
      "Mentors read the engagement digest for participation and check-in prompts.",
      "Students see their own totals under My hours.",
    ],
    tips: ["The kiosk is a shared screen — leave it on /hours/kiosk, not an admin's logged-in view."],
    related: [
      { label: "Shop kiosk", href: "/hours/kiosk" },
      { label: "People", href: "/attendance" },
      { label: "My hours", href: "/hours-self-view" },
    ],
  },
  {
    id: "team.todos",
    hub: "team",
    tab: "todos",
    title: "Work",
    what: "The shared action-item list for the team, with the practice, task board, and season-plan tools nested underneath.",
    why: "It is where \"someone should do that\" turns into an owned item with a name on it.",
    when: "Build season, reviewed at the start and end of every meeting.",
    moments: ["kickoff", "build", "pre-comp"],
    how: [
      "Add the first real action item.",
      "Give every item an owner and a due date.",
      "Filter by view to run a stand-up off the list.",
      "Promote recurring themes into the season plan or the risk register.",
    ],
    related: [
      { label: "Task board", href: "/tasks" },
      { label: "Standup", href: "/standup-digest" },
      { label: "Season plan", href: "/season-planning-workspace" },
    ],
  },
  {
    id: "team.season-planning-workspace",
    hub: "team",
    tab: "season-planning-workspace",
    title: "Season plan",
    what: "Goals broken into milestones with owners and due dates, with progress computed from real attendance and build-task data.",
    why: "It is the one place a mentor can answer \"are we actually on track\" without a gut feeling.",
    when: "Kickoff week, then reviewed weekly through build season.",
    moments: ["kickoff", "build"],
    how: [
      "Write the season goals first.",
      "Break each into milestones with an owner and a due date.",
      "Let progress fill in from attendance and build tasks — the percentage stays blank until milestones exist.",
      "Review it at the same weekly meeting every week.",
    ],
    tips: ["Cross-check it against Season goals, Calendar, and Attendance rather than tracking three plans."],
    related: [
      { label: "Season roadmap", href: "/roadmap" },
      { label: "Objectives", href: "/goals" },
      { label: "Burndown", href: "/build-burndown" },
    ],
  },
  {
    id: "team.practice",
    hub: "team",
    tab: "practice",
    title: "Driver practice",
    what: "Practice sessions where you time cycles, log reps and misses, and link the session to attendance and build tasks.",
    why: "Drivers get good by measured reps, and a logged cycle time is the only honest way to know whether practice is working.",
    when: "Build season once the robot drives, and the week before each event.",
    moments: ["build", "pre-comp"],
    how: [
      "Create a practice session with a title.",
      "Time a rep and log the cycle — mark misses as misses.",
      "Roll call attendance from the session so practice counts as a meeting.",
      "Link the build task the session was blocked on, if any.",
    ],
    related: [
      { label: "Work", href: "/todos" },
      { label: "Driver tryouts", href: "/driver-tryouts" },
      { label: "Batteries", href: "/batteries" },
    ],
  },
  {
    id: "team.retro",
    hub: "team",
    tab: "retro",
    title: "Retro",
    what: "Start / stop / continue feedback sessions collected from the team.",
    why: "The lessons from an event evaporate in about a week unless someone writes them down while they still sting.",
    when: "The evening after each event, and again at the end of the season.",
    moments: ["comp-day", "after"],
    how: [
      "Create a retro session — items stay empty until people add them.",
      "Collect start / stop / continue from everyone, not just the leads.",
      "Turn the agreed changes into work items or risks so they survive the meeting.",
    ],
    related: [
      { label: "Work", href: "/todos" },
      { label: "Season report", href: "/season-report" },
      { label: "Exit interviews", href: "/exit-interview" },
    ],
  },
  {
    id: "team.knowledge",
    hub: "team",
    tab: "knowledge",
    title: "Playbook",
    what: "The team wiki — searchable pages with history, holding the processes and decisions that would otherwise leave with a senior.",
    why: "It is the difference between a team that rebuilds knowledge every year and one that compounds it.",
    when: "All season; hardest to backfill, easiest in the offseason.",
    moments: ["preseason", "build", "after"],
    how: [
      "Create a page for a process you keep re-explaining.",
      "Link it from the tool it describes so people find it in context.",
      "Check Knowledge gaps for subsystems and decisions with no page.",
      "Review pages after the season while the details are fresh.",
    ],
    tips: ["Bus factor and Team health read from this — thin coverage there usually means thin pages here."],
    related: [
      { label: "Knowledge gaps", href: "/knowledge-gap" },
      { label: "Bus factor", href: "/bus-factor" },
      { label: "Engineering notebook", href: "/notebook" },
    ],
  },
  {
    id: "team.roadmap",
    hub: "team",
    tab: "roadmap",
    title: "Season roadmap",
    what: "Kickoff to first event in the order it has to happen, with every date calculated from the kickoff date you enter.",
    why: "New coaches' hardest question is not how to use a tool, it is what to prioritise this week — this answers that.",
    when: "Kickoff week, then as your weekly checkpoint through build.",
    moments: ["preseason", "kickoff", "build"],
    how: [
      "Enter your kickoff date — every date on the page is derived from it.",
      "Walk the phases in order and mark what is done.",
      "Open the linked tool from each step rather than hunting for it.",
    ],
    tips: ["The dates are computed from your kickoff, not invented FIRST deadlines — check the official schedule for anything you submit."],
    related: [
      { label: "Season plan", href: "/season-planning-workspace" },
      { label: "Kickoff", href: "/kickoff" },
      { label: "Playbook", href: "/team/knowledge" },
    ],
  },
  {
    id: "team.migrate",
    hub: "team",
    tab: "migrate",
    title: "Bring your season",
    what: "Import an existing season from one source at a time — preview real rows, then commit.",
    why: "Teams switch tools mid-season only if the old data comes along; this is the path that does not lose it.",
    when: "Before the season, or the week you decide to switch.",
    moments: ["preseason", "kickoff"],
    how: [
      "Pick one source and connect it (some sources need env setup — the page says which).",
      "Preview the real rows it found; nothing is committed yet.",
      "Commit the import, then dual-run both tools until you are confident.",
      "Turn the old tool off only after a full week of dual-running.",
    ],
    tips: ["Preview does not fill in events or titles — an empty preview means the source had nothing to read."],
    related: [
      { label: "Playbook", href: "/team/knowledge" },
      { label: "Team data", href: "/team/data" },
    ],
  },
  {
    id: "team.files",
    hub: "team",
    tab: "files",
    title: "Files",
    what: "One file space for the team and for you: folders, share-by-link or email, and Media Library / CAD Vault / older Team Library as folders inside it.",
    why: "It ends the hunt across Google Drive, a USB stick, and someone's phone. New files go here; old Library links still show as a folder.",
    when: "All season, from the first vendor manual to the last season export.",
    moments: ["preseason", "kickoff", "build", "pre-comp", "after"],
    how: [
      "Open Team → Files. Team space is shared; Personal is only yours.",
      "Make folders and drop files in. Paste an Onshape or web link as a file if that is what you have.",
      "Share a file with a link or an email when a parent, sponsor, or another team needs it.",
      "Mark a file available offline when you will need it in the stands.",
    ],
    tips: [
      "Files over the hosted cap belong on a paired storage node, not the cloud database.",
      "The old Team Library still lists inside Files until those rows are copied into Team files.",
    ],
    related: [
      { label: "Storage node", href: "/team/storage" },
      { label: "Playbook", href: "/team/knowledge" },
      { label: "Media library", href: "/media-library" },
    ],
  },
  {
    id: "team.team-storage",
    hub: "team",
    tab: "team-storage",
    title: "Storage node",
    what: "A self-hosted always-on box (a Raspberry Pi in the shop is the canonical choice) that stores the team's large files on its own disk — bytes on your hardware, only metadata in the cloud.",
    why: "Large media and exports would otherwise max out the hosted database; your own disk is cheap and yours.",
    when: "Preseason to set up; it runs unattended after that.",
    moments: ["preseason", "build"],
    how: [
      "Run the single service file on the box and note the 8-character pairing code it prints.",
      "An owner or admin enters the code at /team/storage to pair.",
      "Watch the node report real disk stats — Online within a minute of its first heartbeat.",
      "For access away from the shop LAN, give it a public URL (Tailscale Funnel or cloudflared) and paste it into the node's card.",
    ],
    tips: [
      "The cloud cannot reach a node behind your router without a public URL — the UI says node-unreachable honestly rather than pretending.",
      "The node refuses writes past its disk quota instead of filling the card.",
    ],
    related: [
      { label: "Files", href: "/files" },
      { label: "Media library", href: "/media-library" },
    ],
  },
  {
    id: "team.team-relays",
    hub: "team",
    tab: "team-relays",
    title: "AI relays",
    what: "Raspberry Pis that run Ask AI, Bugbot, assembly manuals, and video analysis. Pair with a code the installer prints — never a website cookie.",
    why: "The shop's own computers answer first so chats stay fast and cheap, then the team's keys, then hosted keys as a last resort.",
    when: "Set up before build season; it runs unattended after that.",
    moments: ["preseason", "build", "comp-day"],
    how: [
      "Install the relay worker on a Pi. It prints an 8-character code.",
      "An owner or admin types that code at Team → AI relays.",
      "Give the Pi a role: chat, agent, or video. When the video Pi is idle it can run agent jobs too.",
      "Watch the card: online means a heartbeat in the last two minutes.",
    ],
    tips: [
      "Do not paste a Freebuff website cookie. That is not allowed. Paste the relay endpoint and token, or approve the pairing code.",
    ],
    related: [
      { label: "Connectors", href: "/connectors" },
      { label: "Video", href: "/video-analysis" },
    ],
  },
  {
    id: "team.my-kit",
    hub: "team",
    tab: "my-kit",
    title: "My kit",
    what: "One personal page collecting your tasks, events and RSVPs, duties, scout shifts, media due, hours, tool loans, and money items — every row linking to the surface that owns it.",
    why: "It answers 'what do I, personally, need right now' without opening six tabs.",
    when: "All season — check it at the start of each meeting or event day.",
    moments: ["preseason", "kickoff", "build", "pre-comp", "comp-day"],
    how: [
      "Open My kit; sections order themselves by your subteam focus.",
      "Work the items flagged as due or overdue first.",
      "Tap a row to act on it in its owning surface — My kit itself writes nothing.",
    ],
    tips: ["An empty section means you truly have nothing there; a feature missing from this deployment says so separately."],
    related: [
      { label: "Work", href: "/todos" },
      { label: "My hours", href: "/hours-self-view" },
      { label: "Calendar", href: "/team/calendar" },
    ],
  },
  {
    id: "team.risks",
    hub: "team",
    tab: "risks",
    title: "Risk register",
    what: "Season risks scored by likelihood × impact, with mitigations and an owner, tracked to closure.",
    why: "It surfaces the schedule, funding, and people risks that sink seasons — the ones FMEA never sees because nothing has broken yet.",
    when: "Kickoff week, then reviewed weekly through build season.",
    moments: ["kickoff", "build", "pre-comp"],
    how: [
      "Add a schedule, technical, funding, or people risk.",
      "Score real likelihood and impact — the top score stays blank until you do.",
      "Assign a mitigation and an owner.",
      "Review and close them weekly; log actual failures in FMEA instead.",
    ],
    tips: ["Risk register is for what might happen; FMEA is for what already did."],
    related: [
      { label: "Risk burndown", href: "/risk-burndown" },
      { label: "FMEA", href: "/fmea" },
      { label: "Season plan", href: "/season-planning-workspace" },
    ],
  },
  {
    id: "team.notebook",
    hub: "team",
    tab: "notebook",
    title: "Engineering notebook",
    what: "The engineering and build notebook — dated entries documenting design work as it happens.",
    why: "Judged awards and next year's team both need the reasoning, not just the finished robot.",
    when: "Build season, written the day the work happens.",
    moments: ["kickoff", "build", "pre-comp"],
    how: [
      "Add an entry the same day as the work, with what was tried and what happened.",
      "Link the subsystem or decision it belongs to.",
      "Pull from it when writing award essays and the season report.",
    ],
    related: [
      { label: "Playbook", href: "/team/knowledge" },
      { label: "Notes & decisions", href: "/decisions" },
      { label: "Awards", href: "/team/awards" },
    ],
  },
  {
    id: "team.training",
    hub: "team",
    tab: "training",
    title: "Training matrix",
    what: "Who is signed off on mill, lathe, wiring, drive, and safety, with who signed them off and when it expires.",
    why: "It answers \"is anyone here allowed to run that machine tonight\" without asking around, and it is the record if something goes wrong.",
    when: "Before season while training happens, and every time a new student joins.",
    moments: ["preseason", "kickoff", "build"],
    how: [
      "List the skills your shop actually gates on.",
      "Record a sign-off with the mentor who gave it and an expiry where it matters.",
      "Check coverage before scheduling a build night around one machine.",
      "Re-sign expired rows rather than deleting them.",
    ],
    tips: ["Coverage reflects only what you record — an empty cell means unrecorded, not unqualified."],
    related: [
      { label: "People", href: "/attendance" },
      { label: "Skills", href: "/skills-graph" },
      { label: "Safety training", href: "/safety-training" },
    ],
  },
  {
    id: "team.tool-checkout",
    hub: "team",
    tab: "tool-checkout",
    title: "Tool checkout",
    what: "A loan ledger for shop tools: who has each one and when it is due back.",
    why: "Missing tools cost build nights and travel days; this makes the last holder findable instead of anonymous.",
    when: "Build season in the shop, and at an event for anything that travels.",
    moments: ["build", "pre-comp", "comp-day"],
    how: [
      "Add the tools worth tracking — the ledger starts empty.",
      "Check a tool out to a person with a due-back date.",
      "Check it back in when it returns to the drawer.",
      "Sweep the overdue list at the end of the night.",
    ],
    related: [
      { label: "Equipment", href: "/equipment-maintenance" },
      { label: "Work", href: "/todos" },
      { label: "Pit map", href: "/pit-map-planner" },
    ],
  },

  // ------------------------------------------------------------------ Business
  {
    id: "business.overview",
    hub: "business",
    tab: "overview",
    title: "Business overview",
    what: "The season's business picture in one place — budget, orders, partners, grants, and award evidence.",
    why: "It gives the business lead and the head mentor the same view of whether the season is funded.",
    when: "Preseason to set the plan, then monthly through build.",
    moments: ["preseason", "kickoff", "build", "after"],
    how: [
      "Choose the organisation for this team so the numbers are scoped correctly.",
      "Set the season budget under Money.",
      "Work the sponsor pipeline and grants from their own tabs.",
      "Log outreach and awards under Outreach so the evidence exists when you need it.",
    ],
    tips: ["Award totals appear only after you record a real award — nothing is pre-filled."],
    related: [
      { label: "Money", href: "/business?tab=finance" },
      { label: "Sponsors", href: "/business?tab=sponsors" },
      { label: "Outreach", href: "/business?tab=evidence" },
    ],
  },
  {
    id: "business.finance",
    hub: "business",
    tab: "finance",
    title: "Money",
    what: "The season budget with orders, season costs, vendor lead times, and the vendor directory nested underneath.",
    why: "Set the budget once and every purchase decision has something to be compared against instead of a vibe.",
    when: "Preseason for the budget; build season for every order.",
    moments: ["preseason", "kickoff", "build"],
    how: [
      "Set the season budget before the first order.",
      "Raise purchase requests so the reason travels with the request.",
      "Track allocation versus committed spend as orders move to receiving.",
      "Check vendor lead times before ordering anything on the critical path.",
    ],
    tips: ["Lead time, not price, is what usually breaks a build-season order."],
    related: [
      { label: "Overview", href: "/business?tab=overview" },
      { label: "Lead times", href: "/vendor-lead-times" },
      { label: "Vendors", href: "/vendors" },
    ],
  },
  {
    id: "business.reimbursements",
    hub: "business",
    tab: "reimbursements",
    title: "Reimbursements",
    what: "Members file claims with a receipt photo; the treasurer approves, denies, and marks paid — and only a paid claim moves the team ledger.",
    why: "The gearbox a parent bought at 11pm stops living in a text thread and starts living in a queue with a receipt attached.",
    when: "Build season and event travel — whenever someone fronts money.",
    moments: ["build", "pre-comp", "comp-day", "after"],
    how: [
      "File the claim: amount, what it was for, and a photo of the receipt (downscaled in the browser before upload).",
      "Submit it — drafts are visible only to you until then.",
      "An owner/admin approves or denies; denied claims show the note so you can fix and resubmit.",
      "Mark paid when the money actually moves — that is the moment it lands in the ledger.",
    ],
    tips: ["Approved-but-unpaid is a promise, not cash: the balance only counts paid claims, and undoing a payment removes the ledger row too."],
    related: [
      { label: "Money", href: "/business?tab=finance" },
      { label: "Orders", href: "/orders" },
      { label: "Season costs", href: "/costs" },
    ],
  },
  {
    id: "business.sponsors",
    hub: "business",
    tab: "sponsors",
    title: "Sponsors",
    what: "The sponsor pipeline and CRM, with packages, the sponsor wall, renewal ROI, and the tier calculator nested underneath.",
    why: "Sponsorship is a relationship record, not a logo folder — this keeps who promised what and when to follow up.",
    when: "Preseason and early build, when asks land best.",
    moments: ["preseason", "kickoff", "build", "after"],
    how: [
      "Add sponsors to the CRM before attaching packages.",
      "Define packages and what each recognition tier includes.",
      "Record payment and approval — recognition only goes live after both.",
      "Work renewals with last season's ROI in hand.",
    ],
    tips: ["Attaching a package to a sponsor that is not in the CRM is blocked on purpose."],
    related: [
      { label: "Packages", href: "/sponsorship" },
      { label: "Sponsor wall", href: "/sponsor-wall" },
      { label: "Renewal ROI", href: "/sponsor-renewal-roi" },
    ],
  },
  {
    id: "business.sponsorship",
    hub: "business",
    tab: "sponsorship",
    title: "Sponsorship packages",
    what: "The one-pager builder: who you are, what you do, what you ask, and what a sponsor gets, exportable as PDF.",
    why: "It is the artifact you actually hand a business, built from this team's story rather than a generic template.",
    when: "Preseason and early build, before the asks go out.",
    moments: ["preseason", "kickoff"],
    how: [
      "Compose the value props for cash, parts, and mentorship.",
      "Write who you are, what you do, and what you ask.",
      "Spell out what the sponsor gets at each level.",
      "Export the PDF and send it with a named contact, not a generic address.",
    ],
    tips: ["Only this team's story is used — nothing is borrowed from other orgs in the team."],
    related: [
      { label: "Sponsors", href: "/business?tab=sponsors" },
      { label: "Tier calculator", href: "/sponsor-tier-calculator" },
      { label: "Matching gifts", href: "/matching-gift-finder" },
    ],
  },
  {
    id: "business.grants",
    hub: "business",
    tab: "grants",
    title: "Grants",
    what: "The grant writing workbench — research, draft, review, submit, and report, with amounts you enter yourself.",
    why: "Grants are won by reusable, sourced writing; this keeps the drafts and their receipts together across years.",
    when: "Preseason and build season, on each funder's deadline.",
    moments: ["preseason", "build", "after"],
    how: [
      "Turn a deadline into an owned plan with a due date.",
      "Draft in the editor, or open Writer for a metered draft.",
      "Attach the impact and award facts the narrative claims.",
      "Submit, then come back to file the report when it is due.",
    ],
    tips: ["Amounts stay empty until you type them — no figure is estimated for you."],
    related: [
      { label: "Reports", href: "/grant-report" },
      { label: "Eligibility", href: "/grant-eligibility-matcher" },
      { label: "Writer", href: "/writer" },
    ],
  },
  {
    id: "business.evidence",
    hub: "business",
    tab: "evidence",
    title: "Outreach & evidence",
    what: "The evidence trail — outreach and impact activities, fundraisers, award tracking, essays, and judge pitch practice.",
    why: "Impact and Engineering Inspiration are won by a logged trail, and grant narratives need the same facts.",
    when: "All season as things happen; too late to reconstruct in award week.",
    moments: ["preseason", "build", "pre-comp", "after"],
    how: [
      "Log every STEM demo, mentoring session, and community event as it happens.",
      "Record awards you win so the totals are real.",
      "Draft the impact essay from the logged activities.",
      "Rehearse with judge pitch practice before the event.",
    ],
    tips: ["Empty means nothing logged — it is not a placeholder scoreboard."],
    related: [
      { label: "Impact log", href: "/impact" },
      { label: "Award tracker", href: "/award-tracker" },
      { label: "Judge pitch", href: "/judge-sim" },
    ],
  },
  {
    id: "business.impact",
    hub: "business",
    tab: "impact",
    title: "Impact log",
    what: "A log of outreach, STEM demos, and mentoring, with readiness computed only from what you record.",
    why: "It is the raw material for the Impact award, grant narratives, and the sponsor conversation about reach.",
    when: "All season, entered the week the activity happens.",
    moments: ["preseason", "build", "pre-comp", "after"],
    how: [
      "Add an activity with its category, date, and who it reached.",
      "Keep entering as the season runs — people reached stays blank until you log it.",
      "Pull from the log when writing essays and grant reports.",
    ],
    related: [
      { label: "Impact essay", href: "/impact-essay" },
      { label: "Outreach calendar", href: "/outreach-calendar" },
      { label: "Grants", href: "/team/grants" },
    ],
  },
  {
    id: "business.awards-workbench",
    hub: "business",
    tab: "awards-workbench",
    title: "Awards",
    what: "Pick an award from the FIRST catalog to pre-load its essay prompts, draft responses, and record wins.",
    why: "Award essays reuse the same facts every year — starting from the catalog prompts beats starting from a blank page.",
    when: "Build season, well before the submission deadline.",
    moments: ["build", "pre-comp", "after"],
    how: [
      "Start a catalog award to seed the essay prompts.",
      "Draft responses against each prompt, citing logged impact and notebook entries.",
      "Record wins so grant writing can reuse them.",
    ],
    tips: ["Awards you already earned can be logged without inventing history for years you did not compete."],
    related: [
      { label: "Award tracker", href: "/award-tracker" },
      { label: "Impact log", href: "/impact" },
      { label: "Engineering notebook", href: "/notebook" },
    ],
  },

  // --------------------------------------------------------------------- Build
  {
    id: "build.kickoff",
    hub: "build",
    tab: "kickoff",
    title: "Kickoff",
    what: "The kickoff workspace: a release summary of the new game, the capabilities you decide to chase, and the team's open questions.",
    why: "It turns kickoff weekend's noise into a written list of capabilities and unknowns that Strategy and Build can work from.",
    when: "Kickoff weekend and the week after.",
    moments: ["kickoff"],
    how: [
      "Generate or write the release summary for the season's game.",
      "List the capabilities you intend to build — these seed Strategy priorities.",
      "Capture the team's real open questions; empty stays empty until someone asks one.",
      "Convert answered questions into design decisions and build tasks.",
    ],
    related: [
      { label: "Season roadmap", href: "/roadmap" },
      { label: "Strategy", href: "/strategy" },
      { label: "Subsystem specs", href: "/subsystems" },
    ],
  },
  {
    id: "build.cad",
    hub: "build",
    tab: "cad",
    title: "CAD",
    what: "The CAD workspace for the connected Onshape (or Fusion) document, scoped to your org, with a change radar and sketch-to-brief.",
    why: "It puts CAD activity where the rest of the build lives, so design changes are visible to people who are not in the CAD tab all day.",
    when: "Build season, from the first layout onwards.",
    moments: ["kickoff", "build"],
    how: [
      "Open CAD from your team so the agent stays scoped to the right org.",
      "Connect Onshape under CAD setup — the page says to ask a mentor when Onshape is not ready, rather than failing.",
      "Watch Change radar for edits that affect other subteams.",
      "Turn a sketch into a written brief when handing work to another student.",
    ],
    tips: ["If Onshape is not ready yet, ask a mentor — nothing here works around a missing connection."],
    related: [
      { label: "Change radar", href: "/cad-change-radar" },
      { label: "Sketch to brief", href: "/sketch-to-brief" },
      { label: "Blueprint", href: "/robot" },
    ],
  },
  {
    id: "build.code",
    hub: "build",
    tab: "code",
    title: "Code",
    what: "The code workbench — paste or load subsystem code for a local pattern review, with deploy log and code-vs-match analysis nested underneath.",
    why: "It gives programmers a second reader for the mistakes that only show up on the field.",
    when: "Build season, and after any change you plan to deploy.",
    moments: ["build", "pre-comp", "comp-day"],
    how: [
      "Paste the subsystem code, or load the teaching sample to see how findings read.",
      "Run the local pattern review — it works without a model key.",
      "Fix findings, then still run simulation tests: an empty result is not certification.",
      "Record the deploy in the deploy log so match behaviour can be traced back to a build.",
    ],
    tips: ["A clean pass means no local rule matched, not that the code is correct."],
    related: [
      { label: "Get unstuck", href: "/troubleshoot" },
      { label: "AI Bugbot", href: "/bugbot" },
      { label: "Deploy log", href: "/code-deploy-log" },
    ],
  },
  {
    id: "build.troubleshoot",
    hub: "build",
    tab: "troubleshoot",
    title: "Get unstuck",
    what: "Check-by-check troubleshooting for the control-system failures that stop teams, where each step says what it rules out and each fix cites its doc.",
    why: "Control-system dead ends are the single most common thing that stalls a build night, and guessing wastes the whole session.",
    when: "Build season and competition day, the moment the robot stops responding.",
    moments: ["build", "pre-comp", "comp-day"],
    how: [
      "Describe the problem in your own words, or skip straight to the symptom list — both routes run the same curated checklist.",
      "Work the checks in order — each one says what it rules out, so you narrow instead of guessing.",
      "Follow the cited doc for the fix rather than a remembered forum post.",
      "Close the walk as fixed or stuck; the fixed ones stay listed so the next person starts where you finished.",
    ],
    tips: [
      "AI only picks the starting point and rewords the first question — the checks and fixes are the curated tree, unchanged.",
      "Log anything that took more than one session into FMEA so it is faster next time.",
    ],
    related: [
      { label: "Code", href: "/code" },
      { label: "Wiring check", href: "/wiring-diagnoser" },
      { label: "FMEA", href: "/fmea" },
    ],
  },
  {
    id: "build.bugbot",
    hub: "build",
    tab: "bugbot",
    title: "AI Bugbot",
    what: "Scans connected GitHub robot code — subscription Bugbot, or Ultra at a flat fee per scan, fix, and recheck — with findings that quote the source.",
    why: "It reviews the whole repo rather than the one file you thought to paste, and never touches your branch.",
    when: "Build season, before a deploy that matters, and the week before an event.",
    moments: ["build", "pre-comp"],
    how: [
      "Connect the team's GitHub robot-code repo.",
      "Run a scan; every finding quotes the source it came from.",
      "Apply fixes yourself — Bugbot never deploys or pushes.",
      "Recheck after the fix lands.",
    ],
    tips: ["Ultra is metered per scan / fix / recheck, so scan a branch you are about to ship, not every commit."],
    related: [
      { label: "Code", href: "/code" },
      { label: "Deploy log", href: "/code-deploy-log" },
      { label: "AI controls", href: "/team/budgets" },
    ],
  },
  {
    id: "build.agent-config",
    hub: "build",
    tab: "agent-config",
    title: "Team agent config",
    what: "Shared rules, subagent definitions, MCP servers, permission snippets, and skills for coding agents — synced into every member's Claude Code and Cursor with one command.",
    why: "The team's agent conventions stop living on one student's laptop and start versioned where everyone can read them.",
    when: "Preseason to set up; whenever the team's coding conventions change.",
    moments: ["preseason", "build"],
    how: [
      "Author items at /team/agent-config — invalid drafts still save, but are excluded from sync until fixed.",
      "Choose per item whether the entire team or only specific people see it.",
      "Each member runs `vantage-cad agent sync` in the robot-code repo to write Claude Code and Cursor files.",
      "Custom agents pull the same content as typed JSON from /api/agent-config/bundle.",
    ],
    tips: [
      "MCP entries refuse real credentials — use ${PLACEHOLDER} values each member sets locally.",
      "Permission snippets are never merged automatically; the sync prints them for a human to apply.",
    ],
    related: [
      { label: "Code", href: "/code" },
      { label: "AI Bugbot", href: "/bugbot" },
    ],
  },
  {
    id: "build.fmea",
    hub: "build",
    tab: "fmea",
    title: "Robot & FMEA",
    what: "The robot workbench, rooted on FMEA — every in-match and pit failure logged against a subsystem with real occurrence, severity, and detection scores.",
    why: "RPN ranking is how you decide which failure to spend the next build night on instead of the loudest one.",
    when: "Build season onwards, logged the day something breaks.",
    moments: ["build", "pre-comp", "comp-day", "after"],
    how: [
      "Log the failure against the subsystem it belongs to, the day it happens.",
      "Score occurrence, severity, and detection from the real event — RPN stays blank until you do.",
      "Work the highest RPN items first.",
      "Close them out and check Readiness before you travel.",
    ],
    tips: ["FMEA is for failures that already happened; use the Risk register for what might."],
    related: [
      { label: "Blueprint", href: "/robot" },
      { label: "Readiness", href: "/readiness-score" },
      { label: "Failure patterns", href: "/failure-patterns" },
    ],
  },
  {
    id: "build.robot",
    hub: "build",
    tab: "robot",
    title: "Robot blueprint",
    what: "The digital twin read: weakest subsystems with their blockers, missing CAD / code / strategy links, and what to close before the next event.",
    why: "It shows where the robot is actually thin rather than where the loudest subteam says it is.",
    when: "Build season weekly, and hard in the week before an event.",
    moments: ["build", "pre-comp"],
    how: [
      "Define subsystems and their specs so the twin has something to read.",
      "Link CAD, code, and strategy to each subsystem.",
      "Work the flagged blockers and missing links.",
      "Re-read it before travel alongside Readiness and Inspection.",
    ],
    related: [
      { label: "Subsystem specs", href: "/subsystems" },
      { label: "Readiness", href: "/readiness-score" },
      { label: "Bring-up", href: "/bringup" },
    ],
  },
  {
    id: "build.subsystems",
    hub: "build",
    tab: "subsystems",
    title: "Subsystem specs",
    what: "The season's subsystem list — category, motor type and count, gear reduction, and wheel diameter, with free speed computed from what you entered.",
    why: "It is the shared spec sheet the blueprint, readiness index, and weight and power budgets all read from, so one edit updates every downstream check.",
    when: "Kickoff week as the architecture settles, then whenever a subsystem changes.",
    moments: ["kickoff", "build"],
    how: [
      "Add each subsystem with its category and the motor you actually chose.",
      "Enter motor count, gear reduction, and wheel diameter to get free speed.",
      "Revise the entry whenever the mechanism changes rather than starting a new one.",
    ],
    tips: ["Free speed is computed only when the inputs are present — a blank means missing spec, not zero."],
    related: [
      { label: "Blueprint", href: "/robot" },
      { label: "Gearbox calculator", href: "/gearbox" },
      { label: "Weight budget", href: "/weight-budget" },
    ],
  },
  {
    id: "build.gearbox",
    hub: "build",
    tab: "gearbox",
    title: "Gearbox calculator",
    what: "Saved gearboxes per subsystem: driving/driven teeth per stage, compound reduction, and output RPM from the motor's free speed.",
    why: "It keeps the ratio the team agreed on written down and named, instead of on a whiteboard that gets erased.",
    when: "Kickoff week and early build, while ratios are still being chosen.",
    moments: ["kickoff", "build"],
    how: [
      "Name the gearbox and the subsystem it drives.",
      "Add a stage per gear pair with driving and driven tooth counts.",
      "Enter the motor free RPM to get output RPM alongside the reduction.",
      "Save it so the ratio survives the meeting it was decided in.",
    ],
    tips: ["Output RPM stays blank without a motor free speed — it is never guessed for you."],
    related: [
      { label: "Subsystem specs", href: "/subsystems" },
      { label: "Shooter table", href: "/shooter-table" },
      { label: "Blueprint", href: "/robot" },
    ],
  },
  {
    id: "build.weight-budget",
    hub: "build",
    tab: "weight-budget",
    title: "Weight budget",
    what: "Every logged component with weight, quantity, and subsystem, totalled against the weight limit you set, with a per-subsystem breakdown.",
    why: "Teams find out they are overweight at inspection; this finds it while there is still time to cut something.",
    when: "Build season, from the first heavy assembly through the week before an event.",
    moments: ["build", "pre-comp"],
    how: [
      "Set the weight limit for this season's rules.",
      "Log components with real weights and quantities as they are made or bought.",
      "Watch the per-subsystem breakdown for where the mass actually sits.",
      "Re-check the total before weigh-in.",
    ],
    tips: [
      "Weigh parts rather than estimating — the total is only as honest as the entries.",
      "Confirm the limit against the current game manual; it is your number, not a fetched rule.",
    ],
    related: [
      { label: "Weigh-in", href: "/robot-weigh-in" },
      { label: "Power budget", href: "/power-budget" },
      { label: "Readiness", href: "/readiness-score" },
    ],
  },
  {
    id: "build.bringup",
    hub: "build",
    tab: "bringup",
    title: "Bring-up",
    what: "The phased first-power-on checklist — mechanical through software — with pass / fail / N-A and a note per item, plus your own added items.",
    why: "It turns first power-on from a crowd around the robot into an ordered check nobody skips.",
    when: "The first time the robot is powered, and again after any major rebuild.",
    moments: ["build", "pre-comp"],
    how: [
      "Work the phases in order rather than jumping to driving it.",
      "Mark each item pass, fail, or N/A and write the note while you remember it.",
      "Add items for anything unique to your robot.",
      "Clear the failures before the checklist counts as done.",
    ],
    tips: ["A failed item feeds the readiness index — leaving it 'pending' hides a real problem."],
    related: [
      { label: "Readiness", href: "/readiness-score" },
      { label: "Wiring check", href: "/wiring-diagnoser" },
      { label: "Blueprint", href: "/robot" },
    ],
  },
  {
    id: "build.readiness-score",
    hub: "build",
    tab: "readiness-score",
    title: "Readiness",
    what: "One grounded ship-readiness index over subsystem wiring and code state, weight and power headroom, the bring-up checklist, and open FMEA.",
    why: "It answers \"are we ready to put this in a trailer\" with the same evidence every time, not a mentor's mood.",
    when: "The week before each event.",
    moments: ["pre-comp"],
    how: [
      "Complete the bring-up checklist and verify wiring.",
      "Deploy and test the code you intend to compete with.",
      "Close open FMEA items and any budget overrun on record.",
      "Read the index — it is green only when all of the above is true.",
    ],
    tips: ["A blank index means the inputs do not exist yet, not that you are ready."],
    related: [
      { label: "Inspection", href: "/inspection-copilot" },
      { label: "FMEA", href: "/fmea" },
      { label: "Bring-up", href: "/bringup" },
    ],
  },
  {
    id: "build.inspection-copilot",
    hub: "build",
    tab: "inspection-copilot",
    title: "Inspection",
    what: "Compares declared weight, frame and bumper, and wiring limits against your measured robot values before you travel.",
    why: "Finding a legality problem in your shop costs an evening; finding it at inspection costs qualification matches.",
    when: "The week before each event, after weigh-in.",
    moments: ["pre-comp"],
    how: [
      "Weigh and measure the robot and record the real values.",
      "Run the comparison against declared limits.",
      "Fix anything flagged, then re-measure — nothing here is estimated for you.",
      "Cross-check batteries, FMEA, and subsystems before you pack.",
    ],
    related: [
      { label: "Weigh-in", href: "/robot-weigh-in" },
      { label: "Weight budget", href: "/weight-budget" },
      { label: "Readiness", href: "/readiness-score" },
    ],
  },

  // ------------------------------------------------------------------------ AI
  {
    id: "ai.chat",
    hub: "ai",
    tab: "chat",
    title: "AI chat",
    what: "Your team's AI chat channels with team memory, routed through your configured model and metered against your budget.",
    why: "It answers questions with this team's context attached instead of generic advice from a public chatbot.",
    when: "All season, whenever a question needs your own data in the answer.",
    moments: ["preseason", "kickoff", "build", "pre-comp", "comp-day", "after"],
    how: [
      "Open a team.",
      "Configure a model or bring your own key under Controls.",
      "Ask, and check the cited context on anything you will act on.",
    ],
    tips: ["Every call is metered against the org budget before it runs — there is no silent overage."],
    related: [
      { label: "Controls", href: "/team/budgets" },
      { label: "Memory", href: "/ai?tab=memory" },
      { label: "API keys", href: "/team/ai-keys" },
    ],
  },
  {
    id: "ai.writer",
    hub: "ai",
    tab: "writer",
    title: "Writer",
    what: "Metered drafting for grant answers, award essays, and sponsor narratives, working from prompts and the facts you have logged.",
    why: "It gets a first draft on the page without inventing a metric you would then have to defend to a judge or a funder.",
    when: "Build season and the offseason, on grant and award deadlines.",
    moments: ["build", "pre-comp", "after"],
    how: [
      "Configure an AI provider key first — drafts are blocked without one.",
      "Pick the prompt or paste the funder's question.",
      "Generate a draft, then replace every number with one you can source.",
      "Save it back to the grant or award it belongs to.",
    ],
    tips: ["Treat generated figures as placeholders; the logged impact and award records are the real source."],
    related: [
      { label: "Grants", href: "/team/grants" },
      { label: "Awards", href: "/team/awards" },
      { label: "API keys", href: "/team/ai-keys" },
    ],
  },
  {
    id: "ai.agent",
    hub: "ai",
    tab: "agent",
    title: "Agent",
    what: "The autonomous agent workbench — tool setup, runs, and a per-run \"why the agent did this\" trail.",
    why: "An agent you cannot audit is not usable on team data; the run detail shows each step and where a reason was recorded or missing.",
    when: "Build season, for repetitive multi-step work you would otherwise do by hand.",
    moments: ["build", "pre-comp"],
    how: [
      "Set up the tools the agent is allowed to use.",
      "Start a run and watch it in Past runs.",
      "Open Run detail and read the why-panel before trusting the output.",
    ],
    tips: ["A missing reason is shown as missing rather than filled in — treat those steps as unverified."],
    related: [
      { label: "Controls", href: "/team/budgets" },
      { label: "Governance", href: "/ai?tab=governance" },
      { label: "Past runs", href: "/team/ai-runs" },
    ],
  },
  {
    id: "ai.budgets",
    hub: "ai",
    tab: "budgets",
    title: "AI controls",
    what: "Hard spend and token limits checked before every metered AI call, plus memory, governance, keys, and usage underneath.",
    why: "It is what stops a season's AI budget disappearing into one enthusiastic afternoon.",
    when: "Preseason to set the caps, then whenever usage moves.",
    moments: ["preseason", "kickoff", "build"],
    how: [
      "Set the org spend and token caps — they are enforced before each call, not after.",
      "Add your own provider key under API keys if you would rather bring your own.",
      "Set the redaction and consent policy under Governance.",
      "Watch Usage; the included allowance hard-stops unless you buy credits or enable pay-as-you-go.",
    ],
    tips: ["Open a team first or the page has nothing to write to."],
    related: [
      { label: "API keys", href: "/team/ai-keys" },
      { label: "Governance", href: "/ai?tab=governance" },
      { label: "Usage", href: "/team/usage" },
    ],
  },
  {
    id: "ai.ai-bridge",
    hub: "ai",
    tab: "ai-bridge",
    title: "Subscription bridge",
    what: "A member's Claude Pro/Max or ChatGPT subscription, running on their always-on computer, answering the team's AI at $0 API cost — chat-class by default, everything if they opt in.",
    why: "A mentor already paying for Claude can cover the whole team's chat without the team buying API usage.",
    when: "Preseason to pair; it serves the team whenever the machine is online.",
    moments: ["preseason", "build", "pre-comp"],
    how: [
      "On the always-on machine, sign in the Claude Code CLI (verified path; Codex is experimental) and run the bridge's setup to get an 8-character code.",
      "Approve the code at /team/ai-bridge — pairing is the subscriber's own consent.",
      "Pick the device's coverage: interactive chat only (default), or Everything to run all of Vantage's AI on the subscription.",
      "Revoke the device on the same page to stop routing immediately.",
    ],
    tips: [
      "It is that person's plan: rate limits apply, the provider's message is shown verbatim, and turns fall back to the team's own keys automatically.",
      "A device counts as online while its heartbeat is under 3 minutes old.",
    ],
    related: [
      { label: "API keys", href: "/team/ai-keys" },
      { label: "AI controls", href: "/team/budgets" },
      { label: "Usage", href: "/team/usage" },
    ],
  },
  {
    id: "ai.decisions",
    hub: "ai",
    tab: "decisions",
    title: "Notes & decisions",
    what: "The decision log — context, the options considered, what you chose, and why.",
    why: "Next year's team inherits the choice; without the why they redo the same argument from scratch.",
    when: "All season, written the day the call is made.",
    moments: ["kickoff", "build", "pre-comp", "after"],
    how: [
      "Record the decision with its context and the options you weighed.",
      "Say what you chose and why, including what you gave up.",
      "Search past decisions before re-opening an old argument.",
    ],
    tips: ["Entries stay empty until you write them — the log does not fill in history."],
    related: [
      { label: "Search decisions", href: "/decision-search" },
      { label: "Playbook", href: "/team/knowledge" },
      { label: "Season report", href: "/season-report" },
    ],
  },
  {
    id: "ai.season-report",
    hub: "ai",
    tab: "season-report",
    title: "Season report",
    what: "A state-of-the-team retrospective generated only from the build reliability, results, budget, and outreach notes you logged.",
    why: "It is the document you hand sponsors, the school, and next year's leads instead of writing one from memory in August.",
    when: "After the season, once the last event is done.",
    moments: ["after"],
    how: [
      "Keep logging reliability, results, budget, and outreach through the season.",
      "Generate the report once the season closes.",
      "Check every claim against its source before you send it.",
    ],
    tips: ["Thin sections mean thin logging — the report will not fill gaps with plausible numbers."],
    related: [
      { label: "Retro", href: "/retro" },
      { label: "Impact log", href: "/impact" },
      { label: "Notes & decisions", href: "/decisions" },
    ],
  },

  // ------------------------------------------------------------------- Media
  {
    id: "media.calendar",
    hub: "media",
    tab: "calendar",
    title: "Media calendar",
    what: "Scheduled content items with a title and due time for the team's posts.",
    why: "Sponsors were promised posts; a calendar is how those actually happen during the busiest weeks.",
    when: "Build season and event weeks.",
    moments: ["preseason", "build", "pre-comp", "comp-day"],
    how: [
      "Add a content item with a title and due time.",
      "Draft the caption under Drafts before the due time.",
      "Set a reminder so it does not get lost on an event day.",
    ],
    related: [
      { label: "Drafts", href: "/media?tab=drafts" },
      { label: "Reminders", href: "/media?tab=reminders" },
    ],
  },
  {
    id: "media.drafts",
    hub: "media",
    tab: "drafts",
    title: "Media drafts",
    what: "Work-in-progress titles and captions, with a starter caption computed from your own title and notes.",
    why: "It keeps posts written by the team ahead of time rather than typed one-handed in the stands.",
    when: "Build season and the days before an event.",
    moments: ["build", "pre-comp", "comp-day"],
    how: [
      "Save a draft against a scheduled item.",
      "Generate a starter caption from your title and notes, then rewrite it in the team's voice.",
      "Publish from your own social accounts — Vantage holds the draft, not the posting.",
    ],
    tips: ["Titles and captions stay blank until you write them; nothing is added for you."],
    related: [
      { label: "Media calendar", href: "/media?tab=calendar" },
      { label: "Media kit", href: "/media-kit" },
    ],
  },
  {
    id: "media.reminders",
    hub: "media",
    tab: "reminders",
    title: "Media reminders",
    what: "Reminders attached to scheduled or drafted content, driven by the remind_at you set.",
    why: "Event weekends are exactly when content slips, and a reminder is cheaper than an apology to a sponsor.",
    when: "Event weeks and competition day.",
    moments: ["pre-comp", "comp-day"],
    how: [
      "Set remind_at when you schedule or draft an item.",
      "Check reminders the morning of an event day.",
    ],
    tips: ["Alert counts stay at zero until real reminders exist."],
    related: [{ label: "Media calendar", href: "/media?tab=calendar" }],
  },
  {
    id: "media.kit",
    hub: "media",
    tab: "kit",
    title: "Media kit",
    what: "Media kit readiness and the asset library of real logo, photo, and press URLs you add.",
    why: "When a reporter or sponsor asks for assets you have an hour, not a week, to send something usable.",
    when: "Preseason to assemble; event weeks to use.",
    moments: ["preseason", "build", "pre-comp"],
    how: [
      "Add real asset URLs — the library is empty until you do.",
      "Fill the readiness items so the kit is complete before you need it.",
      "Share the kit link with press and sponsors.",
    ],
    related: [
      { label: "Sponsorship packages", href: "/sponsorship" },
      { label: "Media drafts", href: "/media?tab=drafts" },
    ],
  },
  {
    id: "media.media-library",
    hub: "media",
    tab: "media-library",
    title: "Media library",
    what: "The team's photo and video shelf: albums, client-generated thumbnails, and honest size caps (8 MB photos after downscale, 4 MiB hosted-cloud videos; 100 MB only on a paired storage node).",
    why: "Build-season photos and event clips end up findable for the media kit, awards, and sponsors instead of scattered across phones.",
    when: "All season — upload the week the photos are taken.",
    moments: ["preseason", "build", "pre-comp", "comp-day", "after"],
    how: [
      "Upload photos (JPEG/PNG/WebP) and videos (MP4/WebM) — photos are downscaled in the browser first.",
      "Group items into albums and tag the event or subteam so filters work later.",
      "Point larger videos at a paired storage node or YouTube via the Match Video Index.",
    ],
    tips: ["Duplicates are caught by content hash; an over-cap upload is refused with the real size and cap named."],
    related: [
      { label: "Media kit", href: "/media-kit" },
      { label: "Storage node", href: "/team/storage" },
      { label: "Match video", href: "/match-video-index" },
    ],
  },
  {
    id: "media.impact",
    hub: "media",
    tab: "impact",
    title: "Media impact",
    what: "The media-category slice of your logged impact activities.",
    why: "It connects the content calendar back to the outreach evidence used for awards and sponsor reporting.",
    when: "All season, and again when writing award or sponsor reports.",
    moments: ["build", "pre-comp", "after"],
    how: [
      "Log media activities in the Impact log with the media category.",
      "Review the slice here when reporting reach.",
    ],
    tips: ["Hours shown are logged hours only — never estimated reach."],
    related: [
      { label: "Impact log", href: "/impact" },
      { label: "Outreach & evidence", href: "/business?tab=evidence" },
    ],
  },
];

const BY_ID = new Map<string, SectionHelpEntry>(SECTION_HELP.map((entry) => [entry.id, entry]));
const BY_HUB_TAB = new Map<string, SectionHelpEntry>(
  SECTION_HELP.map((entry) => [`${entry.hub}.${entry.tab}`, entry]),
);

export function sectionHelpById(id: string): SectionHelpEntry | undefined {
  return BY_ID.get(id);
}

/** The entry for a hub tab, or undefined when that tab has no help yet. */
export function sectionHelpFor(
  hub: SectionHelpHubId | string | null | undefined,
  tab: string | null | undefined,
): SectionHelpEntry | undefined {
  if (!hub || !tab) return undefined;
  return BY_HUB_TAB.get(`${hub}.${tab}`);
}

export function sectionHelpForHub(hub: SectionHelpHubId): SectionHelpEntry[] {
  return SECTION_HELP.filter((entry) => entry.hub === hub);
}

export function sectionHelpForMoment(moment: SeasonMoment): SectionHelpEntry[] {
  return SECTION_HELP.filter((entry) => entry.moments.includes(moment));
}

export function seasonMomentLabel(moment: SeasonMoment): string {
  return SEASON_MOMENTS.find((entry) => entry.id === moment)?.label ?? moment;
}
