import type { MetadataRoute } from "next";
import { SITE_URL as canonicalUrl } from "../lib/site";

/** Authenticated product + auth surfaces — keep out of public indexes. */
const PRIVATE_DISALLOW = [
  "/api/",
  "/admin",
  "/onboarding",
  "/invite",
  "/sign-in",
  "/signin",
  "/account",
  "/settings",
  "/security",
  "/dashboard",
  "/workspace",
  "/command",
  "/pit",
  "/scouting",
  "/intel",
  "/dossier",
  "/strategy",
  "/chemistry",
  "/cad",
  "/code",
  "/chat",
  "/messages",
  "/exports",
  "/showcase",
  "/display",
  "/team",
  "/inventory",
  "/business",
  "/costs",
  "/impact",
  "/batteries",
  "/notebook",
  "/safety",
  "/hours",
  "/calendar",
  "/team/calendar",
  "/assets",
  "/alumni",
  "/briefing",
  "/consent",
  "/event-readiness",
  "/fundraisers",
  "/inspection",
  "/kickoff",
  "/match-debrief",
  "/media",
  "/meetings",
  "/mock-judging",
  "/packing",
  "/parts-relay",
  "/practice",
  "/recognition",
  "/recruitment",
  "/repairs",
  "/retro",
  "/schedule",
  "/season-rollover",
  "/training",
  "/travel",
  "/video",
  "/volunteers",
  "/whiteboard",
  "/knowledge",
  "/leadership",
  "/config",
  "/changes",
];

export default function robots(): MetadataRoute.Robots {
  return {
    // Public marketing/legal pages are crawlable (including AI crawlers, which we
    // intentionally allow for GEO); authenticated product + auth routes are excluded.
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: PRIVATE_DISALLOW,
    },
    sitemap: `${canonicalUrl}/sitemap.xml`,
  };
}
