import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { featureCacheKey } from "./feature-cache";
import {
  OFFLINE_SHELL_ROUTES,
  navigationFallbackPath,
  offlineCapableLabel,
  pathnameIsOfflineShell,
  isRscRequest,
} from "./shell-routes";

const WEB_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

describe("offline shell routes", () => {
  it("matches allowlisted product paths and nested scouting", () => {
    expect(pathnameIsOfflineShell("/scouting")).toBe(true);
    expect(pathnameIsOfflineShell("/scouting/lineup")).toBe(true);
    expect(pathnameIsOfflineShell("/calendar")).toBe(true);
    expect(pathnameIsOfflineShell("/team/calendar")).toBe(true);
    expect(pathnameIsOfflineShell("/todos")).toBe(true);
    expect(pathnameIsOfflineShell("/tasks")).toBe(true);
    expect(pathnameIsOfflineShell("/logistics")).toBe(true);
    expect(pathnameIsOfflineShell("/schedule")).toBe(true);
    expect(pathnameIsOfflineShell("/offline-shell")).toBe(true);
    expect(pathnameIsOfflineShell("/offline")).toBe(true);
    expect(pathnameIsOfflineShell("/competition")).toBe(true);
    expect(pathnameIsOfflineShell("/command")).toBe(true);
    expect(pathnameIsOfflineShell("/team")).toBe(true);
    expect(pathnameIsOfflineShell("/dashboard")).toBe(true);
    expect(pathnameIsOfflineShell("/build")).toBe(true);
    expect(pathnameIsOfflineShell("/files")).toBe(true);
    expect(pathnameIsOfflineShell("/docs")).toBe(true);
    expect(pathnameIsOfflineShell("/strategy")).toBe(true);
    expect(pathnameIsOfflineShell("/hours")).toBe(true);
    expect(pathnameIsOfflineShell("/hours/kiosk")).toBe(true);
    expect(pathnameIsOfflineShell("/messages")).toBe(true);
    expect(pathnameIsOfflineShell("/match-checklist")).toBe(true);
    expect(pathnameIsOfflineShell("/match-notes-timeline")).toBe(true);
    expect(pathnameIsOfflineShell("/pit")).toBe(true);
    expect(pathnameIsOfflineShell("/video-analysis")).toBe(true);
    expect(pathnameIsOfflineShell("/assembly-manual")).toBe(true);
    expect(pathnameIsOfflineShell("/packing")).toBe(true);
    expect(pathnameIsOfflineShell("/batteries")).toBe(true);
    expect(pathnameIsOfflineShell("/my-day")).toBe(true);
    expect(pathnameIsOfflineShell("/chemistry")).toBe(true);
    expect(pathnameIsOfflineShell("/pick-clock")).toBe(true);
    expect(pathnameIsOfflineShell("/alliance-selection-desk")).toBe(true);
    expect(pathnameIsOfflineShell("/print-farm")).toBe(true);
    expect(pathnameIsOfflineShell("/inventory")).toBe(true);
    expect(pathnameIsOfflineShell("/defense-planner")).toBe(true);
    expect(pathnameIsOfflineShell("/picklist-collab")).toBe(true);
    expect(pathnameIsOfflineShell("/dossier")).toBe(true);
    expect(pathnameIsOfflineShell("/pit-repair-triage")).toBe(true);
    expect(pathnameIsOfflineShell("/event-day-plan")).toBe(true);
    expect(pathnameIsOfflineShell("/field-reset-timer")).toBe(true);
    expect(pathnameIsOfflineShell("/drive-team-signals")).toBe(true);
    expect(pathnameIsOfflineShell("/robot-weigh-in")).toBe(true);
    expect(pathnameIsOfflineShell("/match-delta-watcher")).toBe(true);
    expect(pathnameIsOfflineShell("/match-video-index")).toBe(true);
    expect(pathnameIsOfflineShell("/strategy/draft")).toBe(true);
    expect(pathnameIsOfflineShell("/scouting/lineup")).toBe(true);
    expect(pathnameIsOfflineShell("/match-strategy-cards")).toBe(true);
    expect(pathnameIsOfflineShell("/match-copilot")).toBe(true);
    expect(pathnameIsOfflineShell("/event-readiness")).toBe(true);
    expect(pathnameIsOfflineShell("/video")).toBe(true);
    expect(pathnameIsOfflineShell("/inspection-copilot")).toBe(true);
    expect(pathnameIsOfflineShell("/inspection")).toBe(true);
    expect(pathnameIsOfflineShell("/fmea")).toBe(true);
    expect(pathnameIsOfflineShell("/match-sim")).toBe(true);
    expect(pathnameIsOfflineShell("/pit-map-planner")).toBe(true);
    expect(pathnameIsOfflineShell("/pairwise")).toBe(true);
    expect(pathnameIsOfflineShell("/team-tags")).toBe(true);
    expect(pathnameIsOfflineShell("/shift-balancer")).toBe(true);
    expect(pathnameIsOfflineShell("/counter-book")).toBe(true);
    expect(pathnameIsOfflineShell("/intel")).toBe(true);
    expect(pathnameIsOfflineShell("/overnight-intel")).toBe(true);
    expect(pathnameIsOfflineShell("/alliance-partner-brief")).toBe(true);
    expect(pathnameIsOfflineShell("/picklist-justifier")).toBe(true);
    expect(pathnameIsOfflineShell("/opponent-watchlist")).toBe(true);
    expect(pathnameIsOfflineShell("/alliance-sim")).toBe(true);
    expect(pathnameIsOfflineShell("/briefing")).toBe(true);
    expect(pathnameIsOfflineShell("/award-tracker")).toBe(true);
    expect(pathnameIsOfflineShell("/epa-trend-alerts")).toBe(true);
    expect(pathnameIsOfflineShell("/rankings")).toBe(true);
    expect(pathnameIsOfflineShell("/grant-report")).toBe(true);
    expect(pathnameIsOfflineShell("/media-kit")).toBe(true);
    expect(pathnameIsOfflineShell("/sponsor-wall")).toBe(true);
    expect(pathnameIsOfflineShell("/sponsor-suite")).toBe(true);
    expect(pathnameIsOfflineShell("/outreach-calendar")).toBe(true);
    expect(pathnameIsOfflineShell("/visit-invites")).toBe(true);
    expect(pathnameIsOfflineShell("/judge-sim")).toBe(true);
    expect(pathnameIsOfflineShell("/impact-essay")).toBe(true);
    expect(pathnameIsOfflineShell("/battery-rotation")).toBe(true);
    expect(pathnameIsOfflineShell("/vendors")).toBe(true);
    expect(pathnameIsOfflineShell("/season-report")).toBe(true);
    expect(pathnameIsOfflineShell("/media")).toBe(true);
    expect(pathnameIsOfflineShell("/battery-health-forecast")).toBe(true);
    expect(pathnameIsOfflineShell("/vendor-lead-times")).toBe(true);
    expect(pathnameIsOfflineShell("/bin-shelf-locator")).toBe(true);
    expect(pathnameIsOfflineShell("/build-burndown")).toBe(true);
    expect(pathnameIsOfflineShell("/cad-change-radar")).toBe(true);
    expect(pathnameIsOfflineShell("/code-deploy-log")).toBe(true);
    expect(pathnameIsOfflineShell("/control-map")).toBe(true);
    expect(pathnameIsOfflineShell("/cross-team-scrim")).toBe(true);
    expect(pathnameIsOfflineShell("/decision-search")).toBe(true);
    expect(pathnameIsOfflineShell("/decisions")).toBe(true);
    expect(pathnameIsOfflineShell("/failure-patterns")).toBe(true);
    expect(pathnameIsOfflineShell("/grant-eligibility-matcher")).toBe(true);
    expect(pathnameIsOfflineShell("/hours-self-view")).toBe(true);
    expect(pathnameIsOfflineShell("/knowledge-gap")).toBe(true);
    expect(pathnameIsOfflineShell("/matching-gift-finder")).toBe(true);
    expect(pathnameIsOfflineShell("/onboarding-buddy")).toBe(true);
    expect(pathnameIsOfflineShell("/risk-burndown")).toBe(true);
    expect(pathnameIsOfflineShell("/spare-robot-kit")).toBe(true);
    expect(pathnameIsOfflineShell("/sponsor-renewal-roi")).toBe(true);
    expect(pathnameIsOfflineShell("/team-health-dashboard")).toBe(true);
    expect(pathnameIsOfflineShell("/spare-forecast")).toBe(true);
    expect(pathnameIsOfflineShell("/sketch-to-brief")).toBe(true);
    expect(pathnameIsOfflineShell("/scout-assisted-count")).toBe(true);
    expect(pathnameIsOfflineShell("/scout-coverage-live")).toBe(true);
    expect(pathnameIsOfflineShell("/scout-field-budget")).toBe(true);
    expect(pathnameIsOfflineShell("/scouting-heat-signals")).toBe(true);
    expect(pathnameIsOfflineShell("/scout-data-impact")).toBe(true);
    expect(pathnameIsOfflineShell("/scout-disagreements")).toBe(true);
    expect(pathnameIsOfflineShell("/scout-accuracy")).toBe(true);
    expect(pathnameIsOfflineShell("/scout-crossval")).toBe(true);
    expect(pathnameIsOfflineShell("/rule-impact")).toBe(true);
    expect(pathnameIsOfflineShell("/season-planning-workspace")).toBe(true);
    expect(pathnameIsOfflineShell("/retro")).toBe(true);
    expect(pathnameIsOfflineShell("/team/data")).toBe(true);
    expect(pathnameIsOfflineShell("/tuning-autopilot")).toBe(true);
    expect(pathnameIsOfflineShell("/fundraisers")).toBe(true);
    expect(pathnameIsOfflineShell("/impact")).toBe(true);
    expect(pathnameIsOfflineShell("/orders")).toBe(true);
    expect(pathnameIsOfflineShell("/business")).toBe(true);
    expect(pathnameIsOfflineShell("/team/grants")).toBe(true);
    expect(pathnameIsOfflineShell("/practice")).toBe(true);
    expect(pathnameIsOfflineShell("/manufacturing")).toBe(true);
    expect(pathnameIsOfflineShell("/attendance")).toBe(true);
    expect(pathnameIsOfflineShell("/kickoff")).toBe(true);
    expect(pathnameIsOfflineShell("/match-debrief")).toBe(true);
    expect(pathnameIsOfflineShell("/ranking-projection")).toBe(true);
    expect(pathnameIsOfflineShell("/whiteboard")).toBe(true);
    expect(pathnameIsOfflineShell("/robot")).toBe(true);
    expect(pathnameIsOfflineShell("/my-kit")).toBe(true);
    expect(pathnameIsOfflineShell("/part-requests")).toBe(true);
    expect(pathnameIsOfflineShell("/recognition")).toBe(true);
    expect(pathnameIsOfflineShell("/subteams")).toBe(true);
    expect(pathnameIsOfflineShell("/budget")).toBe(true);
    expect(pathnameIsOfflineShell("/sponsorship")).toBe(true);
    expect(pathnameIsOfflineShell("/safety")).toBe(true);
    expect(pathnameIsOfflineShell("/writer")).toBe(true);
    expect(pathnameIsOfflineShell("/learning")).toBe(true);
    expect(pathnameIsOfflineShell("/training")).toBe(true);
    expect(pathnameIsOfflineShell("/tool-checkout")).toBe(true);
    expect(pathnameIsOfflineShell("/goals")).toBe(true);
    expect(pathnameIsOfflineShell("/cad-vault")).toBe(true);
    expect(pathnameIsOfflineShell("/cad-learn")).toBe(true);
    expect(pathnameIsOfflineShell("/cad-review-queue")).toBe(true);
    expect(pathnameIsOfflineShell("/reimbursements")).toBe(true);
    expect(pathnameIsOfflineShell("/costs")).toBe(true);
    expect(pathnameIsOfflineShell("/duties")).toBe(true);
    expect(pathnameIsOfflineShell("/announcements")).toBe(true);
    expect(pathnameIsOfflineShell("/risks")).toBe(true);
    expect(pathnameIsOfflineShell("/subsystem-signoff")).toBe(true);
    expect(pathnameIsOfflineShell("/prototype-tracker")).toBe(true);
    expect(pathnameIsOfflineShell("/equipment-maintenance")).toBe(true);
    expect(pathnameIsOfflineShell("/notifications")).toBe(true);
    expect(pathnameIsOfflineShell("/forms")).toBe(true);
    expect(pathnameIsOfflineShell("/incidents")).toBe(true);
    expect(pathnameIsOfflineShell("/roles")).toBe(true);
    expect(pathnameIsOfflineShell("/parts-catalog")).toBe(true);
    expect(pathnameIsOfflineShell("/parts-relay")).toBe(true);
    expect(pathnameIsOfflineShell("/cad/setup")).toBe(true);
    expect(pathnameIsOfflineShell("/cad/pair")).toBe(true);
    expect(pathnameIsOfflineShell("/cad/connections")).toBe(true);
    expect(pathnameIsOfflineShell("/presence")).toBe(true);
    expect(pathnameIsOfflineShell("/troubleshoot")).toBe(true);
    expect(pathnameIsOfflineShell("/media-library")).toBe(true);
    expect(pathnameIsOfflineShell("/connectors")).toBe(true);
    expect(pathnameIsOfflineShell("/support")).toBe(true);
    expect(pathnameIsOfflineShell("/team/discord")).toBe(true);
    expect(pathnameIsOfflineShell("/hours/kiosk")).toBe(true);
    expect(pathnameIsOfflineShell("/scouting/forms")).toBe(true);
    expect(pathnameIsOfflineShell("/bus-factor")).toBe(true);
    expect(pathnameIsOfflineShell("/parents")).toBe(true);
    expect(pathnameIsOfflineShell("/power-budget")).toBe(true);
    expect(pathnameIsOfflineShell("/bringup")).toBe(true);
    expect(pathnameIsOfflineShell("/auton-path-library")).toBe(true);
    expect(pathnameIsOfflineShell("/checklist-library")).toBe(true);
    expect(pathnameIsOfflineShell("/scout-training-mode")).toBe(true);
    expect(pathnameIsOfflineShell("/scout-p2p-relay")).toBe(true);
    expect(pathnameIsOfflineShell("/alumni-network")).toBe(true);
    expect(pathnameIsOfflineShell("/mock-judging")).toBe(true);
    expect(pathnameIsOfflineShell("/knowledge-drafts")).toBe(true);
    expect(pathnameIsOfflineShell("/team/knowledge")).toBe(true);
    expect(pathnameIsOfflineShell("/start")).toBe(true);
    expect(pathnameIsOfflineShell("/showcase")).toBe(true);
    expect(pathnameIsOfflineShell("/cross-domain-alerts")).toBe(true);
    expect(pathnameIsOfflineShell("/whats-new")).toBe(true);
    expect(pathnameIsOfflineShell("/search")).toBe(true);
    expect(pathnameIsOfflineShell("/migrate")).toBe(true);
    expect(pathnameIsOfflineShell("/team/admin")).toBe(true);
    expect(pathnameIsOfflineShell("/team/security")).toBe(true);
    expect(pathnameIsOfflineShell("/account")).toBe(true);
    expect(pathnameIsOfflineShell("/api/todos")).toBe(false);
  });

  it("labels offline-capable surfaces for banners", () => {
    expect(offlineCapableLabel("/scouting?orgId=x")).toBe("Scouting");
    expect(offlineCapableLabel("/team/calendar")).toBe("Calendar");
    expect(offlineCapableLabel("/calendar")).toBe("Calendar");
    expect(offlineCapableLabel("/todos")).toBe("Todos");
    expect(offlineCapableLabel("/logistics")).toBe("Logistics");
    expect(offlineCapableLabel("/dashboard")).toBe("Home");
    expect(offlineCapableLabel("/files")).toBe("Files");
    expect(offlineCapableLabel("/hours")).toBe("Hours");
    expect(offlineCapableLabel("/messages")).toBe("Chat");
    expect(offlineCapableLabel("/assembly-manual")).toBe("Assembly manual");
    expect(offlineCapableLabel("/packing")).toBe("Packing");
    expect(offlineCapableLabel("/batteries")).toBe("Batteries");
    expect(offlineCapableLabel("/pit")).toBe("Pit");
    expect(offlineCapableLabel("/my-day")).toBe("My Day");
    expect(offlineCapableLabel("/schedule")).toBe("Schedule");
    expect(offlineCapableLabel("/command")).toBe("Event Day");
    expect(offlineCapableLabel("/chemistry")).toBe("Chemistry");
    expect(offlineCapableLabel("/pick-clock")).toBe("Pick clock");
    expect(offlineCapableLabel("/alliance-selection-desk")).toBe("Alliance selection desk");
    expect(offlineCapableLabel("/print-farm")).toBe("Print farm");
    expect(offlineCapableLabel("/inventory")).toBe("Inventory");
    expect(offlineCapableLabel("/defense-planner")).toBe("Defense planner");
    expect(offlineCapableLabel("/picklist-collab")).toBe("Collaborative pick list");
    expect(offlineCapableLabel("/dossier")).toBe("Dossier");
    expect(offlineCapableLabel("/pit-repair-triage")).toBe("Pit repair triage");
    expect(offlineCapableLabel("/event-day-plan")).toBe("Event-day plan");
    expect(offlineCapableLabel("/field-reset-timer")).toBe("Field reset timer");
    expect(offlineCapableLabel("/drive-team-signals")).toBe("Drive-team signals");
    expect(offlineCapableLabel("/robot-weigh-in")).toBe("Robot weigh-in");
    expect(offlineCapableLabel("/match-delta-watcher")).toBe("Match-delta watcher");
    expect(offlineCapableLabel("/match-video-index")).toBe("Match video index");
    expect(offlineCapableLabel("/strategy/draft")).toBe("Alliance board");
    expect(offlineCapableLabel("/scouting/lineup")).toBe("Lineup & coverage");
    expect(offlineCapableLabel("/match-strategy-cards")).toBe("Match strategy cards");
    expect(offlineCapableLabel("/match-copilot")).toBe("Briefing");
    expect(offlineCapableLabel("/event-readiness")).toBe("Event readiness");
    expect(offlineCapableLabel("/video-analysis")).toBe("Video");
    expect(offlineCapableLabel("/video")).toBe("Match video");
    expect(offlineCapableLabel("/inspection-copilot")).toBe("Inspection");
    expect(offlineCapableLabel("/inspection")).toBe("Inspection");
    expect(offlineCapableLabel("/fmea")).toBe("Failure log");
    expect(offlineCapableLabel("/match-sim")).toBe("Match sim");
    expect(offlineCapableLabel("/pit-map-planner")).toBe("Pit Map Planner");
    expect(offlineCapableLabel("/pairwise")).toBe("Pairwise ranking");
    expect(offlineCapableLabel("/team-tags")).toBe("Drive-team tags");
    expect(offlineCapableLabel("/shift-balancer")).toBe("Scout shift balancer");
    expect(offlineCapableLabel("/counter-book")).toBe("Counter-book");
    expect(offlineCapableLabel("/intel")).toBe("Research");
    expect(offlineCapableLabel("/overnight-intel")).toBe("Overnight brief");
    expect(offlineCapableLabel("/alliance-partner-brief")).toBe("Alliance-Partner Brief");
    expect(offlineCapableLabel("/picklist-justifier")).toBe("Pick-list Justifier");
    expect(offlineCapableLabel("/opponent-watchlist")).toBe("Opponent Watchlist");
    expect(offlineCapableLabel("/alliance-sim")).toBe("Alliance Sim");
    expect(offlineCapableLabel("/briefing")).toBe("Pre-match briefing");
    expect(offlineCapableLabel("/award-tracker")).toBe("Award Tracker");
    expect(offlineCapableLabel("/epa-trend-alerts")).toBe("Rating alerts");
    expect(offlineCapableLabel("/rankings")).toBe("Rankings");
    expect(offlineCapableLabel("/grant-report")).toBe("Grant Report");
    expect(offlineCapableLabel("/media-kit")).toBe("Media Kit");
    expect(offlineCapableLabel("/sponsor-wall")).toBe("Sponsor Wall");
    expect(offlineCapableLabel("/sponsor-suite")).toBe("Sponsor Suite");
    expect(offlineCapableLabel("/outreach-calendar")).toBe("Outreach Calendar");
    expect(offlineCapableLabel("/visit-invites")).toBe("Visit Invites");
    expect(offlineCapableLabel("/judge-sim")).toBe("Judge-Pitch Simulator");
    expect(offlineCapableLabel("/impact-essay")).toBe("Impact Essay");
    expect(offlineCapableLabel("/impact")).toBe("Community Impact");
    expect(offlineCapableLabel("/fundraisers")).toBe("Fundraisers");
    expect(offlineCapableLabel("/orders")).toBe("Orders");
    expect(offlineCapableLabel("/business")).toBe("Business");
    expect(offlineCapableLabel("/battery-rotation")).toBe("Battery Rotation");
    expect(offlineCapableLabel("/vendors")).toBe("Vendors");
    expect(offlineCapableLabel("/season-report")).toBe("Season Report");
    expect(offlineCapableLabel("/media")).toBe("Media");
    expect(offlineCapableLabel("/media-kit")).toBe("Media Kit");
    expect(offlineCapableLabel("/battery-health-forecast")).toBe("Battery Health Forecast");
    expect(offlineCapableLabel("/vendor-lead-times")).toBe("Vendor Lead Times");
    expect(offlineCapableLabel("/bin-shelf-locator")).toBe("Bin/Shelf Locator");
    expect(offlineCapableLabel("/build-burndown")).toBe("Build Burndown");
    expect(offlineCapableLabel("/build")).toBe("Build");
    expect(offlineCapableLabel("/cad-change-radar")).toBe("CAD Change Radar");
    expect(offlineCapableLabel("/code-deploy-log")).toBe("Code Deploy Log");
    expect(offlineCapableLabel("/control-map")).toBe("Control Map");
    expect(offlineCapableLabel("/cross-team-scrim")).toBe("Cross-Team Scrims");
    expect(offlineCapableLabel("/decision-search")).toBe("Decision Search");
    expect(offlineCapableLabel("/decisions")).toBe("Decision Log");
    expect(offlineCapableLabel("/failure-patterns")).toBe("Repeat Failure Patterns");
    expect(offlineCapableLabel("/hours-self-view")).toBe("My Hours");
    expect(offlineCapableLabel("/hours")).toBe("Hours");
    expect(offlineCapableLabel("/grant-eligibility-matcher")).toBe("Grant Eligibility Matcher");
    expect(offlineCapableLabel("/knowledge-gap")).toBe("Knowledge-gap detective");
    expect(offlineCapableLabel("/matching-gift-finder")).toBe("Matching Gift Finder");
    expect(offlineCapableLabel("/onboarding-buddy")).toBe("Onboarding Buddy");
    expect(offlineCapableLabel("/risk-burndown")).toBe("Risk-Register Burndown");
    expect(offlineCapableLabel("/spare-robot-kit")).toBe("Spare Robot Kit");
    expect(offlineCapableLabel("/spare-forecast")).toBe("Spare Forecast");
    expect(offlineCapableLabel("/sponsor-renewal-roi")).toBe("Sponsor Renewal ROI");
    expect(offlineCapableLabel("/team-health-dashboard")).toBe("Team Health");
    expect(offlineCapableLabel("/sketch-to-brief")).toBe("Sketch-to-Brief");
    expect(offlineCapableLabel("/scout-assisted-count")).toBe("Scout-Assisted Count");
    expect(offlineCapableLabel("/scout-coverage-live")).toBe("Scout Coverage Live");
    expect(offlineCapableLabel("/scout-field-budget")).toBe("Field-Count Budget");
    expect(offlineCapableLabel("/scouting-heat-signals")).toBe("Scouting Heat Signals");
    expect(offlineCapableLabel("/scouting")).toBe("Scouting");
    expect(offlineCapableLabel("/scout-data-impact")).toBe("Scout Data Impact");
    expect(offlineCapableLabel("/scout-disagreements")).toBe("Scout Disagreements");
    expect(offlineCapableLabel("/scout-accuracy")).toBe("Scout Accuracy");
    expect(offlineCapableLabel("/scout-crossval")).toBe("Scout Cross-Validation");
    expect(offlineCapableLabel("/rule-impact")).toBe("Rule Impact Analyzer");
    expect(offlineCapableLabel("/season-planning-workspace")).toBe("Season Planning");
    expect(offlineCapableLabel("/retro")).toBe("Retro");
    expect(offlineCapableLabel("/team/data")).toBe("Team Data");
    expect(offlineCapableLabel("/team/grants")).toBe("Grant writing");
    expect(offlineCapableLabel("/team")).toBe("Team");
    expect(offlineCapableLabel("/team/knowledge")).toBe("Playbook");
    expect(offlineCapableLabel("/tuning-autopilot")).toBe("Tuning advisor");
    expect(offlineCapableLabel("/practice")).toBe("Practice");
    expect(offlineCapableLabel("/manufacturing")).toBe("Manufacturing");
    expect(offlineCapableLabel("/attendance")).toBe("Attendance");
    expect(offlineCapableLabel("/kickoff")).toBe("Kickoff");
    expect(offlineCapableLabel("/match-debrief")).toBe("Match debrief");
    expect(offlineCapableLabel("/ranking-projection")).toBe("Ranking projection");
    expect(offlineCapableLabel("/whiteboard")).toBe("Whiteboard");
    expect(offlineCapableLabel("/robot")).toBe("Robot");
    expect(offlineCapableLabel("/robot-weigh-in")).toBe("Robot weigh-in");
    expect(offlineCapableLabel("/my-kit")).toBe("My Kit");
    expect(offlineCapableLabel("/part-requests")).toBe("Part requests");
    expect(offlineCapableLabel("/recognition")).toBe("Recognition");
    expect(offlineCapableLabel("/subteams")).toBe("Subteam progress");
    expect(offlineCapableLabel("/budget")).toBe("Season budget");
    expect(offlineCapableLabel("/sponsorship")).toBe("Sponsorship");
    expect(offlineCapableLabel("/sponsor-suite")).toBe("Sponsor Suite");
    expect(offlineCapableLabel("/safety")).toBe("Safety");
    expect(offlineCapableLabel("/writer")).toBe("Writer");
    expect(offlineCapableLabel("/learning")).toBe("Learning");
    expect(offlineCapableLabel("/training")).toBe("Training");
    expect(offlineCapableLabel("/tool-checkout")).toBe("Tool checkout");
    expect(offlineCapableLabel("/goals")).toBe("Goals");
    expect(offlineCapableLabel("/cad-vault")).toBe("CAD Vault");
    expect(offlineCapableLabel("/cad-learn")).toBe("CAD Learn");
    expect(offlineCapableLabel("/cad-review-queue")).toBe("CAD Review Queue");
    expect(offlineCapableLabel("/cad-change-radar")).toBe("CAD Change Radar");
    expect(offlineCapableLabel("/reimbursements")).toBe("Reimbursements");
    expect(offlineCapableLabel("/costs")).toBe("Season Costs");
    expect(offlineCapableLabel("/duties")).toBe("Duties");
    expect(offlineCapableLabel("/announcements")).toBe("Announcements");
    expect(offlineCapableLabel("/risks")).toBe("Risk Register");
    expect(offlineCapableLabel("/risk-burndown")).toBe("Risk-Register Burndown");
    expect(offlineCapableLabel("/subsystem-signoff")).toBe("Subsystem Sign-off");
    expect(offlineCapableLabel("/prototype-tracker")).toBe("Prototype-to-Decision Tracker");
    expect(offlineCapableLabel("/equipment-maintenance")).toBe("Equipment Maintenance");
    expect(offlineCapableLabel("/notifications")).toBe("Notifications");
    expect(offlineCapableLabel("/forms")).toBe("Forms");
    expect(offlineCapableLabel("/incidents")).toBe("Safety Incident Log");
    expect(offlineCapableLabel("/roles")).toBe("Season roles");
    expect(offlineCapableLabel("/parts-catalog")).toBe("Parts catalog");
    expect(offlineCapableLabel("/parts-relay")).toBe("Parts Relay");
    expect(offlineCapableLabel("/cad/setup")).toBe("CAD setup");
    expect(offlineCapableLabel("/cad/pair")).toBe("Pair this computer");
    expect(offlineCapableLabel("/cad/connections")).toBe("CAD connections");
    expect(offlineCapableLabel("/presence")).toBe("Presence");
    expect(offlineCapableLabel("/troubleshoot")).toBe("Get unstuck");
    expect(offlineCapableLabel("/media-library")).toBe("Media Library");
    expect(offlineCapableLabel("/hours/kiosk")).toBe("Hours kiosk");
    expect(offlineCapableLabel("/hours")).toBe("Hours");
    expect(offlineCapableLabel("/scouting/forms")).toBe("Scout forms");
    expect(offlineCapableLabel("/goals-tracker")).toBe("Season Goals");
    expect(offlineCapableLabel("/standup-digest")).toBe("Morning standup");
    expect(offlineCapableLabel("/meeting-autopilot")).toBe("Meeting agenda");
    expect(offlineCapableLabel("/goals")).toBe("Goals");
    expect(offlineCapableLabel("/safety-training")).toBe("Safety Training");
    expect(offlineCapableLabel("/safety")).toBe("Safety");
    expect(offlineCapableLabel("/notifications/preferences")).toBe("Notification preferences");
    expect(offlineCapableLabel("/notifications")).toBe("Notifications");
    expect(offlineCapableLabel("/team/grants/calendar")).toBe("Grant calendar");
    expect(offlineCapableLabel("/team/admin")).toBe("Team admin");
    expect(offlineCapableLabel("/team/security")).toBe("Team security");
    expect(offlineCapableLabel("/security")).toBe("Security");
    expect(offlineCapableLabel("/wiring-diagnoser")).toBe("Wiring check");
    expect(offlineCapableLabel("/wiring")).toBe("CAN-bus map");
    expect(offlineCapableLabel("/tuning")).toBe("Tuning log");
    expect(offlineCapableLabel("/search")).toBe("Search");
    expect(offlineCapableLabel("/account")).toBe("Account");
    expect(offlineCapableLabel("/whats-new")).toBe("What’s new");
  });

  it("keeps public/sw.js SHELL_ROUTES aligned with OFFLINE_SHELL_ROUTES", () => {
    const sw = readFileSync(join(WEB_ROOT, "public", "sw.js"), "utf8");
    const block = sw.match(/const SHELL_ROUTES = \[([\s\S]*?)\];/);
    expect(block, "sw.js is missing SHELL_ROUTES").toBeTruthy();
    const routes = [...(block?.[1] ?? "").matchAll(/"([^"]+)"/g)].map((match) => match[1]);
    expect([...routes].sort()).toEqual([...OFFLINE_SHELL_ROUTES].sort());
  });

  it("builds stable feature cache keys", () => {
    expect(featureCacheKey("todos", " org-1 ")).toBe("todos:org-1");
    expect(featureCacheKey("logistics", "")).toBe("logistics:_");
    expect(featureCacheKey("files", "org-1", "team:")).toBe("files:org-1:team:");
    expect(featureCacheKey("packing", "org-1")).toBe("packing:org-1");
    expect(featureCacheKey("batteries", "org-1")).toBe("batteries:org-1");
    expect(featureCacheKey("pit", "org-1")).toBe("pit:org-1");
    expect(featureCacheKey("season-tasks", "org-1", "2026")).toBe("season-tasks:org-1:2026");
    expect(featureCacheKey("calendar", "org-1")).toBe("calendar:org-1");
    expect(featureCacheKey("my-day", "org-1")).toBe("my-day:org-1");
    expect(featureCacheKey("dashboard", "org-1")).toBe("dashboard:org-1");
    expect(featureCacheKey("assembly-manual", "org-1")).toBe("assembly-manual:org-1");
    expect(featureCacheKey("chemistry", "org-1")).toBe("chemistry:org-1");
    expect(featureCacheKey("pick-clock", "org-1")).toBe("pick-clock:org-1");
    expect(featureCacheKey("alliance-desk", "org-1", "sess-1")).toBe("alliance-desk:org-1:sess-1");
    expect(featureCacheKey("print-farm", "org-1")).toBe("print-farm:org-1");
    expect(featureCacheKey("inventory", "org-1")).toBe("inventory:org-1");
    expect(featureCacheKey("defense-planner", "org-1", "2026")).toBe("defense-planner:org-1:2026");
    expect(featureCacheKey("picklist-collab", "org-1", "list-1")).toBe("picklist-collab:org-1:list-1");
    expect(featureCacheKey("dossier", "org-1", "frc254")).toBe("dossier:org-1:frc254");
    expect(featureCacheKey("pit-repair", "org-1", "2026")).toBe("pit-repair:org-1:2026");
    expect(featureCacheKey("event-day-plan", "org-1", "2026onto")).toBe("event-day-plan:org-1:2026onto");
    expect(featureCacheKey("field-reset", "org-1", "2026")).toBe("field-reset:org-1:2026");
    expect(featureCacheKey("drive-signals", "org-1")).toBe("drive-signals:org-1");
    expect(featureCacheKey("weigh-in", "org-1", "2026")).toBe("weigh-in:org-1:2026");
    expect(featureCacheKey("match-delta", "org-1", "2026onto")).toBe("match-delta:org-1:2026onto");
    expect(featureCacheKey("match-video-index", "org-1")).toBe("match-video-index:org-1");
    expect(featureCacheKey("draft", "org-1", "2026onto")).toBe("draft:org-1:2026onto");
    expect(featureCacheKey("lineup", "org-1", "2026onto")).toBe("lineup:org-1:2026onto");
    expect(featureCacheKey("strategy-cards", "org-1")).toBe("strategy-cards:org-1");
    expect(featureCacheKey("match-copilot", "org-1")).toBe("match-copilot:org-1");
    expect(featureCacheKey("event-readiness", "org-1", "2026onto")).toBe("event-readiness:org-1:2026onto");
    expect(featureCacheKey("match-video", "org-1")).toBe("match-video:org-1");
    expect(featureCacheKey("inspection", "org-1")).toBe("inspection:org-1");
    expect(featureCacheKey("inspection-copilot", "org-1", "2026")).toBe("inspection-copilot:org-1:2026");
    expect(featureCacheKey("fmea", "org-1", "2026")).toBe("fmea:org-1:2026");
    expect(featureCacheKey("match-sim", "org-1")).toBe("match-sim:org-1");
    expect(featureCacheKey("pit-map", "org-1", "2026")).toBe("pit-map:org-1:2026");
    expect(featureCacheKey("pairwise", "org-1")).toBe("pairwise:org-1");
    expect(featureCacheKey("team-tags", "org-1")).toBe("team-tags:org-1");
    expect(featureCacheKey("shift-balancer", "org-1")).toBe("shift-balancer:org-1");
    expect(featureCacheKey("counter-book", "org-1")).toBe("counter-book:org-1");
    expect(featureCacheKey("intel", "org-1")).toBe("intel:org-1");
    expect(featureCacheKey("overnight-intel", "org-1")).toBe("overnight-intel:org-1");
    expect(featureCacheKey("alliance-brief", "org-1", "1")).toBe("alliance-brief:org-1:1");
    expect(featureCacheKey("picklist-justifier", "org-1", "list-1")).toBe("picklist-justifier:org-1:list-1");
    expect(featureCacheKey("opponent-watchlist", "org-1")).toBe("opponent-watchlist:org-1");
    expect(featureCacheKey("alliance-sim", "org-1", "scen-1")).toBe("alliance-sim:org-1:scen-1");
    expect(featureCacheKey("briefing", "org-1", "2026onto_qm1")).toBe("briefing:org-1:2026onto_qm1");
    expect(featureCacheKey("award-tracker", "org-1", "2026")).toBe("award-tracker:org-1:2026");
    expect(featureCacheKey("epa-trend", "org-1")).toBe("epa-trend:org-1");
    expect(featureCacheKey("rankings", "org-1")).toBe("rankings:org-1");
    expect(featureCacheKey("grant-report", "org-1", "2026")).toBe("grant-report:org-1:2026");
    expect(featureCacheKey("media-kit", "org-1", "2026")).toBe("media-kit:org-1:2026");
    expect(featureCacheKey("sponsor-wall", "org-1")).toBe("sponsor-wall:org-1");
    expect(featureCacheKey("sponsor-suite", "org-1", "2026")).toBe("sponsor-suite:org-1:2026");
    expect(featureCacheKey("outreach-calendar", "org-1", "2026")).toBe("outreach-calendar:org-1:2026");
    expect(featureCacheKey("visit-invites", "org-1")).toBe("visit-invites:org-1");
    expect(featureCacheKey("judge-sim", "org-1", "2026")).toBe("judge-sim:org-1:2026");
    expect(featureCacheKey("impact-essay", "org-1", "2026")).toBe("impact-essay:org-1:2026");
    expect(featureCacheKey("battery-rotation", "org-1")).toBe("battery-rotation:org-1");
    expect(featureCacheKey("vendors", "org-1")).toBe("vendors:org-1");
    expect(featureCacheKey("season-report", "org-1", "2026")).toBe("season-report:org-1:2026");
    expect(featureCacheKey("media", "org-1", "2026")).toBe("media:org-1:2026");
    expect(featureCacheKey("battery-health-forecast", "org-1")).toBe("battery-health-forecast:org-1");
    expect(featureCacheKey("vendor-lead-times", "org-1")).toBe("vendor-lead-times:org-1");
    expect(featureCacheKey("bin-shelf-locator", "org-1")).toBe("bin-shelf-locator:org-1");
    expect(featureCacheKey("build-burndown", "org-1", "2026")).toBe("build-burndown:org-1:2026");
    expect(featureCacheKey("cad-change-radar", "org-1")).toBe("cad-change-radar:org-1");
    expect(featureCacheKey("code-deploy-log", "org-1", "2026")).toBe("code-deploy-log:org-1:2026");
    expect(featureCacheKey("control-map", "org-1", "2026")).toBe("control-map:org-1:2026");
    expect(featureCacheKey("cross-team-scrim", "org-1", "2026")).toBe("cross-team-scrim:org-1:2026");
    expect(featureCacheKey("decision-search", "org-1", "2026")).toBe("decision-search:org-1:2026");
    expect(featureCacheKey("decisions", "org-1", "2026")).toBe("decisions:org-1:2026");
    expect(featureCacheKey("failure-patterns", "org-1", "2026")).toBe("failure-patterns:org-1:2026");
    expect(featureCacheKey("grant-eligibility-matcher", "org-1")).toBe("grant-eligibility-matcher:org-1");
    expect(featureCacheKey("hours-self-view", "org-1")).toBe("hours-self-view:org-1");
    expect(featureCacheKey("knowledge-gap", "org-1", "2026")).toBe("knowledge-gap:org-1:2026");
    expect(featureCacheKey("knowledge", "org-1")).toBe("knowledge:org-1");
    expect(featureCacheKey("matching-gift-finder", "org-1")).toBe("matching-gift-finder:org-1");
    expect(featureCacheKey("onboarding-buddy", "org-1")).toBe("onboarding-buddy:org-1");
    expect(featureCacheKey("risk-burndown", "org-1", "2026")).toBe("risk-burndown:org-1:2026");
    expect(featureCacheKey("spare-robot-kit", "org-1", "2026")).toBe("spare-robot-kit:org-1:2026");
    expect(featureCacheKey("sponsor-renewal-roi", "org-1", "2026")).toBe("sponsor-renewal-roi:org-1:2026");
    expect(featureCacheKey("team-health-dashboard", "org-1", "2026")).toBe("team-health-dashboard:org-1:2026");
    expect(featureCacheKey("spare-forecast", "org-1", "2026")).toBe("spare-forecast:org-1:2026");
    expect(featureCacheKey("sketch-to-brief", "org-1", "2026")).toBe("sketch-to-brief:org-1:2026");
    expect(featureCacheKey("scout-assisted-count", "org-1")).toBe("scout-assisted-count:org-1");
    expect(featureCacheKey("scout-coverage-live", "org-1")).toBe("scout-coverage-live:org-1");
    expect(featureCacheKey("scout-field-budget", "org-1")).toBe("scout-field-budget:org-1");
    expect(featureCacheKey("scouting-heat-signals", "org-1")).toBe("scouting-heat-signals:org-1");
    expect(featureCacheKey("scout-data-impact", "org-1", "2026txcmp")).toBe("scout-data-impact:org-1:2026txcmp");
    expect(featureCacheKey("scout-disagreements", "org-1", "2026")).toBe("scout-disagreements:org-1:2026");
    expect(featureCacheKey("scout-accuracy", "org-1", "2026txcmp")).toBe("scout-accuracy:org-1:2026txcmp");
    expect(featureCacheKey("scout-crossval", "org-1", "2026txcmp")).toBe("scout-crossval:org-1:2026txcmp");
    expect(featureCacheKey("rule-impact", "org-1", "2026")).toBe("rule-impact:org-1:2026");
    expect(featureCacheKey("season-planning-workspace", "org-1", "2026")).toBe("season-planning-workspace:org-1:2026");
    expect(featureCacheKey("retro", "org-1", "2026")).toBe("retro:org-1:2026");
    expect(featureCacheKey("team-data", "org-1")).toBe("team-data:org-1");
    expect(featureCacheKey("tuning-autopilot", "org-1", "2026")).toBe("tuning-autopilot:org-1:2026");
    expect(featureCacheKey("video-rescout", "org-1")).toBe("video-rescout:org-1");
    expect(featureCacheKey("fundraisers", "org-1", "2026")).toBe("fundraisers:org-1:2026");
    expect(featureCacheKey("impact", "org-1", "2026")).toBe("impact:org-1:2026");
    expect(featureCacheKey("orders", "org-1", "2026")).toBe("orders:org-1:2026");
    expect(featureCacheKey("grants-writing", "org-1", "2026")).toBe("grants-writing:org-1:2026");
    expect(featureCacheKey("practice", "org-1")).toBe("practice:org-1");
    expect(featureCacheKey("manufacturing", "org-1")).toBe("manufacturing:org-1");
    expect(featureCacheKey("attendance", "org-1", "2026")).toBe("attendance:org-1:2026");
    expect(featureCacheKey("kickoff", "org-1")).toBe("kickoff:org-1");
    expect(featureCacheKey("match-debrief", "org-1", "2026")).toBe("match-debrief:org-1:2026");
    expect(featureCacheKey("ranking-projection", "org-1")).toBe("ranking-projection:org-1");
    expect(featureCacheKey("whiteboard", "org-1")).toBe("whiteboard:org-1");
    expect(featureCacheKey("robot", "org-1")).toBe("robot:org-1");
    expect(featureCacheKey("my-kit", "org-1")).toBe("my-kit:org-1");
    expect(featureCacheKey("part-requests", "org-1", "2026")).toBe("part-requests:org-1:2026");
    expect(featureCacheKey("recognition", "org-1", "2026")).toBe("recognition:org-1:2026");
    expect(featureCacheKey("subteams", "org-1")).toBe("subteams:org-1");
    expect(featureCacheKey("budget", "org-1", "2026")).toBe("budget:org-1:2026");
    expect(featureCacheKey("sponsorship", "org-1", "2026")).toBe("sponsorship:org-1:2026");
    expect(featureCacheKey("safety", "org-1")).toBe("safety:org-1");
    expect(featureCacheKey("writer", "org-1", "2026")).toBe("writer:org-1:2026");
    expect(featureCacheKey("learning", "org-1")).toBe("learning:org-1");
    expect(featureCacheKey("training", "org-1")).toBe("training:org-1");
    expect(featureCacheKey("tool-checkout", "org-1")).toBe("tool-checkout:org-1");
    expect(featureCacheKey("goals", "org-1", "2026")).toBe("goals:org-1:2026");
    expect(featureCacheKey("cad-vault", "org-1", "2026")).toBe("cad-vault:org-1:2026");
    expect(featureCacheKey("cad-learn", "org-1")).toBe("cad-learn:org-1");
    expect(featureCacheKey("reimbursements", "org-1")).toBe("reimbursements:org-1");
    expect(featureCacheKey("costs", "org-1", "2026")).toBe("costs:org-1:2026");
    expect(featureCacheKey("cad-review-queue", "org-1", "2026")).toBe("cad-review-queue:org-1:2026");
    expect(featureCacheKey("duties", "org-1")).toBe("duties:org-1");
    expect(featureCacheKey("announcements", "org-1")).toBe("announcements:org-1");
    expect(featureCacheKey("risks", "org-1", "2026")).toBe("risks:org-1:2026");
    expect(featureCacheKey("subsystem-signoff", "org-1", "2026")).toBe("subsystem-signoff:org-1:2026");
    expect(featureCacheKey("prototype-tracker", "org-1", "2026")).toBe("prototype-tracker:org-1:2026");
    expect(featureCacheKey("equipment-maintenance", "org-1")).toBe("equipment-maintenance:org-1");
    expect(featureCacheKey("notifications", "org-1", "unread")).toBe("notifications:org-1:unread");
    expect(featureCacheKey("forms", "org-1")).toBe("forms:org-1");
    expect(featureCacheKey("incidents", "org-1", "2026")).toBe("incidents:org-1:2026");
    expect(featureCacheKey("roles", "org-1", "2026")).toBe("roles:org-1:2026");
    expect(featureCacheKey("team-admin", "org-1")).toBe("team-admin:org-1");
    expect(featureCacheKey("parts-catalog", "org-1")).toBe("parts-catalog:org-1");
    expect(featureCacheKey("parts-relay", "org-1")).toBe("parts-relay:org-1");
    expect(featureCacheKey("cad-setup", "org-1")).toBe("cad-setup:org-1");
    expect(featureCacheKey("account", "org-1")).toBe("account:org-1");
    expect(featureCacheKey("presence", "org-1")).toBe("presence:org-1");
    expect(featureCacheKey("support", "org-1")).toBe("support:org-1");
    expect(featureCacheKey("support-tickets", "org-1")).toBe("support-tickets:org-1");
    expect(featureCacheKey("hours-kiosk", "org-1")).toBe("hours-kiosk:org-1");
    expect(featureCacheKey("media-library", "org-1")).toBe("media-library:org-1");
    expect(featureCacheKey("form-detail", "org-1")).toBe("form-detail:org-1");
    expect(featureCacheKey("cad-connections", "org-1")).toBe("cad-connections:org-1");
    expect(featureCacheKey("notification-prefs", "org-1")).toBe("notification-prefs:org-1");
    expect(featureCacheKey("hub-access", "org-1")).toBe("hub-access:org-1");
    expect(featureCacheKey("funding-profile", "org-1")).toBe("funding-profile:org-1");
    expect(featureCacheKey("schedule", "org-1")).toBe("schedule:org-1");
    expect(featureCacheKey("scouting", "org-1")).toBe("scouting:org-1");
    expect(featureCacheKey("pick-desk", "org-1")).toBe("pick-desk:org-1");
    expect(featureCacheKey("business", "org-1", "2026")).toBe("business:org-1:2026");
    expect(featureCacheKey("season-finance", "org-1", "2026")).toBe("season-finance:org-1:2026");
    expect(featureCacheKey("partner-placements", "org-1")).toBe("partner-placements:org-1");
  });

  it("falls failed navigations back to the precached shell", () => {
    expect(navigationFallbackPath()).toBe("/offline");
  });

  it("detects RSC / Flight requests so the SW can bypass them", () => {
    expect(isRscRequest(new Headers({ accept: "text/x-component", RSC: "1" }))).toBe(true);
    expect(isRscRequest(new Headers({ "Next-Router-State-Tree": "%5B%5D" }))).toBe(true);
    expect(isRscRequest(new Headers({ accept: "text/html" }))).toBe(false);
  });
});

