import { AGENT_CONFIG_NAME, parseFrontmatter, parseRuleScope } from "./formats";
import type { AgentConfigBundle } from "./store";

/**
 * Pure Cursor writers for team-shared agent configuration.
 *
 * Each output is a REAL artifact in Cursor's CURRENT native formats, verified
 * 2026-08 against the official docs:
 *
 * - Project rules → `.cursor/rules/*.mdc` files ("Project rules live in
 *   .cursor/rules as .mdc files"), MDC YAML frontmatter with `description:`,
 *   `globs:` ("Separate multiple patterns with commas."), and `alwaysApply:`
 *   ("If alwaysApply is true, the rule will be applied to every chat
 *   session."); nested folders under .cursor/rules are supported.
 *   Source: https://cursor.com/docs/context/rules
 *   (The legacy single-file `.cursorrules` no longer appears in the current
 *   docs; only the .mdc format is written here.)
 * - MCP servers → `.cursor/mcp.json` under a top-level `mcpServers` key with
 *   the same entry shape Claude uses: `command`/`args`/`env` for stdio,
 *   `url` (+ optional `headers`) for remote HTTP/SSE.
 *   Source: https://cursor.com/docs/context/mcp
 * - Agent Skills → `.cursor/skills/<name>/SKILL.md`, YAML frontmatter with
 *   required `name` ("Must match the parent folder name.") and `description`;
 *   skills may be organized recursively in subdirectories.
 *   Source: https://cursor.com/docs/skills
 *
 * Subagents and permission snippets have no verified Cursor-native equivalent,
 * so they are intentionally NOT exported to Cursor (sync reports them as
 * skipped rather than inventing a format).
 *
 * Everything Vantage writes lives inside managed namespaces so re-sync can
 * update or prune without ever touching user-authored files:
 * rules under `.cursor/rules/vantage/`, skills under `.cursor/skills/vantage/`,
 * mcp entries under the `vantage-` key prefix.
 */

export const CURSOR_RULES_DIR = ".cursor/rules/vantage";
export const CURSOR_SKILLS_DIR = ".cursor/skills/vantage";
export const CURSOR_MCP_FILE = ".cursor/mcp.json";
export const CURSOR_MCP_PREFIX = "vantage-";

/** Marks a file as Vantage-managed: sync only ever prunes files carrying it. */
export const CURSOR_GENERATED_BANNER =
  "<!-- Generated by `vantage-cad agent sync` — edit at /team/agent-config, not here. -->";

/** YAML double-quoted scalar (JSON string escaping is valid YAML). */
function yamlQuote(value: string): string {
  return JSON.stringify(value);
}

export type CursorRuleFile = { filename: string; content: string };

/**
 * One shared rule → one `.cursor/rules/vantage/<name>.mdc` file.
 *
 * Frontmatter mapping (rule metadata comes from the item description plus the
 * optional scope frontmatter parsed by parseRuleScope):
 * - globs declared  → Auto Attached: `globs:` + `alwaysApply: false`
 * - no globs        → team-wide always-on: `alwaysApply: true`
 * - an explicit `alwaysApply:` in the rule's scope frontmatter wins.
 */
export function buildCursorRuleMdc(rule: {
  name: string;
  description: string | null;
  markdown: string;
}): CursorRuleFile | null {
  if (!AGENT_CONFIG_NAME.test(rule.name)) return null;
  const scope = parseRuleScope(rule.markdown);
  const body = scope.body.trim();
  if (!body) return null;
  const description = scope.description ?? rule.description;
  const alwaysApply = scope.alwaysApply ?? !scope.globs;
  const frontmatter = ["---"];
  if (description) frontmatter.push(`description: ${yamlQuote(description)}`);
  if (scope.globs) frontmatter.push(`globs: ${scope.globs.join(",")}`);
  frontmatter.push(`alwaysApply: ${alwaysApply}`, "---");
  return {
    filename: `${rule.name}.mdc`,
    content: `${frontmatter.join("\n")}\n\n${CURSOR_GENERATED_BANNER}\n\n${body}\n`,
  };
}

/**
 * Cursor requires a skill's folder name to match its SKILL.md frontmatter
 * `name`. Prefer the frontmatter name when it is filename-safe; fall back to
 * the item name (which the save path already validated).
 */
export function cursorSkillFolder(markdown: string, itemName: string): string | null {
  const parsed = parseFrontmatter(markdown);
  const fromFrontmatter = typeof parsed.fields.name === "string" ? parsed.fields.name.trim() : "";
  if (fromFrontmatter && AGENT_CONFIG_NAME.test(fromFrontmatter)) return fromFrontmatter;
  return AGENT_CONFIG_NAME.test(itemName) ? itemName : null;
}

/**
 * The mcpServers record for `.cursor/mcp.json`, namespaced under `vantage-`
 * exactly like the Claude `.mcp.json` merge so re-sync can update/prune its
 * own keys without touching user-configured servers.
 */
export function buildCursorMcpServers(
  servers: AgentConfigBundle["mcpServers"],
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const server of servers) {
    if (!AGENT_CONFIG_NAME.test(server.name)) continue;
    out[`${CURSOR_MCP_PREFIX}${server.name}`] = server.entry;
  }
  return out;
}

export type CursorExport = {
  /** Relative path → full file content, ready to write into a repo. */
  files: Record<string, string>;
  /** Entries for `.cursor/mcp.json` mcpServers (merge, do not overwrite). */
  mcpServers: Record<string, unknown>;
  /** Item names that have no Cursor-native representation. */
  skipped: Array<{ kind: string; name: string; reason: string }>;
};

/** Materialize a (scope-filtered) bundle as Cursor-native files. */
export function buildCursorExport(bundle: AgentConfigBundle): CursorExport {
  const files: Record<string, string> = {};
  const skipped: CursorExport["skipped"] = [];
  for (const rule of bundle.rules) {
    const file = buildCursorRuleMdc(rule);
    if (file) files[`${CURSOR_RULES_DIR}/${file.filename}`] = file.content;
    else skipped.push({ kind: "rules", name: rule.name, reason: "empty body or unsafe name" });
  }
  for (const skill of bundle.skills) {
    const folder = cursorSkillFolder(skill.markdown, skill.name);
    if (folder) files[`${CURSOR_SKILLS_DIR}/${folder}/SKILL.md`] = `${skill.markdown.trim()}\n`;
    else skipped.push({ kind: "skill", name: skill.name, reason: "unsafe name" });
  }
  for (const subagent of bundle.subagents) {
    skipped.push({ kind: "subagent", name: subagent.name, reason: "no Cursor equivalent" });
  }
  for (const permissions of bundle.permissions) {
    skipped.push({ kind: "permissions", name: permissions.name, reason: "no Cursor equivalent" });
  }
  return { files, mcpServers: buildCursorMcpServers(bundle.mcpServers), skipped };
}
