"use client";
import { useEffect, useState } from "react";
import { PRICING_CATALOG, TEAM_TRIAL_DAYS } from "@vantage/billing/catalog";
type Org = { id:string;name:string;teamNumber:number;planCode:string|null;status:string|null;validUntil:string|null;creditBalance:string;modelCost:string };
export default function CommercialClient() {
  const [orgs,setOrgs]=useState<Org[]>([]); const [orgId,setOrgId]=useState(""); const [message,setMessage]=useState(""); const [ok,setOk]=useState(false);
  const [gift,setGift]=useState({amountUsd:"",reason:""}); const [pack,setPack]=useState({code:"",name:"",creditAmountUsd:"",purchasePriceUsd:"",stripePriceId:"",active:false});
  const [margin,setMargin]=useState<{revenue:string;providerCost:string;subscriptions:number;config:{stripeFeePercent:string;stripeFixedFeeUsd:string;infrastructureAllocationUsd:string;grossMarginWarningPercent:string}}|null>(null);
  async function load(){const r=await fetch("/api/admin/commercial");const d=await r.json();setOrgs(d.organizations??[]);setMargin(d.margin??null);if(!r.ok){setMessage(d.error);setOk(false);}}
  useEffect(()=>{void load();},[]);
  async function post(body:unknown){const r=await fetch("/api/admin/commercial",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();setMessage(r.ok?"Commercial ledger updated.":d.error);setOk(r.ok);if(r.ok)await load();}
  const trialApi = PRICING_CATALOG.team_trial.includedAllowanceUsd;
  return <main className="intel-app"><header className="intel-header"><div><span className="eyebrow">VANTAGE / COMMERCIAL CONTROL</span><h1>Entitlements + credits</h1></div><a href="/admin/models">Model routing →</a></header>
    {message&&<p className={`telemetry-status${ok?" success":""}`}>{message}</p>}<section className="admin-grid"><section className="intel-panel"><span className="eyebrow">ORGANIZATIONS</span>{orgs.map((o)=><button className="similar-team" key={o.id} onClick={()=>setOrgId(o.id)}><b>#{o.teamNumber}</b><span>{o.name}<small>{o.planCode??"Free"} · {o.status??"no entitlement"}</small></span><em>${Number(o.creditBalance).toFixed(2)} credits</em></button>)}</section>
      <section className="intel-panel"><span className="eyebrow">AUDITED ACTIONS</span><label>Selected organization<select value={orgId} onChange={(e)=>setOrgId(e.target.value)}><option value="">Choose team</option>{orgs.map((o)=><option key={o.id} value={o.id}>#{o.teamNumber} {o.name}</option>)}</select></label>
        <div className="intel-actions"><button disabled={!orgId} onClick={()=>void post({action:"trial",orgId,planCode:"team_trial"})}>Grant {TEAM_TRIAL_DAYS}-day team trial (${trialApi} API)</button><button disabled={!orgId} onClick={()=>void post({action:"trial",orgId,planCode:"individual_pro"})}>Grant {TEAM_TRIAL_DAYS}-day Individual Pro trial</button><button disabled={!orgId} onClick={()=>confirm("Revoke the active trial now?")&&void post({action:"revoke-trial",orgId})}>Revoke trial</button></div>
        <label>Gift amount USD<input type="number" min="0.01" step="0.01" value={gift.amountUsd} onChange={(e)=>setGift({...gift,amountUsd:e.target.value})}/></label><label>Required reason<input value={gift.reason} onChange={(e)=>setGift({...gift,reason:e.target.value})}/></label><button className="primary-action" disabled={!orgId} onClick={()=>void post({action:"gift",orgId,...gift})}>Gift credits + notify</button>
      </section></section>
    {margin&&<MarginPanel value={margin}/>}
    <section className="compare-panel"><span className="eyebrow">CREDIT PACK CONFIGURATION</span><div className="pick-controls"><input placeholder="Code" value={pack.code} onChange={(e)=>setPack({...pack,code:e.target.value})}/><input placeholder="Display name" value={pack.name} onChange={(e)=>setPack({...pack,name:e.target.value})}/><input placeholder="Credits USD" type="number" value={pack.creditAmountUsd} onChange={(e)=>setPack({...pack,creditAmountUsd:e.target.value})}/><input placeholder="Purchase USD" type="number" value={pack.purchasePriceUsd} onChange={(e)=>setPack({...pack,purchasePriceUsd:e.target.value})}/><input placeholder="Stripe Price ID" value={pack.stripePriceId} onChange={(e)=>setPack({...pack,stripePriceId:e.target.value})}/><label className="check-field"><input type="checkbox" checked={pack.active} onChange={(e)=>setPack({...pack,active:e.target.checked})}/> Active</label><button onClick={()=>void post({action:"credit-pack",...pack})}>Save pack</button></div></section>
  </main>;
}
function MarginPanel({value}:{value:{revenue:string;providerCost:string;subscriptions:number;config:{stripeFeePercent:string;stripeFixedFeeUsd:string;infrastructureAllocationUsd:string;grossMarginWarningPercent:string}}}){const revenue=Number(value.revenue),provider=Number(value.providerCost),fees=revenue*Number(value.config.stripeFeePercent)/100+value.subscriptions*Number(value.config.stripeFixedFeeUsd),infra=value.subscriptions*Number(value.config.infrastructureAllocationUsd),gross=revenue-fees-provider-infra,percent=revenue?gross/revenue*100:0,warning=percent<Number(value.config.grossMarginWarningPercent);return<section className={`compare-panel ${warning?"margin-warning":""}`}><span className="eyebrow">MARGIN / VIABILITY</span><h2>{warning?"Thin-margin warning":"Current allocation estimate"}</h2><div className="metric-grid"><article><span>Subscription revenue</span><strong>${revenue.toFixed(2)}</strong></article><article><span>Stripe fee estimate</span><strong>${fees.toFixed(2)}</strong></article><article><span>Provider cost</span><strong>${provider.toFixed(2)}</strong></article><article><span>Infrastructure allocation</span><strong>${infra.toFixed(2)}</strong></article><article><span>Estimated gross margin</span><strong>${gross.toFixed(2)} · {percent.toFixed(1)}%</strong></article></div><p>Included API allowances are provider-cost usage at list rates (1.0×, no Vantage markup)—not cash or withdrawable balances. Usage Credits are $1 = $1 API. To protect viability, publish a new entitlement version with notice for future periods/new subscriptions; never rewrite an active paid period snapshot.</p></section>;}
