import { createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual } from "node:crypto";
import type { PoolClient } from "@neondatabase/serverless";

export type SignInMethod="password"|"google"|"email_otp";
export type OrgAuthPolicy={allowPassword:boolean;allowGoogle:boolean;allowEmailOtp:boolean;mfaPolicy:"off"|"optional"|"required";rememberedDeviceDays:number};
export const DEFAULT_ORG_AUTH_POLICY:OrgAuthPolicy={allowPassword:false,allowGoogle:true,allowEmailOtp:true,mfaPolicy:"optional",rememberedDeviceDays:14};

export function evaluateOrgAuthAccess(policy:OrgAuthPolicy,method:SignInMethod,mfaEnrolled:boolean,stepUpValid:boolean){
  const allowed=method==="password"?policy.allowPassword:method==="google"?policy.allowGoogle:policy.allowEmailOtp;
  if(!allowed)return{allowed:false,reason:"sign_in_method_not_allowed" as const,requiresMfa:false};
  const requiresMfa=policy.mfaPolicy==="required";
  if(requiresMfa&&!mfaEnrolled)return{allowed:false,reason:"mfa_enrollment_required" as const,requiresMfa:true};
  if(requiresMfa&&!stepUpValid)return{allowed:false,reason:"mfa_step_up_required" as const,requiresMfa:true};
  return{allowed:true,reason:null,requiresMfa};
}
export function validateOrgAuthPolicy(policy:OrgAuthPolicy){if(!policy.allowPassword&&!policy.allowGoogle&&!policy.allowEmailOtp)throw new Error("At least one sign-in method must remain enabled");if(policy.rememberedDeviceDays<0||policy.rememberedDeviceDays>90)throw new Error("Remembered-device duration must be 0–90 days");}

const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
function base32(bytes:Buffer){let bits=0,value=0,out="";for(const byte of bytes){value=(value<<8)|byte;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5;}}if(bits>0)out+=alphabet[(value<<(5-bits))&31];return out;}
function decodeBase32(input:string){let bits=0,value=0;const out:number[]=[];for(const char of input.replace(/=+$/,"").toUpperCase()){const index=alphabet.indexOf(char);if(index<0)throw new Error("Invalid authenticator secret");value=(value<<5)|index;bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8;}}return Buffer.from(out);}
function encryptionKey(){return createHash("sha256").update(process.env.MFA_ENCRYPTION_KEY??process.env.BETTER_AUTH_SECRET??"local-development-secret-change-me").digest();}
export function encryptMfaSecret(secret:string){const iv=randomBytes(12);const cipher=createCipheriv("aes-256-gcm",encryptionKey(),iv);const encrypted=Buffer.concat([cipher.update(secret,"utf8"),cipher.final()]);return`${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`;}
export function decryptMfaSecret(value:string){const[iv,tag,data]=value.split(".");if(!iv||!tag||!data)throw new Error("Invalid encrypted MFA secret");const cipher=createDecipheriv("aes-256-gcm",encryptionKey(),Buffer.from(iv,"base64url"));cipher.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([cipher.update(Buffer.from(data,"base64url")),cipher.final()]).toString("utf8");}
export function totpAt(secret:string,timeMs=Date.now(),period=30){const step=Math.floor(timeMs/1000/period);const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(step));const digest=createHmac("sha1",decodeBase32(secret)).update(counter).digest();const offset=digest[digest.length-1]!&15;const value=(digest.readUInt32BE(offset)&0x7fffffff)%1_000_000;return{code:String(value).padStart(6,"0"),step:String(step)};}
export function verifyTotp(secret:string,code:string,timeMs=Date.now()){if(!/^\d{6}$/.test(code))return null;for(const drift of[-1,0,1]){const candidate=totpAt(secret,timeMs+drift*30_000);const a=Buffer.from(candidate.code),b=Buffer.from(code);if(a.length===b.length&&timingSafeEqual(a,b))return candidate.step;}return null;}
export function isTotpReplay(previousStep:string|null|undefined,verifiedStep:string|null){return Boolean(verifiedStep&&previousStep===verifiedStep);}
function recoveryHash(userId:string,code:string){return createHmac("sha256",process.env.MFA_RECOVERY_PEPPER??process.env.BETTER_AUTH_SECRET??"local-recovery-pepper").update(`${userId}:${code.trim().toUpperCase()}`).digest("hex");}
function newRecoveryCodes(){return Array.from({length:10},()=>`${randomBytes(3).toString("hex")}-${randomBytes(3).toString("hex")}`.toUpperCase());}
export async function beginMfaEnrollment(client:PoolClient,user:{id:string;email:string}){const secret=base32(randomBytes(20));await client.query(`INSERT INTO user_mfa_enrollments(user_id,encrypted_secret,confirmed_at) VALUES($1,$2,NULL) ON CONFLICT(user_id) DO UPDATE SET encrypted_secret=excluded.encrypted_secret,confirmed_at=NULL,updated_at=now()`,[user.id,encryptMfaSecret(secret)]);const label=encodeURIComponent(`Vantage:${user.email}`);return{secret,uri:`otpauth://totp/${label}?secret=${secret}&issuer=Vantage&digits=6&period=30`};}
export async function confirmMfaEnrollment(client:PoolClient,userId:string,code:string){const result=await client.query<{encrypted_secret:string;recovery_generation:number}>(`SELECT encrypted_secret,recovery_generation FROM user_mfa_enrollments WHERE user_id=$1 FOR UPDATE`,[userId]);const row=result.rows[0];if(!row)throw new Error("MFA setup was not started");if(!verifyTotp(decryptMfaSecret(row.encrypted_secret),code))throw new Error("Invalid authenticator code");const generation=row.recovery_generation+1,codes=newRecoveryCodes();await client.query(`UPDATE user_mfa_enrollments SET confirmed_at=now(),recovery_generation=$2,updated_at=now() WHERE user_id=$1`,[userId,generation]);await client.query(`DELETE FROM mfa_recovery_codes WHERE user_id=$1`,[userId]);for(const item of codes)await client.query(`INSERT INTO mfa_recovery_codes(user_id,code_hash,generation) VALUES($1,$2,$3)`,[userId,recoveryHash(userId,item),generation]);return codes;}
export async function regenerateRecoveryCodes(client:PoolClient,userId:string,totpCode:string){const result=await client.query<{encrypted_secret:string;recovery_generation:number}>(`SELECT encrypted_secret,recovery_generation FROM user_mfa_enrollments WHERE user_id=$1 AND confirmed_at IS NOT NULL FOR UPDATE`,[userId]);const row=result.rows[0];if(!row||!verifyTotp(decryptMfaSecret(row.encrypted_secret),totpCode))throw new Error("Valid authenticator code required");const generation=row.recovery_generation+1,codes=newRecoveryCodes();await client.query(`UPDATE user_mfa_enrollments SET recovery_generation=$2,updated_at=now() WHERE user_id=$1`,[userId,generation]);await client.query(`DELETE FROM mfa_recovery_codes WHERE user_id=$1`,[userId]);for(const item of codes)await client.query(`INSERT INTO mfa_recovery_codes(user_id,code_hash,generation) VALUES($1,$2,$3)`,[userId,recoveryHash(userId,item),generation]);return codes;}
export async function verifyMfaStepUp(client:PoolClient,input:{userId:string;orgId:string;sessionId:string;code:string;rememberDays?:number}){const result=await client.query<{encrypted_secret:string}>(`SELECT encrypted_secret FROM user_mfa_enrollments WHERE user_id=$1 AND confirmed_at IS NOT NULL`,[input.userId]);const enrollment=result.rows[0];let step:string|null=null;if(enrollment)step=verifyTotp(decryptMfaSecret(enrollment.encrypted_secret),input.code);if(!step){const consumed=await client.query(`UPDATE mfa_recovery_codes SET consumed_at=now() WHERE user_id=$1 AND code_hash=$2 AND consumed_at IS NULL RETURNING id`,[input.userId,recoveryHash(input.userId,input.code)]);if(!consumed.rowCount)throw new Error("Invalid or already-used verification code");}
 const previous=await client.query<{totp_step:string|null}>(`SELECT totp_step FROM mfa_step_up_sessions WHERE session_id=$1 AND org_id=$2 FOR UPDATE`,[input.sessionId,input.orgId]);if(isTotpReplay(previous.rows[0]?.totp_step,step))throw new Error("Authenticator code was already used");
 await client.query(`INSERT INTO mfa_step_up_sessions(user_id,org_id,session_id,expires_at,totp_step) VALUES($1,$2,$3,now()+interval '12 hours',$4) ON CONFLICT(session_id,org_id) DO UPDATE SET verified_at=now(),expires_at=excluded.expires_at,totp_step=excluded.totp_step`,[input.userId,input.orgId,input.sessionId,step]);if((input.rememberDays??0)<=0)return{};
 const token=randomBytes(32).toString("base64url");await client.query(`INSERT INTO remembered_mfa_devices(user_id,token_hash,label,expires_at) VALUES($1,$2,$3,now()+($4||' days')::interval)`,[input.userId,createHash("sha256").update(token).digest("hex"),"Remembered browser",input.rememberDays]);return{rememberToken:token};}
export async function revokeMfa(client:PoolClient,userId:string){await client.query(`DELETE FROM user_mfa_enrollments WHERE user_id=$1`,[userId]);await client.query(`UPDATE remembered_mfa_devices SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL`,[userId]);await client.query(`DELETE FROM mfa_step_up_sessions WHERE user_id=$1`,[userId]);}
export async function assertOrgAuthentication(client:PoolClient,input:{userId:string;orgId:string;sessionId:string;authMethod:string;rememberedDeviceToken?:string|null}){
 const policyResult=await client.query<OrgAuthPolicy>(`SELECT allow_password AS "allowPassword",allow_google AS "allowGoogle",allow_email_otp AS "allowEmailOtp",mfa_policy AS "mfaPolicy",remembered_device_days AS "rememberedDeviceDays" FROM org_auth_policies WHERE org_id=$1`,[input.orgId]);const policy=policyResult.rows[0]??DEFAULT_ORG_AUTH_POLICY;
 const enrolled=Boolean((await client.query(`SELECT 1 FROM user_mfa_enrollments WHERE user_id=$1 AND confirmed_at IS NOT NULL`,[input.userId])).rowCount);let stepped=Boolean((await client.query(`SELECT 1 FROM mfa_step_up_sessions WHERE user_id=$1 AND session_id=$2 AND org_id=$3 AND expires_at>now()`,[input.userId,input.sessionId,input.orgId])).rowCount);
 if(!stepped&&input.rememberedDeviceToken){const hash=createHash("sha256").update(input.rememberedDeviceToken).digest("hex");const remembered=await client.query(`UPDATE remembered_mfa_devices SET last_used_at=now() WHERE user_id=$1 AND token_hash=$2 AND revoked_at IS NULL AND expires_at>now() RETURNING id`,[input.userId,hash]);stepped=Boolean(remembered.rowCount);}
 const result=evaluateOrgAuthAccess(policy,input.authMethod as SignInMethod,enrolled,stepped);if(!result.allowed){const messages={sign_in_method_not_allowed:"Re-authenticate with a sign-in method allowed by this organization.",mfa_enrollment_required:"This organization requires authenticator-app 2FA enrollment.",mfa_step_up_required:"Authenticator verification is required to enter this organization."};const reason=result.reason??"sign_in_method_not_allowed";const error=new Error(messages[reason]);(error as Error&{code?:string}).code=reason;throw error;}return{policy,mfaVerified:stepped};
}
export async function assertPlatformPrivilegeMfa(client:PoolClient,input:{userId:string;sessionId:string}){const enrolled=await client.query(`SELECT 1 FROM user_mfa_enrollments WHERE user_id=$1 AND confirmed_at IS NOT NULL`,[input.userId]);if(!enrolled.rowCount)return{bootstrap:true};const stepped=await client.query(`SELECT 1 FROM mfa_step_up_sessions WHERE user_id=$1 AND session_id=$2 AND expires_at>now() ORDER BY verified_at DESC LIMIT 1`,[input.userId,input.sessionId]);if(!stepped.rowCount)throw new Error("Authenticator step-up is required for this privileged action");return{bootstrap:false};}
