import { createHash,randomBytes } from "node:crypto";
import type { PoolClient } from "@neondatabase/serverless";
import { AIOrchestrator,type ChatAdapter,type ContextSource } from "@vantage/agent";
import { VERIFY_CAD_OPERATIONS } from "./agent-policy";
import type { CadExecutionResult } from "./fusion-relay";
export * from "./fusion-relay";
export {
  CAD_AGENT_SYSTEM_PROMPT,
  DESTRUCTIVE_CAD_OPERATIONS,
  VERIFY_CAD_OPERATIONS,
  sanitizeUntrustedCadText,
  isAllowlistedCadOperation,
  requiresDestructiveConfirmation,
  canAutoRunWithinAllowlist,
  buildDefaultCadPlan,
  describeCadBrainMode,
  cadenceAgentPlanningPrompt,
} from "./agent-policy";
export type { CadBrainMode, CadSetupTarget, EngineeringBriefLite } from "./agent-policy";
export * from "./mock-fusion-plugin";
export * from "./agent-loop";
export * from "./onshape";
export * from "./compatibility";

export type EngineeringBrief={summary:string;requirements:string[];constraints:string[];scoringTasks:string[];assumptions:Array<{name:string;value:string;needsConfirmation:boolean}>;risks:string[];acceptanceCriteria:string[];sourceRefs:Array<{type:string;id:string;classification:string}>;disclaimer:string};
export const CAD_OPERATIONS=["create_sketch","create_extrude","create_fillet","create_chamfer","create_shell","create_pattern","set_variable","create_assembly","feature_script","verify_topology","render_views","create_checkpoint","rollback_checkpoint","export_step","export_stl","export_gltf"] as const;
export type CadOperation=typeof CAD_OPERATIONS[number];
export type CadAction={operation:CadOperation;parameters:Record<string,unknown>;requiresApproval:boolean;reason:string};
export type { CadExecutionResult };
export interface CadAdapter{readonly platform:"onshape"|"fusion360"|"mock";readonly executionMode:"hosted"|"local";execute(action:CadAction,context:{jobId:string;idempotencyKey:string;documentRef?:Record<string,unknown>}):Promise<CadExecutionResult>;rollback(checkpointRef:string):Promise<void>;}
export interface OnshapeTransport{mutate(input:{operation:CadOperation;parameters:Record<string,unknown>;idempotencyKey:string}):Promise<{featureId?:string;exportArtifact?:{type:string;title:string;provenance:Record<string,unknown>;previewText?:string};explain?:Record<string,unknown>}>;describe():Promise<{fingerprint:string;summary:Record<string,unknown>;render:string;checkpointRef:string}>;rollback(checkpointRef:string):Promise<void>;}
export class OnshapeHostedCadAdapter implements CadAdapter{readonly platform="onshape";readonly executionMode="hosted";constructor(private readonly transport:OnshapeTransport){}async execute(action:CadAction,context:{idempotencyKey:string}){const mutation=await this.transport.mutate({operation:action.operation,parameters:action.parameters,idempotencyKey:context.idempotencyKey}),verified=await this.transport.describe();return{externalFeatureId:mutation.featureId,output:{operation:action.operation,...(mutation.exportArtifact?{exportArtifact:mutation.exportArtifact}:{}),...(mutation.explain?{studentExplain:mutation.explain}:{})},topology:{fingerprint:verified.fingerprint,summary:verified.summary},render:{mimeType:"image/svg+xml",content:verified.render},checkpointRef:verified.checkpointRef};}rollback(checkpointRef:string){return this.transport.rollback(checkpointRef);}}
export class DeterministicMockCadAdapter implements CadAdapter{readonly platform="mock";readonly executionMode="hosted";private version=0;async execute(action:CadAction,context:{jobId:string;idempotencyKey:string}){this.version++;const fingerprint=createHash("sha256").update(`${context.jobId}:${this.version}:${action.operation}:${JSON.stringify(action.parameters)}`).digest("hex");return{externalFeatureId:`mock-feature-${this.version}`,output:{operation:action.operation,deterministic:true},topology:{fingerprint,summary:{bodies:1,features:this.version,validation:"mock-pass"}},render:{mimeType:"image/svg+xml",content:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 450"><rect width="800" height="450" fill="#0b1115"/><path d="M180 320 L400 90 L620 320 Z" fill="none" stroke="#16d9e8" stroke-width="12"/><text x="30" y="420" fill="#dce5e8">Checkpoint ${this.version} · ${action.operation}</text></svg>`},checkpointRef:`mock-checkpoint-${this.version}`};}async rollback(){this.version=Math.max(0,this.version-1);}}
class BriefAdapter implements ChatAdapter{readonly provider="local";readonly model="vantage-cad-brief-v1";constructor(private readonly brief:EngineeringBrief){}async complete(){const text=JSON.stringify(this.brief);return{text,promptTokens:Math.ceil(text.length/4),completionTokens:Math.ceil(text.length/4),costUsd:0};}}
function briefFrom(input:{request:string;sources:ContextSource[]}):EngineeringBrief{return{summary:input.request.trim(),requirements:["Translate the confirmed scoring objective into a serviceable mechanism","Preserve access for inspection and repair"],constraints:["Use only dimensions and weight values confirmed by the user","Stay within configured manufacturing and API complexity limits"],scoringTasks:["User-selected game task from the strategy context"],assumptions:[{name:"Envelope dimensions",value:"Not yet confirmed",needsConfirmation:true},{name:"Weight budget",value:"Not yet confirmed",needsConfirmation:true},{name:"Manufacturing process",value:"Not yet confirmed",needsConfirmation:true}],risks:["Clearance and collision require geometry verification","Loads, fasteners, wire routing, and unsupported cantilevers require human engineering review"],acceptanceCriteria:["User confirms requirements and assumptions before mutation","Every mutation produces topology and render verification","Design review checklist is reviewed by a human"],sourceRefs:input.sources.map(source=>({type:source.type,id:source.id,classification:source.classification})),disclaimer:"AI-generated design review suggestions are not engineering or safety certification."};}
export function validateCadPlan(actions:CadAction[]){
  if(actions.length>50)throw new Error("CAD action plan exceeds the 50-step complexity limit");
  for(const action of actions){
    if(!CAD_OPERATIONS.includes(action.operation))throw new Error(`CAD operation is not allowlisted: ${action.operation}`);
    if(action.operation==="feature_script"&&String(action.parameters.source??"").length>20_000)throw new Error("FeatureScript exceeds the complexity limit");
    if(action.operation.startsWith("export_")||VERIFY_CAD_OPERATIONS.has(action.operation))continue;
    if(!action.requiresApproval)throw new Error(`Geometry mutation requires approval: ${action.operation}`);
  }
}
export class CadRepository{
 constructor(private readonly client:PoolClient){}
 async createBriefJob(input:{orgId:string;userId:string;threadId?:string;requestId:string;title:string;request:string;sources:ContextSource[];platform?:"onshape"|"fusion360"|"mock";executionMode?:"hosted"|"local"}){
  const brief=briefFrom({request:input.request,sources:input.sources}),orchestrated=await new AIOrchestrator(this.client).run({orgId:input.orgId,userId:input.userId,threadId:input.threadId,requestId:input.requestId,capability:"cad",privacyScope:"team",message:input.request,adapter:new BriefAdapter(brief),contextSources:input.sources});
  const parsed=JSON.parse(orchestrated.text) as EngineeringBrief;const result=await this.client.query<{id:string}>(`INSERT INTO cad_jobs(org_id,created_by,thread_id,execution_mode,platform,title,brief,status) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,'awaiting_brief_confirmation') RETURNING id`,[input.orgId,input.userId,input.threadId??null,input.executionMode??"hosted",input.platform??"mock",input.title,JSON.stringify(parsed)]);const jobId=result.rows[0]!.id;
  const aiArtifact=await new AIOrchestrator(this.client).createArtifact({runId:orchestrated.runId,orgId:input.orgId,userId:input.userId,threadId:input.threadId,kind:"cad_brief",title:input.title,content:parsed as unknown as Record<string,unknown>,claims:parsed.sourceRefs.map(ref=>({claim:`Source used: ${ref.id}`,classification:ref.classification==="hard_metric"?"hard_metric":ref.classification==="scout_observation"?"scout_observation":ref.classification==="researched_claim"?"researched_claim":"model_inference",sourceIds:[ref.id]}))});
  const checksum=createHash("sha256").update(JSON.stringify(parsed)).digest("hex");await this.client.query(`INSERT INTO cad_artifacts(org_id,job_id,type,title,content,checksum,source_refs,created_by) VALUES($1,$2,'engineering_brief',$3,$4::jsonb,$5,$6::jsonb,$7)`,[input.orgId,jobId,input.title,JSON.stringify({...parsed,aiArtifactId:aiArtifact.id}),checksum,JSON.stringify(parsed.sourceRefs),input.userId]);await this.audit(input.orgId,jobId,input.userId,"cad.brief.created",{aiRunId:orchestrated.runId,aiArtifactId:aiArtifact.id});return{jobId,brief:parsed,aiRunId:orchestrated.runId};
 }
 async confirmBrief(orgId:string,jobId:string,userId:string,brief:EngineeringBrief){const result=await this.client.query(`UPDATE cad_jobs SET brief=$4::jsonb,brief_confirmed_at=now(),status='planning',updated_at=now() WHERE id=$1 AND org_id=$2 AND created_by=$3 RETURNING id`,[jobId,orgId,userId,JSON.stringify(brief)]);if(!result.rowCount)throw new Error("CAD job is unavailable");await this.audit(orgId,jobId,userId,"cad.brief.confirmed",{});}
 async savePlan(orgId:string,jobId:string,userId:string,actions:CadAction[]){validateCadPlan(actions);await this.client.query("DELETE FROM cad_job_steps WHERE job_id=$1 AND org_id=$2 AND status='planned'",[jobId,orgId]);for(const[index,action]of actions.entries())await this.client.query(`INSERT INTO cad_job_steps(org_id,job_id,sequence,operation,idempotency_key,parameters,requires_approval,approval_status) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8)`,[orgId,jobId,index+1,action.operation,`${jobId}:${index+1}:${createHash("sha256").update(JSON.stringify(action)).digest("hex").slice(0,16)}`,JSON.stringify({...action.parameters,reason:action.reason}),action.requiresApproval,action.requiresApproval?"pending":"approved"]);await this.client.query(`UPDATE cad_jobs SET action_plan=$3::jsonb,status='awaiting_action_approval',updated_at=now() WHERE id=$1 AND org_id=$2 AND brief_confirmed_at IS NOT NULL`,[jobId,orgId,JSON.stringify(actions)]);await this.audit(orgId,jobId,userId,"cad.plan.saved",{steps:actions.length});}
 async approveStep(orgId:string,jobId:string,stepId:string,userId:string,approved:boolean){const result=await this.client.query(`UPDATE cad_job_steps SET approval_status=$5,approved_by=$4,approved_at=now() WHERE id=$1 AND job_id=$2 AND org_id=$3 AND status='planned' RETURNING operation`,[stepId,jobId,orgId,userId,approved?"approved":"rejected"]);if(!result.rowCount)throw new Error("CAD step is unavailable");await this.audit(orgId,jobId,userId,approved?"cad.step.approved":"cad.step.rejected",{stepId});}
 async executeStep(orgId:string,jobId:string,stepId:string,userId:string,adapter:CadAdapter){const row=(await this.client.query<{operation:CadOperation;parameters:Record<string,unknown>;idempotency_key:string;approval_status:string;brief_confirmed_at:Date|null;document_ref:Record<string,unknown>|null}>(`SELECT s.operation,s.parameters,s.idempotency_key,s.approval_status,j.brief_confirmed_at,j.document_ref FROM cad_job_steps s JOIN cad_jobs j ON j.id=s.job_id AND j.org_id=s.org_id WHERE s.id=$1 AND s.job_id=$2 AND s.org_id=$3 FOR UPDATE`,[stepId,jobId,orgId])).rows[0];if(!row||!row.brief_confirmed_at)throw new Error("Confirm the engineering brief before geometry mutation");if(row.approval_status!=="approved")throw new Error("Approve this CAD action before execution");if(!CAD_OPERATIONS.includes(row.operation))throw new Error("CAD operation is not allowlisted");
  await this.client.query(`UPDATE cad_job_steps SET status='running',started_at=now(),progress=10 WHERE id=$1`,[stepId]);const result=await adapter.execute({operation:row.operation,parameters:row.parameters,requiresApproval:true,reason:String(row.parameters.reason??"Approved action")},{jobId,idempotencyKey:row.idempotency_key,documentRef:row.document_ref??undefined});const exportArtifact=result.output.exportArtifact as{type?:string;title?:string;provenance?:Record<string,unknown>;previewText?:string}|undefined;const isExport=row.operation.startsWith("export_")&&exportArtifact?.provenance;const artifactType=isExport?String(exportArtifact!.type??`cad_${row.operation}`):"render_checkpoint";const artifactTitle=isExport?String(exportArtifact!.title??`Export: ${row.operation}`):`Checkpoint: ${row.operation}`;const artifactContent=isExport?{provenance:exportArtifact!.provenance,previewText:exportArtifact!.previewText??null,topology:result.topology,render:result.render}:{...result.render};const checksum=createHash("sha256").update(JSON.stringify(artifactContent)).digest("hex");const sourceRefs=row.document_ref?[{type:"onshape_document",id:String((row.document_ref as{documentId?:string}).documentId??"")},{type:"onshape_element",id:String((row.document_ref as{elementId?:string}).elementId??"")}]:[];const artifact=await this.client.query<{id:string}>(`INSERT INTO cad_artifacts(org_id,job_id,step_id,type,title,content,checksum,source_refs,created_by) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$8::jsonb,$9) RETURNING id`,[orgId,jobId,stepId,artifactType,artifactTitle,JSON.stringify(artifactContent),checksum,JSON.stringify(sourceRefs),userId]);const checkpoint=await this.client.query<{id:string}>(`INSERT INTO cad_checkpoints(org_id,job_id,step_id,external_version_ref,topology_fingerprint,topology,render_artifact_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7) RETURNING id`,[orgId,jobId,stepId,result.checkpointRef,result.topology.fingerprint,JSON.stringify(result.topology.summary),artifact.rows[0]!.id]);await this.client.query(`UPDATE cad_job_steps SET status='completed',progress=100,output=$2::jsonb,completed_at=now() WHERE id=$1`,[stepId,JSON.stringify(result.output)]);await this.client.query(`UPDATE cad_jobs SET current_checkpoint_id=$2,status='running',updated_at=now() WHERE id=$1`,[jobId,checkpoint.rows[0]!.id]);await this.audit(orgId,jobId,userId,"cad.step.executed",{stepId,operation:row.operation,checkpointId:checkpoint.rows[0]!.id,artifactType});return{...result,artifactId:artifact.rows[0]!.id,checkpointId:checkpoint.rows[0]!.id};}
 async detectHumanEdit(orgId:string,jobId:string,currentFingerprint:string){const row=(await this.client.query<{id:string;topology_fingerprint:string}>(`SELECT id,topology_fingerprint FROM cad_checkpoints WHERE job_id=$1 AND org_id=$2 ORDER BY created_at DESC LIMIT 1`,[jobId,orgId])).rows[0];if(!row)return false;const changed=row.topology_fingerprint!==currentFingerprint;if(changed)await this.client.query(`UPDATE cad_checkpoints SET human_edit_detected=true WHERE id=$1`,[row.id]);return changed;}
 private async audit(orgId:string,jobId:string,userId:string,action:string,payload:Record<string,unknown>){await this.client.query(`INSERT INTO cad_audit_events(org_id,job_id,actor_user_id,action,payload) VALUES($1,$2,$3,$4,$5::jsonb)`,[orgId,jobId,userId,action,JSON.stringify(payload)]);}
}
export function createLeaseToken(){const token=randomBytes(32).toString("base64url");return{token,hash:createHash("sha256").update(token).digest("hex")};}
