/**
 * Robot-code constants from the shooter lookup table.
 *
 * The file a team pastes into WPILib is a literal dump of `shooter_points` rows.
 * Interpolation belongs on the field lookup, not in this download — a missing RPM
 * stays missing, and an empty table stays empty. Inventing 3000 RPM so the array
 * "looks complete" would flash a number nobody measured.
 */

export const SHOOTER_EXPORT_LANGUAGES = ["java", "cpp", "python"] as const;
export type ShooterExportLanguage = (typeof SHOOTER_EXPORT_LANGUAGES)[number];

export type LoggedShooterRow = {
  distanceFt: number;
  rpm: number | null;
  hoodAngle: number | null;
  tableName?: string | null;
};

export type ShooterExportInput = {
  seasonYear: number;
  language: ShooterExportLanguage;
  tableName?: string | null;
};

export type LoggedMeasure = { distanceFt: number; value: number; tableName: string };

const DEFAULT_TABLE = "Shooter";

function isLoggedMeasure(value: number | null | undefined): value is number {
  return value != null && Number.isFinite(value) && value >= 0;
}

function tableOf(row: LoggedShooterRow): string {
  const name = row.tableName?.trim();
  return name ? name : DEFAULT_TABLE;
}

/**
 * Print a stored measurement as-is. Distance is numeric(6,2) and RPM is numeric(7,1)
 * in the table; we do not round those to a "nice" flywheel number.
 */
export function formatLoggedNumber(value: number): string {
  if (!Number.isFinite(value)) throw new Error("logged value must be finite");
  return String(value);
}

function byDistanceThenTable(a: LoggedMeasure, b: LoggedMeasure): number {
  if (a.distanceFt !== b.distanceFt) return a.distanceFt - b.distanceFt;
  return a.tableName.localeCompare(b.tableName);
}

/** Flywheel rows that actually have a logged RPM. Hood-only shots are excluded. */
export function loggedRpmRows(rows: readonly LoggedShooterRow[]): LoggedMeasure[] {
  return rows
    .filter((row) => Number.isFinite(row.distanceFt) && row.distanceFt > 0 && isLoggedMeasure(row.rpm))
    .map((row) => ({ distanceFt: row.distanceFt, value: row.rpm as number, tableName: tableOf(row) }))
    .sort(byDistanceThenTable);
}

/** Hood rows that actually have a logged angle. RPM-only shots are excluded. */
export function loggedHoodRows(rows: readonly LoggedShooterRow[]): LoggedMeasure[] {
  return rows
    .filter((row) => Number.isFinite(row.distanceFt) && row.distanceFt > 0 && isLoggedMeasure(row.hoodAngle))
    .map((row) => ({ distanceFt: row.distanceFt, value: row.hoodAngle as number, tableName: tableOf(row) }))
    .sort(byDistanceThenTable);
}

export function parseShooterExportLanguage(raw: string | null | undefined): ShooterExportLanguage {
  const key = (raw ?? "java").trim().toLowerCase();
  if (key === "c++" || key === "h" || key === "hpp") return "cpp";
  if (key === "py") return "python";
  if ((SHOOTER_EXPORT_LANGUAGES as readonly string[]).includes(key)) return key as ShooterExportLanguage;
  throw new Error("lang must be java, cpp, or python");
}

export function shooterExportFileName(input: { language: ShooterExportLanguage; seasonYear: number }): string {
  switch (input.language) {
    case "java":
      return `ShooterTable${input.seasonYear}.java`;
    case "cpp":
      return `ShooterTable${input.seasonYear}.h`;
    case "python":
      return `shooter_table_${input.seasonYear}.py`;
  }
}

function banner(input: ShooterExportInput, rpmCount: number, hoodCount: number, comment: "//" | "#"): string {
  const table = input.tableName?.trim() ? ` · ${input.tableName.trim()}` : "";
  return [
    `${comment} Generated by Vantage from logged shooter_points only.`,
    `${comment} Season ${input.seasonYear}${table}. ${rpmCount} RPM row${rpmCount === 1 ? "" : "s"}, ${hoodCount} hood row${hoodCount === 1 ? "" : "s"}.`,
    `${comment} This file does not invent RPM or hood angles. Add calibrated shots on /shooter-table.`,
  ].join("\n");
}

function pairLiteral(row: LoggedMeasure): string {
  return `{${formatLoggedNumber(row.distanceFt)}, ${formatLoggedNumber(row.value)}}`;
}

function javaPairs(rows: LoggedMeasure[]): string {
  if (rows.length === 0) return "{}";
  const lines = rows.map((row) => {
    const note = row.tableName !== DEFAULT_TABLE ? ` // ${row.tableName}` : "";
    return `    ${pairLiteral(row)},${note}`;
  });
  return `{\n${lines.join("\n")}\n  }`;
}

function exportJava(rows: readonly LoggedShooterRow[], input: ShooterExportInput): string {
  const rpm = loggedRpmRows(rows);
  const hood = loggedHoodRows(rows);
  return `${banner(input, rpm.length, hood.length, "//")}

public final class ShooterTable {
  private ShooterTable() {}

  /** distanceFt, rpm — logged flywheel rows only. */
  public static final double[][] kRpmByDistanceFt = ${javaPairs(rpm)};

  /** distanceFt, hoodDeg — logged hood rows only. */
  public static final double[][] kHoodDegByDistanceFt = ${javaPairs(hood)};
}
`;
}

function cppArrays(
  names: { count: string; distances: string; values: string },
  rows: LoggedMeasure[],
): string {
  if (rows.length === 0) return `inline constexpr int ${names.count} = 0;`;
  const distances = rows.map((row) => formatLoggedNumber(row.distanceFt)).join(", ");
  const values = rows.map((row) => formatLoggedNumber(row.value)).join(", ");
  return [
    `inline constexpr int ${names.count} = ${rows.length};`,
    `inline constexpr double ${names.distances}[${names.count}] = {${distances}};`,
    `inline constexpr double ${names.values}[${names.count}] = {${values}};`,
  ].join("\n");
}

function exportCpp(rows: readonly LoggedShooterRow[], input: ShooterExportInput): string {
  const rpm = loggedRpmRows(rows);
  const hood = loggedHoodRows(rows);
  return `${banner(input, rpm.length, hood.length, "//")}
#pragma once

namespace ShooterTable {
${cppArrays({ count: "kRpmCount", distances: "kRpmDistancesFt", values: "kRpm" }, rpm)}
${cppArrays({ count: "kHoodCount", distances: "kHoodDistancesFt", values: "kHoodDeg" }, hood)}
}
`;
}

function pythonTuples(rows: LoggedMeasure[]): string {
  if (rows.length === 0) return "()";
  const lines = rows.map((row) => {
    const note = row.tableName !== DEFAULT_TABLE ? `  # ${row.tableName}` : "";
    return `    (${formatLoggedNumber(row.distanceFt)}, ${formatLoggedNumber(row.value)}),${note}`;
  });
  return `(\n${lines.join("\n")}\n)`;
}

function exportPython(rows: readonly LoggedShooterRow[], input: ShooterExportInput): string {
  const rpm = loggedRpmRows(rows);
  const hood = loggedHoodRows(rows);
  return `${banner(input, rpm.length, hood.length, "#")}

# (distance_ft, rpm) — logged flywheel rows only.
k_rpm_by_distance_ft = ${pythonTuples(rpm)}

# (distance_ft, hood_deg) — logged hood rows only.
k_hood_deg_by_distance_ft = ${pythonTuples(hood)}
`;
}

/**
 * Robot-code source for the given language. Empty input yields empty constant
 * tables — never a sample flywheel RPM.
 */
export function exportShooterConstants(
  rows: readonly LoggedShooterRow[],
  input: ShooterExportInput,
): string {
  switch (input.language) {
    case "java":
      return exportJava(rows, input);
    case "cpp":
      return exportCpp(rows, input);
    case "python":
      return exportPython(rows, input);
  }
}
