"use client";

import { useEffect, useState, type FormEvent } from "react";

type Storefront = { orgName: string; teamNumber: number | null; pitch: string | null; paymentUrl: string | null; packages: Array<{ id: string; name: string; priceCents: number; durationDays: number; surfaces: string[]; benefits: string | null }> };
const labels: Record<string, string> = { business_wall: "business portal", dashboard_footer: "team dashboard", pit_footer: "pit command" };

export default function StorefrontClient({ publicId }: { publicId: string }) {
  const [store, setStore] = useState<Storefront | null>(null); const [selected, setSelected] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { void fetch(`/api/support/${encodeURIComponent(publicId)}`).then(async (response) => { const data = await response.json() as Storefront | { error?: string }; if (!response.ok || !("packages" in data)) throw new Error("error" in data ? data.error : "Support page unavailable"); setStore(data); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Support page unavailable")); }, [publicId]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); setMessage(""); try { const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch(`/api/support/${encodeURIComponent(publicId)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...values, packageId: selected }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? "Could not send inquiry"); setMessage("Thanks — your inquiry is in the team’s private review queue. A team leader will follow up directly."); event.currentTarget.reset(); setSelected(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not send inquiry"); } finally { setBusy(false); } };
  if (error && !store) return <main className="support-page"><section className="support-card"><p className="support-eyebrow">Team support</p><h1>That support page is unavailable.</h1><p>{error}</p></section></main>;
  if (!store) return <main className="support-page"><section className="support-card"><p>Loading team partnership opportunities…</p></section></main>;
  return <main className="support-page"><section className="support-hero"><p className="support-eyebrow">Partner with {store.teamNumber ? `FRC Team ${store.teamNumber}` : store.orgName}</p><h1>Build the next generation of problem-solvers.</h1><p>{store.pitch || "Your support helps students design, build, lead, and compete."}</p>{store.paymentUrl ? <a href={store.paymentUrl} target="_blank" rel="noopener noreferrer" className="support-payment">Make a direct team contribution ↗</a> : null}</section><section className="support-card"><header><p className="support-eyebrow">Recognition packages</p><h2>Choose how you want to show up.</h2></header><div className="support-packages">{store.packages.map((item) => <button type="button" key={item.id} className={selected === item.id ? "selected" : ""} onClick={() => setSelected(item.id)}><strong>{item.name}</strong><b>${(item.priceCents / 100).toLocaleString()}</b><span>{item.durationDays} days · {item.surfaces.map((surface) => labels[surface] ?? surface).join(", ")}</span><small>{item.benefits || "Custom recognition with student impact updates."}</small></button>)}{!store.packages.length ? <p>Contact the team to explore a custom partnership.</p> : null}</div></section><section className="support-card"><p className="support-eyebrow">Start a conversation</p><h2>The team reviews every inquiry before anything is published.</h2>{message ? <p className="support-success">{message}</p> : null}{error ? <p className="support-error">{error}</p> : null}<form className="support-form" onSubmit={(event) => void submit(event)}><input name="websiteField" tabIndex={-1} autoComplete="off" className="support-honeypot" aria-hidden="true" /><label>Company <input name="companyName" required /></label><label>Your name <input name="contactName" required /></label><label>Email <input name="contactEmail" type="email" required /></label><label>Website <input name="website" type="url" placeholder="https://" /></label><label>Suggested recognition line <input name="headline" maxLength={240} placeholder="Proudly supporting student innovation" /></label><label>Logo link (optional) <input name="logoUrl" type="url" placeholder="https://" /><small>This stays private until the team processes an approved upload.</small></label><label className="wide">What kind of partnership are you considering? <textarea name="message" rows={4} /></label><button disabled={busy}>{busy ? "Sending…" : "Send private inquiry"}</button></form></section><p className="support-note">Payments are made directly to the team. Sponsor records and artwork are reviewed by team leadership before any recognition appears in Vantage.</p></main>;
}
