"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
type Data = { organization:{name:string;teamNumber:number|null;role:string};context:{eventKey:string|null;eventName:string|null};nextMatch:{matchKey:string;compLevel:string;matchNumber:number;scheduledTime:string|null}|null;gate:{state:"go"|"check"|"hold";reasons:string[]};summary:{openIssues:number;overdueMaintenance:number;readyBatteries:number;activeBatteries:number};issues:Array<{id:string;subsystem:string;severity:string;symptoms:string;occurredAt:string;matchKey:string|null;canResolve:boolean}>;maintenance:Array<{id:string;subsystem:string;task:string;dueAt:string|null}>;batteries:Array<{id:string;assetTag:string;status:"active"|"service"|"retired";measuredAt:string|null;voltage:number|null;resistanceMilliohms:number|null;gate:"ready"|"review"|"unread"}>;rules:{battery:string;hold:string};updatedAt:string;};
type Form = {kind:"battery"|"issue"|"maintenance"|"resolve";id?:string}|null;
const subsystems=["Drivetrain","Game piece mechanism","Electrical","Controls","Pneumatics","Structure","Bumpers","Other"];
const ago=(value:string|null)=>{if(!value)return"No reading";const m=Math.round((Date.now()-new Date(value).getTime())/60000);return m<1?"just now":m<60?`${m}m ago`:m<2160?`${Math.round(m/60)}h ago`:new Date(value).toLocaleDateString();};
const due=(value:string|null)=>{if(!value)return"No deadline";const d=new Date(value);return`${d.getTime()<Date.now()?"Overdue · ":"Due "}${d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}`;};
const match=(value:Data["nextMatch"])=>!value?"No upcoming match":value.compLevel==="qm"?`Qualification ${value.matchNumber}`:`${value.compLevel.toUpperCase()} ${value.matchNumber}`;
const countdown=(value:string|null|undefined,now:number)=>{if(!value)return"Time pending";const s=Math.round((new Date(value).getTime()-now)/1000);if(s<=0)return"Queue now";const m=Math.floor(s/60);return m>=60?`${Math.floor(m/60)}h ${m%60}m`:`${m}m ${s%60}s`;};
export default function PitCommandClient({orgId}:{orgId:string}){
  const[data,setData]=useState<Data|null>(null),[form,setForm]=useState<Form>(null),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[now,setNow]=useState(Date.now()),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{try{const r=await fetch(`/api/pit?orgId=${encodeURIComponent(orgId)}`,{cache:"no-store"});const b=await r.json() as Data|{error?:string};if(!r.ok||!("gate" in b))throw new Error("error" in b?b.error:"Could not load Pit Command");setData(b);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load Pit Command");}finally{setLoading(false);}},[orgId]);
  useEffect(()=>{void load();const poll=window.setInterval(()=>void load(),30000),clock=window.setInterval(()=>setNow(Date.now()),1000);return()=>{clearInterval(poll);clearInterval(clock);};},[load]);
  async function mutate(payload:Record<string,unknown>,success:string,key=String(payload.action)){setBusy(key);setError("");try{const r=await fetch("/api/pit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...payload,orgId})});const b=await r.json() as{error?:string};if(!r.ok)throw new Error(b.error??"Pit action failed");setMessage(success);setForm(null);await load();}catch(e){setError(e instanceof Error?e.message:"Pit action failed");}finally{setBusy("");}}
  function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!form)return;const values=Object.fromEntries(new FormData(e.currentTarget));if(form.kind==="battery")void mutate({action:"log_battery",...values},"Battery reading logged.","form");else if(form.kind==="issue")void mutate({action:"report_issue",matchKey:data?.nextMatch?.matchKey??"",...values},"Issue added to the board.","form");else if(form.kind==="maintenance")void mutate({action:"add_maintenance",...values},"Maintenance item added.","form");else void mutate({action:"resolve_issue",id:form.id,...values},"Issue resolved and gate recalculated.","form");}
  const rack=useMemo(()=>data?.batteries.filter(b=>b.status!=="retired")??[],[data]);
  if(loading&&!data)return <main className="pit-page pit-loading"><span className="app-badge setup">PIT COMMAND</span><h1>Building the release board…</h1><p>Checking issues, maintenance, batteries, and your next match.</p></main>;
  if(!data)return <main className="pit-page pit-loading"><h1>Pit board unavailable</h1><p role="alert">{error}</p><button className="app-button" onClick={()=>void load()}>Try again</button></main>;
  return <main className="pit-page">
    <header className="pit-header"><div><span className="breadcrumbs">Competition / Pit Command · Team {data.organization.teamNumber??"—"}</span><h1>Robot release board</h1><p>{data.context.eventName??"No active event"} · explicit evidence, no invented percentage</p></div><div className="pit-next"><span>NEXT MATCH</span><strong>{match(data.nextMatch)}</strong><b>{countdown(data.nextMatch?.scheduledTime,now)}</b></div></header>
    {error?<p className="telemetry-status" role="alert">{error}</p>:null}{message?<p className="telemetry-status success" role="status">{message}</p>:null}
    <section className={`pit-gate ${data.gate.state}`}><div className="pit-gate-state"><span>RELEASE GATE</span><strong>{data.gate.state.toUpperCase()}</strong><small>{data.gate.state==="go"?"Evidence clear":data.gate.state==="hold"?"Do not release":"Crew review needed"}</small></div><div className="pit-reasons"><span>WHY</span><ul>{data.gate.reasons.map(r=><li key={r}>{r}</li>)}</ul></div><dl><div><dt>Issues</dt><dd>{data.summary.openIssues}</dd></div><div><dt>Overdue</dt><dd>{data.summary.overdueMaintenance}</dd></div><div><dt>Batteries</dt><dd>{data.summary.readyBatteries}/{data.summary.activeBatteries}</dd></div></dl></section>
    <section className="pit-actions"><button onClick={()=>setForm({kind:"battery"})}><span>01</span><strong>Log battery</strong><small>Voltage + resistance</small></button><button onClick={()=>setForm({kind:"issue"})}><span>02</span><strong>Report issue</strong><small>Put it on the board</small></button><button onClick={()=>setForm({kind:"maintenance"})}><span>03</span><strong>Add work</strong><small>Task + due time</small></button><button onClick={()=>void load()}><span>↻</span><strong>Refresh gate</strong><small>Recheck now</small></button></section>
    {form?<section className="pit-capture"><header><div><span>FAST CAPTURE</span><h2>{form.kind==="battery"?"Battery check":form.kind==="issue"?"Report robot issue":form.kind==="maintenance"?"Add maintenance":"Close issue"}</h2></div><button type="button" aria-label="Close" onClick={()=>setForm(null)}>×</button></header><form onSubmit={submit}>
      {form.kind==="battery"?<><label>Battery tag<input name="assetTag" autoFocus required placeholder="COMP-04"/></label><label>Voltage<input name="voltage" type="number" step=".01" min="0" max="20" placeholder="12.74"/></label><label>Resistance (mΩ)<input name="resistanceMilliohms" type="number" step=".1" min="0" max="100" placeholder="18.2"/></label><label>Charger cycles<input name="chargerCycles" type="number" min="0" step="1" placeholder="Optional"/></label></>:null}
      {form.kind==="issue"?<><label>Subsystem<select name="subsystem" autoFocus>{subsystems.map(s=><option key={s}>{s}</option>)}</select></label><label>Severity<select name="severity" defaultValue="degraded"><option value="minor">Minor</option><option value="degraded">Degraded</option><option value="disabled">Robot disabled</option><option value="safety">Safety — hold</option></select></label><label className="wide">What happened?<textarea name="symptoms" required rows={3} maxLength={2000}/></label></>:null}
      {form.kind==="maintenance"?<><label>Subsystem<select name="subsystem" autoFocus>{subsystems.map(s=><option key={s}>{s}</option>)}</select></label><label>Due time<input name="dueAt" type="datetime-local"/></label><label className="wide">Work item<textarea name="task" required rows={3} maxLength={500}/></label></>:null}
      {form.kind==="resolve"?<label className="wide">Resolution<textarea name="resolution" autoFocus required rows={3} maxLength={2000} placeholder="What changed, and how was it verified?"/></label>:null}
      <footer><button type="button" className="app-button secondary" onClick={()=>setForm(null)}>Cancel</button><button className="app-button" disabled={busy==="form"}>{busy==="form"?"Saving…":"Save to pit board"}</button></footer></form></section>:null}
    <section className="pit-grid">
      <article className="pit-card"><header><div><span>ROBOT</span><h2>Open issues</h2></div><b>{data.issues.length}</b></header>{!data.issues.length?<div className="pit-empty"><strong>No open robot issues</strong><span>Report anything the next crew needs to know.</span></div>:<ul className="pit-issues">{data.issues.map(i=><li key={i.id} data-severity={i.severity}><div><em>{i.severity}</em><time>{ago(i.occurredAt)}</time></div><strong>{i.subsystem}</strong><p>{i.symptoms}</p>{i.canResolve?<button onClick={()=>setForm({kind:"resolve",id:i.id})}>Resolve + verify</button>:null}</li>)}</ul>}</article>
      <article className="pit-card"><header><div><span>WORK QUEUE</span><h2>Maintenance</h2></div><b>{data.maintenance.length}</b></header>{!data.maintenance.length?<div className="pit-empty"><strong>Work queue clear</strong><span>Add inspections or between-match repairs here.</span></div>:<ul className="pit-work">{data.maintenance.map(i=><li key={i.id} className={i.dueAt&&new Date(i.dueAt).getTime()<now?"overdue":""}><button disabled={busy===i.id} onClick={()=>void mutate({action:"complete_maintenance",id:i.id},"Maintenance completed.",i.id)}>✓</button><div><span>{i.subsystem}</span><strong>{i.task}</strong><small>{due(i.dueAt)}</small></div></li>)}</ul>}</article>
      <article className="pit-card pit-battery"><header><div><span>POWER</span><h2>Battery rack</h2></div><b>{data.summary.readyBatteries}/{data.summary.activeBatteries}</b></header>{!rack.length?<div className="pit-empty"><strong>No batteries tracked</strong><span>Log a reading to create the first record.</span></div>:<ul>{rack.map(b=><li key={b.id} data-gate={b.gate}><div><strong>{b.assetTag}</strong><small>{b.status}</small></div><div><strong>{b.voltage==null?"—":`${Number(b.voltage).toFixed(2)} V`}</strong><small>{b.resistanceMilliohms==null?"IR —":`${Number(b.resistanceMilliohms).toFixed(1)} mΩ`}</small></div><div><b>{b.gate.toUpperCase()}</b><small>{ago(b.measuredAt)}</small></div><button disabled={busy===b.id} onClick={()=>void mutate({action:"battery_status",id:b.id,status:b.status==="service"?"active":"service"},b.status==="service"?"Battery returned to active rack.":"Battery moved to service.",b.id)}>{b.status==="service"?"Return":"Service"}</button></li>)}</ul>}<footer><strong>READY RANGE</strong><span>{data.rules.battery}</span></footer></article>
    </section><footer className="pit-foot"><span>Last calculated {new Date(data.updatedAt).toLocaleTimeString()}</span><span>Human release decision stays with the pit crew · {data.rules.hold}</span></footer>
  </main>;
}
