import { mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { loadDeviceCredential } from "./secure-store";

/**
 * `vantage-cad agent sync [--dir <repo>] [--agent claude|cursor|all] [--dry-run]`
 *
 * Pulls the team's shared agent configuration (GET /api/agent-config/bundle,
 * authenticated with the same paired device token as every other CLI route).
 * The bundle is scoped server-side to THIS device's user: team-wide items plus
 * items shared with them personally. Sync then materializes it per agent.
 *
 * Claude Code target:
 * - .claude/agents/<name>.md                    one file per subagent
 * - .claude/skills/<name>/SKILL.md              one folder per skill
 * - .claude/vantage-team-rules.md               concatenated team rules
 * - CLAUDE.md                                   an @import line, ONLY between
 *   BEGIN/END VANTAGE markers (idempotent: re-sync replaces the block, never
 *   duplicates, never touches anything outside the markers)
 * - .mcp.json                                   deep-merged; only keys under the
 *   `vantage-` prefix are added/updated/pruned — other servers are never touched
 * - .claude/vantage-permissions.suggested.json  permissions are a security
 *   change, so they are NEVER auto-merged into settings.json; a human applies
 *   the printed suggestion.
 *
 * Cursor target (formats verified 2026-08 against the official docs —
 * https://cursor.com/docs/context/rules, https://cursor.com/docs/context/mcp,
 * https://cursor.com/docs/skills — see apps/web/lib/agent-config/cursor-formats.ts
 * for the full citations):
 * - .cursor/rules/vantage/<name>.mdc            one MDC file per rule
 *   (frontmatter: description / globs / alwaysApply; team rules without path
 *   scopes are alwaysApply: true). Only files inside this managed folder that
 *   carry the generated banner are ever updated or pruned.
 * - .cursor/skills/vantage/<name>/SKILL.md      one folder per skill (Cursor
 *   Agent Skills use the same SKILL.md frontmatter contract)
 * - .cursor/mcp.json                            same mcpServers shape as
 *   .mcp.json; merged with the identical vantage-prefix-only rule
 * - subagents and permissions have no Cursor-native equivalent and are
 *   reported as skipped for the Cursor target (never an invented format).
 *
 * Default targets: whatever is detected in the repo (.claude/ or CLAUDE.md →
 * Claude Code, .cursor/ → Cursor); when nothing is detected, Claude Code —
 * pass --agent to be explicit.
 */

export const VANTAGE_BEGIN_MARKER = "<!-- BEGIN VANTAGE TEAM AGENT CONFIG -->";
export const VANTAGE_END_MARKER = "<!-- END VANTAGE TEAM AGENT CONFIG -->";
export const VANTAGE_MCP_PREFIX = "vantage-";
export const TEAM_RULES_FILE = ".claude/vantage-team-rules.md";
export const PERMISSIONS_SUGGESTION_FILE = ".claude/vantage-permissions.suggested.json";
export const CURSOR_RULES_DIR = ".cursor/rules/vantage";
export const CURSOR_SKILLS_DIR = ".cursor/skills/vantage";
export const CURSOR_MCP_FILE = ".cursor/mcp.json";
/** Marks a file as Vantage-managed: sync only ever prunes files carrying it. */
export const CURSOR_GENERATED_BANNER =
  "<!-- Generated by `vantage-cad agent sync` — edit at /team/agent-config, not here. -->";

export type AgentConfigBundle = {
  schema: string;
  orgId: string;
  generatedAt: string;
  rules: Array<{ name: string; description: string | null; markdown: string; version: number }>;
  subagents: Array<{ name: string; description: string | null; markdown: string; version: number }>;
  mcpServers: Array<{ name: string; description: string | null; entry: Record<string, unknown>; version: number }>;
  permissions: Array<{ name: string; description: string | null; snippet: { allow?: string[]; deny?: string[]; ask?: string[] }; version: number }>;
  skills: Array<{ name: string; description: string | null; markdown: string; version: number }>;
};

const SAFE_NAME = /^[a-z0-9][a-z0-9-]{0,63}$/;

export function safeConfigName(name: string): string | null {
  return SAFE_NAME.test(name) ? name : null;
}

/**
 * Idempotently install `block` between the VANTAGE markers in a CLAUDE.md body.
 * Everything outside the markers is preserved byte-for-byte; a half-present
 * marker pair is an error (never guess at a corrupt file).
 */
export function applyVantageMarkerBlock(existing: string, block: string): string {
  const begin = existing.indexOf(VANTAGE_BEGIN_MARKER);
  const end = existing.indexOf(VANTAGE_END_MARKER);
  const wrapped = `${VANTAGE_BEGIN_MARKER}\n${block.trim()}\n${VANTAGE_END_MARKER}`;
  if (begin === -1 && end === -1) {
    if (!existing) return `${wrapped}\n`;
    return `${existing.replace(/\n*$/, "\n\n")}${wrapped}\n`;
  }
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error(
      `CLAUDE.md has a corrupt VANTAGE marker pair (found ${begin === -1 ? "END without BEGIN" : end === -1 ? "BEGIN without END" : "END before BEGIN"}). Fix or remove the markers, then re-run sync.`,
    );
  }
  const before = existing.slice(0, begin);
  const after = existing.slice(end + VANTAGE_END_MARKER.length);
  return `${before}${wrapped}${after}`;
}

export function buildClaudeMdBlock(): string {
  return [
    "Team agent rules synced from Vantage (/team/agent-config).",
    "Do not edit between these markers — `vantage-cad agent sync` rewrites this block.",
    `@${TEAM_RULES_FILE}`,
  ].join("\n");
}

export type RuleScope = {
  body: string;
  description: string | null;
  globs: string[] | null;
  alwaysApply: boolean | null;
};

/**
 * A rules item MAY start with an optional YAML frontmatter block declaring
 * Cursor scoping metadata (description / globs / alwaysApply — the MDC fields
 * from https://cursor.com/docs/context/rules). Claude Code output uses only
 * the body; the Cursor writer turns the metadata into MDC frontmatter.
 * Mirrors parseRuleScope in apps/web/lib/agent-config/formats.ts (this CLI
 * package intentionally has no dependency on the web app).
 */
export function parseRuleScope(markdown: string): RuleScope {
  const normalized = markdown.replace(/\r\n/g, "\n");
  const none: RuleScope = { body: normalized, description: null, globs: null, alwaysApply: null };
  if (!normalized.startsWith("---\n")) return none;
  const end = normalized.indexOf("\n---", 4);
  if (end === -1) return none;
  const rawFields = normalized.slice(4, end);
  const body = normalized.slice(normalized.indexOf("\n", end + 1) + 1);
  const scope: RuleScope = { body, description: null, globs: null, alwaysApply: null };
  const clean = (value: string) => value.trim().replace(/^["']|["']$/g, "");
  const lines = rawFields.split("\n");
  for (let i = 0; i < lines.length; i += 1) {
    const match = /^([A-Za-z][A-Za-z0-9_-]*):\s*(.*)$/.exec(lines[i]!);
    if (!match) continue;
    const key = match[1]!;
    if (key === "globs" && !match[2]!.trim()) {
      // YAML block list form: globs:\n  - src/**\n  - "**/*.java"
      const list: string[] = [];
      while (i + 1 < lines.length && /^\s+-\s+/.test(lines[i + 1]!)) {
        i += 1;
        list.push(clean(lines[i]!.replace(/^\s+-\s+/, "")));
      }
      scope.globs = list.filter(Boolean).length ? list.filter(Boolean) : null;
      continue;
    }
    const value = clean(match[2]!);
    if (key === "description" && value) scope.description = value;
    else if (key === "globs" && value) {
      // Cursor docs: "Separate multiple patterns with commas."
      const globs = value.split(",").map(clean).filter(Boolean);
      scope.globs = globs.length ? globs : null;
    } else if (key === "alwaysApply") {
      if (value === "true") scope.alwaysApply = true;
      else if (value === "false") scope.alwaysApply = false;
    }
  }
  return scope;
}

export function buildTeamRulesMarkdown(bundle: AgentConfigBundle): string | null {
  const sections = bundle.rules
    // Claude Code gets the rule BODY only — Cursor scoping frontmatter is
    // metadata for .mdc generation, not agent context.
    .map((rule) => ({ name: rule.name, body: parseRuleScope(rule.markdown).body.trim() }))
    .filter((rule) => rule.body)
    .map((rule) => `## ${rule.name}\n\n${rule.body}`);
  if (!sections.length) return null;
  return [
    CURSOR_GENERATED_BANNER,
    "# Team agent rules",
    ...sections,
    "",
  ].join("\n\n");
}

/** YAML double-quoted scalar (JSON string escaping is valid YAML). */
function yamlQuote(value: string): string {
  return JSON.stringify(value);
}

/**
 * One shared rule → one `.cursor/rules/vantage/<name>.mdc` file (MDC format
 * per https://cursor.com/docs/context/rules). Rules without declared globs are
 * team-wide always-on (`alwaysApply: true`); declared globs make the rule
 * Auto Attached; an explicit alwaysApply in the rule's scope frontmatter wins.
 * Cursor docs: "Separate multiple patterns with commas."
 */
export function buildCursorRuleMdc(rule: {
  name: string;
  description: string | null;
  markdown: string;
}): { filename: string; content: string } | null {
  if (!safeConfigName(rule.name)) return null;
  const scope = parseRuleScope(rule.markdown);
  const body = scope.body.trim();
  if (!body) return null;
  const description = scope.description ?? rule.description;
  const alwaysApply = scope.alwaysApply ?? !scope.globs;
  const frontmatter = ["---"];
  if (description) frontmatter.push(`description: ${yamlQuote(description)}`);
  if (scope.globs) frontmatter.push(`globs: ${scope.globs.join(",")}`);
  frontmatter.push(`alwaysApply: ${alwaysApply}`, "---");
  return {
    filename: `${rule.name}.mdc`,
    content: `${frontmatter.join("\n")}\n\n${CURSOR_GENERATED_BANNER}\n\n${body}\n`,
  };
}

/**
 * Cursor requires a skill folder to match the SKILL.md frontmatter `name`
 * ("Must match the parent folder name." — https://cursor.com/docs/skills).
 * Prefer the frontmatter name when filename-safe; fall back to the item name.
 */
export function cursorSkillFolder(markdown: string, itemName: string): string | null {
  const match = /^---\n[\s\S]*?^name:\s*["']?([A-Za-z0-9-]+)["']?\s*$/m.exec(
    markdown.replace(/\r\n/g, "\n"),
  );
  const fromFrontmatter = match?.[1] ?? "";
  if (fromFrontmatter && safeConfigName(fromFrontmatter)) return fromFrontmatter;
  return safeConfigName(itemName);
}

// ---------------------------------------------------------------------------
// Agent targets (--agent claude|cursor|all, default: detected)
// ---------------------------------------------------------------------------

export type AgentTargets = { claude: boolean; cursor: boolean; source: "flag" | "detected" | "default" };

export function parseAgentTargets(
  flag: string | null,
  detected: { claude: boolean; cursor: boolean },
): AgentTargets {
  if (flag) {
    if (flag === "claude") return { claude: true, cursor: false, source: "flag" };
    if (flag === "cursor") return { claude: false, cursor: true, source: "flag" };
    if (flag === "all") return { claude: true, cursor: true, source: "flag" };
    throw new Error(`Unknown --agent value ${JSON.stringify(flag)}. Use claude, cursor, or all.`);
  }
  if (detected.claude || detected.cursor) return { ...detected, source: "detected" };
  // Nothing detected: keep the original behavior (Claude Code) and let the
  // summary point at --agent cursor.
  return { claude: true, cursor: false, source: "default" };
}

export type McpMergeResult = {
  json: string;
  added: string[];
  updated: string[];
  removed: string[];
  unchanged: string[];
};

/**
 * Deep-merge team MCP servers into an existing .mcp.json. Only keys under the
 * `vantage-` namespace are ever written or pruned; every other server and every
 * unknown top-level key survives byte-for-byte (modulo JSON re-serialization).
 */
export function mergeMcpServers(
  existingJson: string | null,
  servers: AgentConfigBundle["mcpServers"],
  label = ".mcp.json",
): McpMergeResult {
  let root: Record<string, unknown> = {};
  if (existingJson && existingJson.trim()) {
    const parsed: unknown = JSON.parse(existingJson);
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error(`${label} exists but is not a JSON object — fix it before syncing`);
    }
    root = parsed as Record<string, unknown>;
  }
  const mcpServers =
    root.mcpServers && typeof root.mcpServers === "object" && !Array.isArray(root.mcpServers)
      ? { ...(root.mcpServers as Record<string, unknown>) }
      : {};

  const wanted = new Map<string, Record<string, unknown>>();
  for (const server of servers) {
    const name = safeConfigName(server.name);
    if (!name) continue;
    wanted.set(`${VANTAGE_MCP_PREFIX}${name}`, server.entry);
  }

  const added: string[] = [];
  const updated: string[] = [];
  const removed: string[] = [];
  const unchanged: string[] = [];

  for (const key of Object.keys(mcpServers)) {
    if (!key.startsWith(VANTAGE_MCP_PREFIX)) continue; // never touch a team's other servers
    if (!wanted.has(key)) {
      delete mcpServers[key];
      removed.push(key);
    }
  }
  for (const [key, entry] of wanted) {
    if (!(key in mcpServers)) {
      mcpServers[key] = entry;
      added.push(key);
    } else if (JSON.stringify(mcpServers[key]) !== JSON.stringify(entry)) {
      mcpServers[key] = entry;
      updated.push(key);
    } else {
      unchanged.push(key);
    }
  }

  const json = `${JSON.stringify({ ...root, mcpServers }, null, 2)}\n`;
  return { json, added, updated, removed, unchanged };
}

export function buildPermissionsSuggestion(bundle: AgentConfigBundle): string | null {
  if (!bundle.permissions.length) return null;
  const allow = new Set<string>();
  const deny = new Set<string>();
  const ask = new Set<string>();
  for (const item of bundle.permissions) {
    for (const rule of item.snippet.allow ?? []) allow.add(rule);
    for (const rule of item.snippet.deny ?? []) deny.add(rule);
    for (const rule of item.snippet.ask ?? []) ask.add(rule);
  }
  const suggestion = {
    note: "Suggested by your team via Vantage (/team/agent-config). Review each rule, then merge it into .claude/settings.json permissions yourself — a wrong permissions merge is a security change, so Vantage never applies it automatically.",
    generatedAt: bundle.generatedAt,
    permissions: {
      ...(allow.size ? { allow: [...allow].sort() } : {}),
      ...(deny.size ? { deny: [...deny].sort() } : {}),
      ...(ask.size ? { ask: [...ask].sort() } : {}),
    },
  };
  return `${JSON.stringify(suggestion, null, 2)}\n`;
}

// ---------------------------------------------------------------------------
// Filesystem plumbing (thin; all decisions above are pure and tested)
// ---------------------------------------------------------------------------

type WriteOutcome = "written" | "updated" | "unchanged" | "dry-run";

async function readIfExists(path: string): Promise<string | null> {
  try {
    return await readFile(path, "utf8");
  } catch {
    return null;
  }
}

async function dirExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isDirectory();
  } catch {
    return false;
  }
}

async function fileExists(path: string): Promise<boolean> {
  try {
    return (await stat(path)).isFile();
  } catch {
    return false;
  }
}

/**
 * Remove stale .mdc files from the managed Cursor rules folder. Only files
 * carrying the generated banner are ever deleted — a user-authored file that
 * strayed into .cursor/rules/vantage/ is left alone and reported.
 */
export async function pruneManagedMdcDir(
  dirPath: string,
  keep: Set<string>,
  dryRun: boolean,
): Promise<{ pruned: string[]; kept: string[] }> {
  const pruned: string[] = [];
  const kept: string[] = [];
  let entries: string[];
  try {
    entries = await readdir(dirPath);
  } catch {
    return { pruned, kept };
  }
  for (const entry of entries) {
    if (!entry.endsWith(".mdc") || keep.has(entry)) continue;
    const fullPath = join(dirPath, entry);
    const content = await readIfExists(fullPath);
    if (content === null || !content.includes(CURSOR_GENERATED_BANNER)) {
      kept.push(entry);
      continue;
    }
    if (!dryRun) await rm(fullPath);
    pruned.push(entry);
  }
  return { pruned, kept };
}

async function writeManaged(
  path: string,
  content: string,
  dryRun: boolean,
): Promise<WriteOutcome> {
  const existing = await readIfExists(path);
  if (existing === content) return "unchanged";
  if (dryRun) return "dry-run";
  await mkdir(join(path, ".."), { recursive: true });
  await writeFile(path, content, "utf8");
  return existing === null ? "written" : "updated";
}

export async function fetchAgentConfigBundle(): Promise<AgentConfigBundle> {
  const credential = await loadDeviceCredential();
  if (!credential) throw new Error("Not paired. Run `vantage-cad setup` first.");
  const base = (credential.baseUrl ?? process.env.VANTAGE_URL ?? "http://localhost:3001").replace(/\/$/, "");
  const response = await fetch(`${base}/api/agent-config/bundle`, {
    headers: { authorization: `Bearer ${credential.deviceToken}` },
  });
  const data = (await response.json()) as Record<string, unknown>;
  if (!response.ok) throw new Error(String(data.error ?? `HTTP ${response.status}`));
  if (data.schema !== "vantage.agent-config/v1") {
    throw new Error("Server returned an unknown agent-config bundle schema");
  }
  return data as unknown as AgentConfigBundle;
}

type SyncReporter = (path: string, outcome: WriteOutcome) => void;

/** Namespaced .mcp.json-shaped merge shared by both agents' mcp files. */
async function syncMcpFile(
  path: string,
  label: string,
  servers: AgentConfigBundle["mcpServers"],
  dryRun: boolean,
  summary: string[],
  report: SyncReporter,
): Promise<void> {
  const merge = mergeMcpServers(await readIfExists(path), servers, label);
  const changed = merge.added.length + merge.updated.length + merge.removed.length > 0;
  if (!changed) report(label, "unchanged");
  else if (dryRun) report(label, "dry-run");
  else {
    await writeFile(path, merge.json, "utf8");
    report(label, "updated");
  }
  for (const key of merge.added) summary.push(`    + mcpServers.${key}`);
  for (const key of merge.updated) summary.push(`    ~ mcpServers.${key}`);
  for (const key of merge.removed) summary.push(`    - mcpServers.${key} (no longer in team config)`);
}

async function syncClaude(
  dir: string,
  bundle: AgentConfigBundle,
  dryRun: boolean,
  summary: string[],
  report: SyncReporter,
): Promise<void> {
  summary.push("Claude Code:");

  // Subagents → .claude/agents/<name>.md
  for (const subagent of bundle.subagents) {
    const name = safeConfigName(subagent.name);
    if (!name) {
      summary.push(`  skipped: subagent with unsafe name ${JSON.stringify(subagent.name)}`);
      continue;
    }
    const path = join(dir, ".claude", "agents", `${name}.md`);
    report(`.claude/agents/${name}.md`, await writeManaged(path, `${subagent.markdown.trim()}\n`, dryRun));
  }

  // Skills → .claude/skills/<name>/SKILL.md
  for (const skill of bundle.skills) {
    const name = safeConfigName(skill.name);
    if (!name) {
      summary.push(`  skipped: skill with unsafe name ${JSON.stringify(skill.name)}`);
      continue;
    }
    const path = join(dir, ".claude", "skills", name, "SKILL.md");
    report(`.claude/skills/${name}/SKILL.md`, await writeManaged(path, `${skill.markdown.trim()}\n`, dryRun));
  }

  // Rules → dedicated file + marked @import in CLAUDE.md
  const rulesMarkdown = buildTeamRulesMarkdown(bundle);
  if (rulesMarkdown) {
    report(TEAM_RULES_FILE, await writeManaged(join(dir, TEAM_RULES_FILE), rulesMarkdown, dryRun));
    const claudeMdPath = join(dir, "CLAUDE.md");
    const existing = (await readIfExists(claudeMdPath)) ?? "";
    const next = applyVantageMarkerBlock(existing, buildClaudeMdBlock());
    if (next === existing) report("CLAUDE.md", "unchanged");
    else if (dryRun) report("CLAUDE.md", "dry-run");
    else {
      await writeFile(claudeMdPath, next, "utf8");
      report("CLAUDE.md", existing ? "updated" : "written");
    }
  } else {
    summary.push("  skipped: no team rules published yet");
  }

  // MCP servers → namespaced deep merge into .mcp.json
  if (bundle.mcpServers.length) {
    await syncMcpFile(join(dir, ".mcp.json"), ".mcp.json", bundle.mcpServers, dryRun, summary, report);
  }
}

async function syncCursor(
  dir: string,
  bundle: AgentConfigBundle,
  dryRun: boolean,
  summary: string[],
  report: SyncReporter,
): Promise<void> {
  summary.push("Cursor:");

  // Rules → .cursor/rules/vantage/<name>.mdc (one MDC file per rule)
  const wanted = new Set<string>();
  let wroteRule = false;
  for (const rule of bundle.rules) {
    const file = buildCursorRuleMdc(rule);
    if (!file) {
      summary.push(`  skipped: rule ${JSON.stringify(rule.name)} (empty body or unsafe name)`);
      continue;
    }
    wanted.add(file.filename);
    wroteRule = true;
    report(
      `${CURSOR_RULES_DIR}/${file.filename}`,
      await writeManaged(join(dir, CURSOR_RULES_DIR, file.filename), file.content, dryRun),
    );
  }
  if (!wroteRule) summary.push("  skipped: no team rules published yet");

  // Prune rules that left the team config — banner-carrying files only.
  const prune = await pruneManagedMdcDir(join(dir, CURSOR_RULES_DIR), wanted, dryRun);
  for (const entry of prune.pruned) {
    summary.push(`  ${dryRun ? "would remove" : "removed"}: ${CURSOR_RULES_DIR}/${entry} (no longer in team config)`);
  }
  for (const entry of prune.kept) {
    summary.push(`  left alone: ${CURSOR_RULES_DIR}/${entry} (not generated by sync)`);
  }

  // Skills → .cursor/skills/vantage/<name>/SKILL.md (same SKILL.md contract)
  for (const skill of bundle.skills) {
    const folder = cursorSkillFolder(skill.markdown, skill.name);
    if (!folder) {
      summary.push(`  skipped: skill with unsafe name ${JSON.stringify(skill.name)}`);
      continue;
    }
    const path = join(dir, CURSOR_SKILLS_DIR, folder, "SKILL.md");
    report(`${CURSOR_SKILLS_DIR}/${folder}/SKILL.md`, await writeManaged(path, `${skill.markdown.trim()}\n`, dryRun));
  }

  // MCP servers → same namespaced merge, Cursor's file
  if (bundle.mcpServers.length) {
    await syncMcpFile(join(dir, CURSOR_MCP_FILE), CURSOR_MCP_FILE, bundle.mcpServers, dryRun, summary, report);
  }

  // Honest skips: no Cursor-native equivalent — never invent a format.
  for (const subagent of bundle.subagents) {
    summary.push(`  skipped: subagent ${subagent.name} (no Cursor equivalent; synced for Claude Code only)`);
  }
  if (bundle.permissions.length) {
    summary.push("  skipped: permissions (no Cursor equivalent; see the Claude Code suggestion file)");
  }
}

export async function runAgentSync(argv: string[]): Promise<void> {
  const sub = argv[0] ?? "";
  if (sub !== "sync") {
    console.log("vantage-cad agent sync [--dir <repo>] [--agent claude|cursor|all] [--dry-run]");
    console.log("  Sync your team's shared agent configuration into this repository.");
    console.log("  --agent defaults to what the repo already uses (.claude/CLAUDE.md and/or .cursor).");
    return;
  }
  const dirFlag = argv.indexOf("--dir");
  const dir = dirFlag !== -1 && argv[dirFlag + 1] ? argv[dirFlag + 1]! : process.cwd();
  const dryRun = argv.includes("--dry-run");
  const agentFlagIndex = argv.indexOf("--agent");
  const agentFlag = agentFlagIndex !== -1 ? (argv[agentFlagIndex + 1] ?? "") : null;

  const targets = parseAgentTargets(agentFlag, {
    claude: (await dirExists(join(dir, ".claude"))) || (await fileExists(join(dir, "CLAUDE.md"))),
    cursor: await dirExists(join(dir, ".cursor")),
  });

  const bundle = await fetchAgentConfigBundle();
  const summary: string[] = [];
  const report: SyncReporter = (path, outcome) =>
    summary.push(`  ${outcome === "dry-run" ? "would write" : outcome}: ${path}`);

  if (targets.claude) await syncClaude(dir, bundle, dryRun, summary, report);
  if (targets.cursor) await syncCursor(dir, bundle, dryRun, summary, report);

  // Permissions → suggestion file ONLY, never an automatic settings.json merge.
  const suggestion = targets.claude ? buildPermissionsSuggestion(bundle) : null;
  if (suggestion) {
    report(
      PERMISSIONS_SUGGESTION_FILE,
      await writeManaged(join(dir, PERMISSIONS_SUGGESTION_FILE), suggestion, dryRun),
    );
  }

  const targetLabel = [targets.claude ? "Claude Code" : null, targets.cursor ? "Cursor" : null]
    .filter(Boolean)
    .join(" + ");
  console.log(
    `Team agent config${dryRun ? " (dry run)" : ""} for org ${bundle.orgId} → ${targetLabel}${
      targets.source === "detected" ? " (detected)" : targets.source === "default" ? " (default)" : ""
    }:`,
  );
  for (const line of summary) console.log(line);
  if (targets.source !== "flag" && !targets.cursor) {
    console.log("\nUsing Cursor too? Run with --agent cursor (or --agent all) to write .cursor/rules, .cursor/skills, and .cursor/mcp.json.");
  }
  if (suggestion) {
    console.log(
      `\nPermissions were NOT applied automatically. Review ${PERMISSIONS_SUGGESTION_FILE} and merge the rules you agree with into .claude/settings.json yourself.`,
    );
  }
}
