#!/usr/bin/env node
import { createInterface } from "node:readline/promises";
import { hostname } from "node:os";
import { stdin as input,stdout as output } from "node:process";
import { clearDeviceCredential,credentialStorageStatus,loadDeviceCredential,saveDeviceCredential } from "./secure-store";
import { detectFusionPrerequisites,openBrowser,validatePluginEndpoint } from "./platform";
const VERSION="0.1.0",command=process.argv[2]??"help",base=(process.env.VANTAGE_URL??"http://localhost:3001").replace(/\/$/,"");
const ask=createInterface({input,output});
async function json(path:string,init:RequestInit={}){const response=await fetch(`${base}${path}`,{...init,headers:{"content-type":"application/json",...init.headers}}),data=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(String(data.error??`HTTP ${response.status}`));return data;}
async function heartbeat(credential:Record<string,string>){return json("/api/cad/relay/heartbeat",{method:"POST",headers:{authorization:`Bearer ${credential.deviceToken}`} as Record<string,string>,body:JSON.stringify({cliVersion:VERSION})});}
async function setup(){console.log("\nVantage CAD desktop setup\nNo Vantage password is entered in this terminal.");const started=await json("/api/cad/pair/start",{method:"POST",body:JSON.stringify({machineName:hostname(),cliVersion:VERSION})});console.log(`\nPairing code: ${started.userCode}\nOpen: ${started.verificationUri}\nChoose your authorized organization and CAD platform in the browser.`);await openBrowser(String(started.verificationUri)).catch(()=>console.log("Browser could not open automatically; copy the URL above."));
 let paired:Record<string,unknown>|null=null;const deadline=Date.now()+Number(started.expiresIn)*1000;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,Number(started.interval)*1000));const response=await fetch(`${base}/api/cad/pair/poll`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({pollToken:started.pollToken})});const data=await response.json() as Record<string,unknown>;if(data.status==="pending")continue;if(data.status==="approved"){paired=data;break;}throw new Error(`Pairing ${String(data.status??"failed")}`);}if(!paired)throw new Error("Pairing expired. Run setup again.");
 const status=await heartbeat({deviceToken:String(paired.deviceToken)}),device=status.device as Record<string,unknown>,platform=String(device.platform);console.log(`\nPaired ${String(device.machineName)} to organization ${String(device.orgId)} for ${platform}.`);
 if(platform==="onshape"){console.log("\nOnshape hosted path:\n1. Continue in Vantage CAD Connections and authorize Onshape OAuth.\n2. Select document, workspace, and element permissions in the browser.\n3. Run `vantage-cad diagnose` to test. The Vantage server executes hosted jobs; this CLI need not stay running.");}
 else{const fusion=await detectFusionPrerequisites();console.log("\nFusion 360 local path:\n1. Install Autodesk Fusion 360 and sign in to your Autodesk account.\n2. In Fusion: Utilities → Add-Ins → Scripts and Add-Ins.\n3. Add the Vantage connector from this repository's fusion360-official connector folder.\n4. Run the add-in, keep Fusion open, then run `vantage-cad start`.");console.log(`Expected add-in folder${fusion.paths.length===1?"":"s"}:\n${fusion.paths.map(path=>`  ${path}`).join("\n")||"  Fusion relay is supported only on Windows and macOS."}`);if(!fusion.existing.length)console.log("The Fusion add-in directory was not detected. Installation requires your action; Vantage will not modify Fusion automatically.");const endpoint=await ask.question("Fusion plugin endpoint [http://127.0.0.1:32145]: ");paired.pluginEndpoint=validatePluginEndpoint(endpoint||"http://127.0.0.1:32145").toString();}
 console.log("\nAI execution source:\n1. Vantage managed plan (recommended reliable default)\n2. Team/platform configured OpenAI or Anthropic API\n3. Personal BYOK API key (configure in the encrypted Vantage browser form)\n4. Local OpenAI-compatible URL\n5. Claude Code local connector — platform owner private local sessions only; never team/background traffic");const provider=await ask.question("Choose 1–5: ");if(!["1","2","3","4","5"].includes(provider))throw new Error("Unsupported provider selection");if(provider==="3")console.log("Open Vantage provider settings to add an official API key. ChatGPT/Claude consumer subscriptions are not API credentials.");if(provider==="4"){const url=await ask.question("Local OpenAI-compatible HTTPS URL: ");const parsed=new URL(url);if(!["https:","http:"].includes(parsed.protocol))throw new Error("Local provider URL must use HTTP(S)");paired.localBaseUrl=parsed.toString();}if(provider==="5")console.log("Personal local use only. Requires platform_admin, this matching paired device, private interactive scope, and explicit opt-in. It cannot serve members, shared queues, memory generation, scheduled jobs, or production web traffic.");
 const storage=await saveDeviceCredential({deviceToken:String(paired.deviceToken),deviceId:String(paired.deviceId),orgId:String(paired.orgId),userId:String(paired.userId),platform,provider,baseUrl:base,...(paired.localBaseUrl?{localBaseUrl:String(paired.localBaseUrl)}:{}),...(paired.pluginEndpoint?{pluginEndpoint:String(paired.pluginEndpoint)}:{})});console.log(`\nSetup complete. Device token stored in ${storage}.`);}
async function status(){const credential=await loadDeviceCredential();if(!credential)throw new Error("Not paired. Run `vantage-cad setup`.");const result=await heartbeat(credential);console.log(JSON.stringify({connected:true,device:result.device,serverTime:result.serverTime,credentialStorage:credentialStorageStatus()},null,2));}
async function diagnose(){console.log(`Vantage URL: ${base}\nCLI version: ${VERSION}\nCredential storage: ${credentialStorageStatus()}`);const credential=await loadDeviceCredential();console.log(`Paired credential: ${credential?"present":"missing"}`);if(credential)await status();const fusion=await detectFusionPrerequisites();console.log(`Fusion platform supported: ${fusion.supported}\nFusion add-in paths found: ${fusion.existing.join(", ")||"none"}`);if(fusion.linuxNote)console.log(fusion.linuxNote);console.log("Consumer ChatGPT/Claude subscriptions are not tested as API credentials. Vantage never scrapes browser sessions or cookies.");}
async function start(){const credential=await loadDeviceCredential();if(!credential)throw new Error("Not paired. Run `vantage-cad setup`.");if(credential.platform==="onshape"){console.log("Onshape jobs run on the Vantage server. This monitor may be closed at any time.");for(;;){await heartbeat(credential);await new Promise(resolve=>setTimeout(resolve,30_000));}}
 const useMock=process.env.VANTAGE_CAD_MOCK==="1";
 const plugin=validatePluginEndpoint(credential.pluginEndpoint??"http://127.0.0.1:32145");
 if(useMock){
  const { startMockFusionPluginServer } = await import("@vantage/cad");
  await startMockFusionPluginServer(Number(plugin.port || 32145));
  console.log("VANTAGE_CAD_MOCK=1 — started in-process mock Fusion plugin (no Autodesk required).");
 }
 console.log("Fusion local relay started. Keep Fusion running with the official connector add-in active (or mock plugin). Press Ctrl+C to stop.");
 for(;;){await heartbeat(credential);const claim=await fetch(`${base}/api/cad/relay/jobs`,{method:"POST",headers:{authorization:`Bearer ${credential.deviceToken}`}});if(claim.status===204){await new Promise(resolve=>setTimeout(resolve,3000));continue;}if(!claim.ok)throw new Error(`Job claim failed with HTTP ${claim.status}`);const envelope=await claim.json() as Record<string,unknown>;const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),120_000);try{const executed=await fetch(new URL("/execute",plugin),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(envelope),signal:controller.signal});const result=await executed.json() as Record<string,unknown>;await json("/api/cad/relay/jobs",{method:"PATCH",headers:{authorization:`Bearer ${credential.deviceToken}`} as Record<string,string>,body:JSON.stringify({jobId:envelope.jobId,stepId:envelope.stepId,leaseToken:envelope.leaseToken,state:executed.ok?"completed":"failed",progress:100,result})});}finally{clearTimeout(timeout);}}}
async function logout(){const credential=await loadDeviceCredential();if(credential)await json("/api/cad/relay/logout",{method:"POST",headers:{authorization:`Bearer ${credential.deviceToken}`} as Record<string,string>,body:"{}"}).catch(()=>undefined);await clearDeviceCredential();console.log("Local credential removed and paired device revoked.");}
async function main(){if(command==="setup")await setup();else if(command==="status")await status();else if(command==="diagnose")await diagnose();else if(command==="start")await start();else if(command==="logout")await logout();else if(command==="update")console.log("This CLI is not published to npm. From the Vantage repository run: npm install && npm run build --workspace=@vantage/cad-cli, then npm install -g ./packages/vantage-cad-cli");else console.log("vantage-cad <setup|start|status|diagnose|update|logout>");}
main().catch(error=>{console.error(`vantage-cad: ${error instanceof Error?error.message:"Command failed"}`);process.exitCode=1;}).finally(()=>{if(command!=="start")ask.close();});
