-- Spare-robot-kit: a competition spare-parts kit checklist generated by cross-referencing
-- inventory spare bins against FMEA repeat-failure history for their subsystem (same read-only
-- join pattern as 0231_spare_forecast.sql). The checklist itself — what to physically pack, and
-- what's been packed — is what this migration persists; the candidate items are computed live
-- from the existing inventory_items / fmea_failures tables (see compute-spare-robot-kit.ts).

CREATE TABLE spare_robot_kit_checklists (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  season_year integer NOT NULL,
  title text NOT NULL,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'finalized')),
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  rationale text NOT NULL DEFAULT '',
  created_by uuid NOT NULL REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX spare_robot_kit_checklists_org_season_idx
  ON spare_robot_kit_checklists(org_id, season_year, created_at DESC);

ALTER TABLE spare_robot_kit_checklists ENABLE ROW LEVEL SECURITY;

CREATE POLICY spare_robot_kit_checklists_member_read ON spare_robot_kit_checklists
  FOR SELECT TO vantage_app USING (is_org_member(org_id));
CREATE POLICY spare_robot_kit_checklists_member_insert ON spare_robot_kit_checklists
  FOR INSERT TO vantage_app WITH CHECK (is_org_member(org_id) AND created_by = current_app_user_id());
CREATE POLICY spare_robot_kit_checklists_member_update ON spare_robot_kit_checklists
  FOR UPDATE TO vantage_app USING (is_org_member(org_id)) WITH CHECK (is_org_member(org_id));
CREATE POLICY spare_robot_kit_checklists_member_delete ON spare_robot_kit_checklists
  FOR DELETE TO vantage_app
  USING (created_by = current_app_user_id() OR has_org_role(org_id, ARRAY['owner', 'admin']::org_role[]));

GRANT SELECT, INSERT, UPDATE, DELETE ON spare_robot_kit_checklists TO vantage_app, vantage_worker;
