/**
 * Client-safe view of a renderWithModel outcome (packages/agent/src/render.ts).
 *
 * Every AI-led POST route answers `{ ...view, render }`; the feature clients read that
 * `render` with `renderReceiptFrom` and hand it to <RenderAttribution>, so the badge says
 * "Generated by Vantage AI" only when a model actually wrote the output and "Template —
 * no model call" (with the reason) when the deterministic template stood in.
 *
 * No server imports here: this file is imported from "use client" components.
 */

export type ClientRenderMode = "model" | "template";

export type ClientRenderOutcome = {
  mode: ClientRenderMode;
  /** meteredAI feature name (= ai_render_attempts.feature). */
  feature?: string;
  modelId?: string;
  provider?: string;
  /** Set only when mode === "template"; may carry a suffix, e.g. "cap_hit:payg_not_enabled". */
  fallbackReason?: string;
  requestId?: string;
};

/** The outcome plus when the client received it — what the badge's "generated at" shows. */
export type RenderReceipt = { render: ClientRenderOutcome; at: string };

function optionalString(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value : undefined;
}

/** The `render` field of a route response, or null when the response carries none. */
export function readRenderOutcome(data: unknown): ClientRenderOutcome | null {
  if (!data || typeof data !== "object") return null;
  const render = (data as { render?: unknown }).render;
  if (!render || typeof render !== "object") return null;
  const record = render as Record<string, unknown>;
  const mode = record.mode;
  if (mode !== "model" && mode !== "template") return null;
  return {
    mode,
    feature: optionalString(record.feature),
    modelId: optionalString(record.modelId),
    provider: optionalString(record.provider),
    fallbackReason: optionalString(record.fallbackReason),
    requestId: optionalString(record.requestId),
  };
}

/** A receipt for a POST response that rendered something; null for responses that did not. */
export function renderReceiptFrom(data: unknown, at: string = new Date().toISOString()): RenderReceipt | null {
  const render = readRenderOutcome(data);
  return render ? { render, at } : null;
}

const FALLBACK_REASON_COPY: Record<string, string> = {
  no_provider: "no AI provider is configured for this team",
  billing_not_configured: "AI billing is not configured",
  cap_hit: "the team's AI spend cap was reached",
  approval_required: "the call is waiting for an approval",
  policy_denied: "the team's AI policy denied the call",
  timeout: "the model did not answer in time",
  provider_error: "the AI provider returned an error",
  empty_output: "the model returned nothing usable",
  rejected_output: "the model's answer did not keep the required structure",
  resolve_error: "the team's AI provider could not be resolved",
  deterministic_only: "this output is fully computed from your data",
};

/** Plain-language reason a template stood in, from the fallback taxonomy in render.ts. */
export function fallbackReasonLabel(reason: string | null | undefined): string | null {
  if (!reason) return null;
  const [head, detail] = reason.split(":", 2);
  const copy = FALLBACK_REASON_COPY[head ?? ""];
  if (!copy) return `the template stood in (${reason})`;
  if (head === "cap_hit" && detail) return `${copy} (${detail.replace(/_/g, " ")})`;
  return copy;
}
