import { auth } from "@vantage/core";
import { withRls } from "@vantage/db";
import { createExportJob,createExportRegistry,issueExportDownload,processExportJob } from "@vantage/export-center";
import { after } from "next/server";
import { headers } from "next/headers";
async function current(){const value=await auth.api.getSession({headers:await headers()});if(!value)throw new Error("Authentication required");return value;}
const errorResponse=(error:unknown)=>Response.json({error:error instanceof Error?error.message:"Export request failed"},{status:400});
export async function GET(request:Request){try{const session=await current(),url=new URL(request.url),orgId=url.searchParams.get("orgId");if(!orgId)throw new Error("orgId is required");const jobs=await withRls({userId:session.user.id,orgId},async client=>(await client.query(`SELECT id,scope,status,domains,filters,progress,size_bytes AS "sizeBytes",error,expires_at AS "expiresAt",created_at AS "createdAt" FROM export_jobs WHERE org_id=$1 ORDER BY created_at DESC LIMIT 30`,[orgId])).rows);return Response.json({jobs,domains:[...createExportRegistry().values()].map(({id,description,scope,fileName})=>({id,description,scope,fileName}))});}catch(error){return errorResponse(error);}}
export async function POST(request:Request){try{const session=await current(),body=await request.json() as {orgId:string;scope:"team"|"private";domains:string[]|"all";filters?:Record<string,unknown>;action?:string;jobId?:string;reason?:string};if(body.action==="download"){const token=await withRls({userId:session.user.id,orgId:body.orgId},client=>issueExportDownload(client,String(body.jobId),session.user.id));return Response.json({url:`/api/exports/download?token=${encodeURIComponent(token)}`});}const jobId=await withRls({userId:session.user.id,orgId:body.orgId},client=>createExportJob(client,{orgId:body.orgId,userId:session.user.id,scope:body.scope,domains:body.domains,filters:body.filters??{},reason:body.reason}));after(async()=>{await withRls({userId:session.user.id,orgId:body.orgId},client=>processExportJob(client,jobId));});return Response.json({jobId},{status:202});}catch(error){return errorResponse(error);}}
export async function PATCH(request:Request){try{const session=await current(),body=await request.json() as {orgId:string;jobId:string};await withRls({userId:session.user.id,orgId:body.orgId},client=>client.query(`UPDATE export_jobs SET cancel_requested_at=now(),updated_at=now() WHERE id=$1 AND org_id=$2 AND requested_by=$3 AND status IN ('queued','running')`,[body.jobId,body.orgId,session.user.id]));return Response.json({success:true});}catch(error){return errorResponse(error);}}
