import { relativeTime } from "./relative-time";
import styles from "./ui.module.css";
import { aiAttributionView, type AIAttributionKind } from "./ai-attribution-policy";

export { AI_ATTRIBUTION_LABELS, aiAttributionView } from "./ai-attribution-policy";
export type { AIAttributionKind } from "./ai-attribution-policy";

type AIAttributionProps = {
  /**
   * Honest-label policy: "ai" ONLY where a real metered model call produced the
   * content; "computed" for deterministic output derived from the team's own
   * data (templates, rollups, rule-based analysis). Defaults to "ai" so
   * existing metered surfaces keep their badge.
   */
  kind?: AIAttributionKind;
  /** The meteredAI `feature=` label (or the compute feature for kind="computed"). */
  feature: string;
  /** ISO timestamp the content was generated. */
  generatedAt: string;
  onRegenerate?: () => void;
  className?: string;
};

const SparkGlyph = () => (
  <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
    <path
      d="M8 1.5 9.4 6 14 7.4 9.4 8.8 8 13.4 6.6 8.8 2 7.4 6.6 6 8 1.5Z"
      fill="currentColor"
    />
  </svg>
);

const TrendGlyph = () => (
  <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
    <path
      d="M3 12.5 6.5 8 9 10.5 13 4.5"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
    />
  </svg>
);

/**
 * Trust chip for generated panels.
 * - kind="ai": "Generated by Vantage AI · <feature> · <relative time>" — reserved
 *   for content a real metered model call produced.
 * - kind="computed": "Computed from your data · <feature> · <relative time>" —
 *   deterministic templates/rollups. Never dress deterministic output as AI.
 * Optional regenerate. Thread `generatedAt`/`feature` through each compute-* result type.
 */
export function AIAttribution({
  kind = "ai",
  feature,
  generatedAt,
  onRegenerate,
  className,
}: AIAttributionProps) {
  const rel = relativeTime(generatedAt);
  const view = aiAttributionView(kind);
  return (
    <div className={[styles.aiAttribution, className].filter(Boolean).join(" ")}>
      <span className={styles[view.chipClass]}>
        {view.glyph === "trend" ? <TrendGlyph /> : <SparkGlyph />}
        {view.label}
      </span>
      <span>
        {feature}
        {rel ? ` · ${rel}` : ""}
      </span>
      {onRegenerate ? (
        <button type="button" className={styles.regenBtn} onClick={onRegenerate}>
          Regenerate
        </button>
      ) : null}
    </div>
  );
}
