// Honest-label policy: the AI badge appears ONLY where a real metered model
// call produced the content; deterministic output is labeled "Computed from
// your data". <AIAttribution kind=…> renders exactly this view.
import { describe, expect, it } from "vitest";
import {
  AI_ATTRIBUTION_LABELS,
  aiAttributionView,
  attributionKindForRenderMode,
} from "./ai-attribution-policy";

describe("aiAttributionView", () => {
  it("labels metered model output as AI (kind='ai')", () => {
    const view = aiAttributionView("ai");
    expect(view.label).toBe("Generated by Vantage AI");
    expect(view.glyph).toBe("spark");
    expect(view.chipClass).toBe("aiChip");
  });

  it("labels deterministic output honestly (kind='computed')", () => {
    const view = aiAttributionView("computed");
    expect(view.label).toBe("Computed from your data");
    expect(view.glyph).toBe("trend");
    expect(view.chipClass).toBe("computedChip");
    expect(view.label).not.toContain("AI");
  });

  it("defaults to the AI badge so existing metered surfaces are unchanged", () => {
    expect(aiAttributionView().label).toBe(AI_ATTRIBUTION_LABELS.ai);
  });

  it("keeps the policy labels distinct", () => {
    expect(AI_ATTRIBUTION_LABELS.ai).not.toBe(AI_ATTRIBUTION_LABELS.computed);
    expect(AI_ATTRIBUTION_LABELS.template).not.toBe(AI_ATTRIBUTION_LABELS.ai);
  });

  it("labels a template fallback as Template, never AI (kind='template')", () => {
    const view = aiAttributionView("template");
    expect(view.label).toContain("Template");
    expect(view.label).not.toContain("AI");
    expect(view.glyph).toBe("trend");
    expect(attributionKindForRenderMode("model")).toBe("ai");
    expect(attributionKindForRenderMode("template")).toBe("template");
    expect(attributionKindForRenderMode(undefined)).toBe("template");
  });
});
