import { relativeTime } from "./relative-time";
import styles from "./ui.module.css";

type AIAttributionProps = {
  /** The meteredAI `feature=` label. */
  feature: string;
  /** ISO timestamp the content was generated. */
  generatedAt: string;
  onRegenerate?: () => void;
  className?: string;
};

const SparkGlyph = () => (
  <svg viewBox="0 0 16 16" fill="none" aria-hidden="true">
    <path
      d="M8 1.5 9.4 6 14 7.4 9.4 8.8 8 13.4 6.6 8.8 2 7.4 6.6 6 8 1.5Z"
      fill="currentColor"
    />
  </svg>
);

/**
 * Trust chip for every meteredAI output: "Generated by Vantage AI · <feature> · <relative time>"
 * + optional regenerate. Thread `generatedAt`/`feature` through each compute-* result type.
 */
export function AIAttribution({ feature, generatedAt, onRegenerate, className }: AIAttributionProps) {
  const rel = relativeTime(generatedAt);
  return (
    <div className={[styles.aiAttribution, className].filter(Boolean).join(" ")}>
      <span className={styles.aiChip}>
        <SparkGlyph />
        Generated by Vantage AI
      </span>
      <span>
        {feature}
        {rel ? ` · ${rel}` : ""}
      </span>
      {onRegenerate ? (
        <button type="button" className={styles.regenBtn} onClick={onRegenerate}>
          Regenerate
        </button>
      ) : null}
    </div>
  );
}
