// Honest-label policy for generated panels — pure, framework-free, unit-tested.
//
// Product rule (never fabricate, applied to labels): a surface that computes
// deterministically is labeled "Computed from your data"; the AI badge
// ("Generated by Vantage AI") appears ONLY where a real metered model call
// produced the content. <AIAttribution kind=…> renders this policy.

export type AIAttributionKind = "ai" | "computed" | "template";

export const AI_ATTRIBUTION_LABELS: Record<AIAttributionKind, string> = {
  ai: "Generated by Vantage AI",
  computed: "Computed from your data",
  // An AI-led feature whose model call did not produce the output (no key, cap hit,
  // provider error…) and the deterministic template stood in — see renderWithModel.
  template: "Template — no model call",
};

export type AIAttributionView = {
  kind: AIAttributionKind;
  label: string;
  /** Which glyph the chip draws: the spark is reserved for real model output. */
  glyph: "spark" | "trend";
  /** ui.module.css class key the chip uses. */
  chipClass: "aiChip" | "computedChip";
};

/** Resolve the chip presentation for a kind (default "ai" keeps existing metered surfaces unchanged). */
export function aiAttributionView(kind: AIAttributionKind = "ai"): AIAttributionView {
  if (kind === "computed") {
    return { kind, label: AI_ATTRIBUTION_LABELS.computed, glyph: "trend", chipClass: "computedChip" };
  }
  if (kind === "template") {
    return { kind, label: AI_ATTRIBUTION_LABELS.template, glyph: "trend", chipClass: "computedChip" };
  }
  return { kind: "ai", label: AI_ATTRIBUTION_LABELS.ai, glyph: "spark", chipClass: "aiChip" };
}

/**
 * Attribution for a renderWithModel outcome: "ai" only when a real model produced the
 * output, "template" otherwise. Never dresses a fallback as AI.
 */
export function attributionKindForRenderMode(
  mode: "model" | "template" | null | undefined,
): AIAttributionKind {
  return mode === "model" ? "ai" : "template";
}
