import { AIAttribution } from "./ai-attribution";
import { attributionKindForRenderMode } from "./ai-attribution-policy";
import { fallbackReasonLabel, type RenderReceipt } from "../../lib/ai-render/outcome";

type RenderAttributionProps = {
  /** From `renderReceiptFrom(postResponse)`; renders nothing until a route has answered with a `render`. */
  receipt: RenderReceipt | null | undefined;
  /** The meteredAI feature label; the receipt's own feature wins when the route reported one. */
  feature: string;
  onRegenerate?: () => void;
  className?: string;
};

/**
 * Honest badge for an AI-led feature's latest render. "Generated by Vantage AI" appears
 * only when the route reported mode "model"; a template fallback shows the neutral
 * "Template — no model call" chip plus the reason, so a fallback is never dressed as AI.
 */
export function RenderAttribution({ receipt, feature, onRegenerate, className }: RenderAttributionProps) {
  if (!receipt) return null;
  const { render } = receipt;
  const kind = attributionKindForRenderMode(render.mode);
  const detail =
    kind === "template"
      ? fallbackReasonLabel(render.fallbackReason)
      : render.modelId
        ? `${render.provider ? `${render.provider} · ` : ""}${render.modelId}`
        : null;
  return (
    <div className={className} data-render-mode={render.mode} data-testid="render-attribution">
      <AIAttribution
        kind={kind}
        feature={render.feature ?? feature}
        generatedAt={receipt.at}
        onRegenerate={onRegenerate}
      />
      {detail ? (
        <p className="app-muted" style={{ margin: "4px 0 0", fontSize: 12 }}>
          {kind === "template" ? `Template stood in — ${detail}.` : `Model: ${detail}.`}
        </p>
      ) : null}
    </div>
  );
}
