"use client";
import { useEffect,useState } from "react";
const presets=[
  ["next_match","Next Match","Countdown, alliances, scheduled time, and leave-now status"],
  ["win_prediction","Win Prediction","Alliance probability, confidence, factors, and strategy headline"],
  ["robot_readiness","Robot Readiness","Battery, checklist, inspection, maintenance, and queue status"],
  ["event_command","Event Command","Current/next match, rank, record, surprises, and alerts"],
  ["scouting_coverage","Scouting Coverage","Assignments, missing reports, disagreements, and event intel"],
] as const;
const presetWidgets:Record<string,string[]>={next_match:["next_match","alerts"],win_prediction:["prediction","strategy"],robot_readiness:["robot_readiness","alerts"],event_command:["event_status","next_match","alerts"],scouting_coverage:["scouting_coverage","team_intel"]};
type Board={id:string;name:string;preset:string;widgets:Array<{type:string;x:number;y:number;w:number;h:number}>};
export default function DisplaySetup({orgId}:{orgId:string}){const[boards,setBoards]=useState<Board[]>([]);const[name,setName]=useState("Pit TV");const[preset,setPreset]=useState("next_match");const[widgets,setWidgets]=useState<string[]>(presetWidgets.next_match!);const[message,setMessage]=useState("");
 async function load(){const r=await fetch(`/api/display/boards?orgId=${orgId}`);const d=await r.json();setBoards(d.boards??[]);if(!r.ok)setMessage(d.error);}
 useEffect(()=>{void load();},[orgId]);
 function choose(value:string){setPreset(value);setWidgets(presetWidgets[value]??[]);}
 async function save(id?:string){const layout=widgets.map((type,index)=>({type,x:(index%2)*6,y:Math.floor(index/2)*4,w:6,h:4}));const r=await fetch("/api/display/boards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({orgId,id,name:id?`${name} copy`:name,preset,widgets:layout})});const d=await r.json();setMessage(r.ok?"Display board saved.":d.error);if(r.ok)await load();}
 async function token(boardId:string){const r=await fetch("/api/display/boards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"token",orgId,boardId,label:"Pit TV"})});const d=await r.json();if(r.ok){await navigator.clipboard.writeText(`${location.origin}/display/kiosk?token=${d.token}`);setMessage("Read-only kiosk link copied. It is shown only once.");}else setMessage(d.error);}
 return<main className="intel-app display-setup"><header className="intel-header"><div><span className="eyebrow">Live / Displays</span><h1>Pit TV boards</h1><p className="app-muted">Pick a preset, save a board, then open fullscreen or copy a read-only kiosk token. Empty boards stay empty until you save one.</p></div><a href={`/workspace?orgId=${orgId}`}>← Workspace</a></header>{message&&<p className="telemetry-status" role="status">{message}</p>}
 {!boards.length&&!message?<section className="soft-empty" style={{marginBottom:16}}><span className="app-badge setup">No boards yet</span><h2>Create your first display board</h2><p>Choose a preset below and save. Vantage will not invent match countdowns or ranks for an empty board.</p></section>:null}
 <section className="preset-picker" aria-label="Display presets">{presets.map(([id,title,copy])=><button className={preset===id?"active":""} key={id} onClick={()=>choose(id)}><strong>{title}</strong><span>{copy}</span></button>)}<button className={preset==="custom"?"active":""} onClick={()=>setPreset("custom")}><strong>Custom grid</strong><span>Choose authorized, competition-readable widgets</span></button></section>
 <section className="admin-grid"><form className="intel-panel" onSubmit={(e)=>{e.preventDefault();void save();}}><label>Board name<input value={name} onChange={(e)=>setName(e.target.value)} required/></label>{preset==="custom"&&<fieldset><legend>Widgets</legend>{["next_match","prediction","strategy","robot_readiness","event_status","scouting_coverage","alerts","team_intel"].map((type)=><label className="check-field" key={type}><input type="checkbox" checked={widgets.includes(type)} onChange={(e)=>setWidgets(e.target.checked?[...widgets,type]:widgets.filter((item)=>item!==type))}/>{type.replaceAll("_"," ")}</label>)}</fieldset>}<div className="intel-actions"><button>Save board</button><button type="button" onClick={()=>choose(preset==="custom"?"next_match":preset)}>Reset to preset</button></div></form>
 <section className="display-preview" aria-label="Board preview"><span>16:9 PREVIEW · ONE LAYOUT</span><h2>{name}</h2><div>{widgets.map((item)=><article key={item}><strong>{item.replaceAll("_"," ")}</strong><small>Authorized module data</small></article>)}</div></section></section>
 <section className="compare-panel"><span className="eyebrow">SAVED BOARDS</span>{boards.map((board)=><article className="saved-board" key={board.id}><div><strong>{board.name}</strong><small>{board.preset.replaceAll("_"," ")}</small></div><a href={`/display/kiosk?orgId=${orgId}&boardId=${board.id}`} target="_blank">Open fullscreen</a><button onClick={()=>{setName(board.name);setPreset(board.preset);setWidgets(board.widgets.map((w)=>w.type));void save(board.id);}}>Duplicate</button><button onClick={()=>void token(board.id)}>Copy TV token</button></article>)}</section></main>;}
