#!/usr/bin/env bash
# Pi / always-on host setup for the Vantage free relay.
#
# Builds the chain:  Vantage (Vercel) --> tunnel --> FreeBuff proxy (this box) --> Codebuff
# plus the outbound-only background sweep that drains free_relay_jobs.
#
# Idempotent: safe to re-run. Never overwrites an existing key or .env value.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

ENV_FILE="${FREE_RELAY_ENV_FILE:-$REPO_ROOT/.env.free-relay}"
PROXY_PORT="${FREE_RELAY_PROXY_PORT:-8080}"
PROXY_IMAGE="${FREE_RELAY_PROXY_IMAGE:-ghcr.io/quorinex/freebuff2api:latest}"
PROXY_NAME="${FREE_RELAY_PROXY_NAME:-vantage-freebuff-proxy}"
MODEL="${FREE_RELAY_MODEL:-deepseek/deepseek-v4-flash}"

say() { printf '\n\033[1m== %s\033[0m\n' "$1"; }
warn() { printf '\033[33m!! %s\033[0m\n' "$1" >&2; }
die() { printf '\033[31mxx %s\033[0m\n' "$1" >&2; exit 1; }

say "Vantage free-relay installer"

command -v node >/dev/null 2>&1 || die "Node.js 22+ is required."
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 22 ] || die "Node.js 22+ is required (found $(node -v))."

# ---------------------------------------------------------------- relay secret
# The proxy is the only thing holding your FreeBuff token. Anything that can reach
# it can spend that token, so the relay always gets a key of its own — even when it
# starts out bound to loopback, because a tunnel may be added later.
if [ -f "$ENV_FILE" ] && grep -q '^FREE_RELAY_API_KEY=' "$ENV_FILE"; then
  RELAY_KEY="$(grep '^FREE_RELAY_API_KEY=' "$ENV_FILE" | head -n1 | cut -d= -f2-)"
  say "Reusing existing FREE_RELAY_API_KEY from $ENV_FILE"
else
  command -v openssl >/dev/null 2>&1 || die "openssl is required to generate a relay key."
  RELAY_KEY="vr_$(openssl rand -hex 24)"
  say "Generated a new FREE_RELAY_API_KEY"
fi

if [ -z "${FREEBUFF_AUTH_TOKENS:-}" ]; then
  if [ -f "$ENV_FILE" ] && grep -q '^FREEBUFF_AUTH_TOKENS=' "$ENV_FILE"; then
    FREEBUFF_AUTH_TOKENS="$(grep '^FREEBUFF_AUTH_TOKENS=' "$ENV_FILE" | head -n1 | cut -d= -f2-)"
  else
    warn "FREEBUFF_AUTH_TOKENS is not set."
    warn "Log in to FreeBuff/Codebuff, copy your auth token, then re-run as:"
    warn "  FREEBUFF_AUTH_TOKENS=eyJ... bash scripts/pi/install-free-relay.sh"
    die "Cannot start the proxy without at least one FreeBuff token."
  fi
fi

# ------------------------------------------------------------------ env file
if [ ! -f "$ENV_FILE" ]; then
  umask 077
  cat >"$ENV_FILE" <<EOF
# Vantage free relay — generated by scripts/pi/install-free-relay.sh
# Chmod 600. Contains your FreeBuff token and the relay key. Never commit.
FREEBUFF_AUTH_TOKENS=$FREEBUFF_AUTH_TOKENS
FREE_RELAY_API_KEY=$RELAY_KEY
FREE_RELAY_BASE_URL=http://127.0.0.1:$PROXY_PORT/v1
FREE_RELAY_MODEL=$MODEL
FREE_RELAY_PROVIDER=freebuff
FREE_RELAY_INTERVAL_MS=300000
# Worker role — needed only by the background sweep, not by the proxy.
DATABASE_ADMIN_URL=
EOF
  chmod 600 "$ENV_FILE"
  say "Wrote $ENV_FILE (chmod 600)"
else
  say "Keeping existing $ENV_FILE"
fi

# --------------------------------------------------------------- npm install
say "Installing workspace dependencies"
npm install --no-fund --no-audit

# --------------------------------------------------------------- proxy (docker)
if command -v docker >/dev/null 2>&1; then
  say "Starting the FreeBuff proxy ($PROXY_NAME on :$PROXY_PORT)"
  docker rm -f "$PROXY_NAME" >/dev/null 2>&1 || true
  docker run -d --name "$PROXY_NAME" \
    --restart unless-stopped \
    -p "127.0.0.1:$PROXY_PORT:8080" \
    -e AUTH_TOKENS="$FREEBUFF_AUTH_TOKENS" \
    -e API_KEYS="$RELAY_KEY" \
    "$PROXY_IMAGE" >/dev/null
  # Bound to 127.0.0.1 on purpose: reaching it from outside goes through the tunnel
  # below, so the box never has an open port on the LAN or the internet.
else
  warn "docker not found — start a FreeBuff proxy yourself on :$PROXY_PORT."
  warn "It must require the relay key as a client API key (API_KEYS=\$FREE_RELAY_API_KEY)."
fi

# --------------------------------------------------------------- verify
say "Verifying the proxy answers with the relay key"
sleep 4
if command -v curl >/dev/null 2>&1; then
  if curl -fsS -m 20 "http://127.0.0.1:$PROXY_PORT/v1/models" \
       -H "Authorization: Bearer $RELAY_KEY" >/dev/null; then
    echo "  /v1/models OK"
  else
    warn "/v1/models did not answer. Check: docker logs $PROXY_NAME"
  fi

  # A keyless request must be refused, or the relay is an open pass-through.
  if curl -fsS -m 20 "http://127.0.0.1:$PROXY_PORT/v1/models" >/dev/null 2>&1; then
    warn "The proxy answered WITHOUT a key — it is an open pass-through to your"
    warn "FreeBuff account. Set API_KEYS on the proxy before exposing it."
  else
    echo "  keyless request correctly refused"
  fi
else
  warn "curl not found — skipping verification."
fi

# --------------------------------------------------------------- systemd
if command -v systemctl >/dev/null 2>&1 && [ "$(id -u)" = "0" ]; then
  say "Installing the background sweep as a systemd service"
  cat >/etc/systemd/system/vantage-free-relay.service <<EOF
[Unit]
Description=Vantage free-relay background sweep (outbound only)
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$REPO_ROOT
EnvironmentFile=$ENV_FILE
ExecStart=$(command -v npm) run free-relay:daemon
Restart=always
RestartSec=30

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now vantage-free-relay.service
  echo "  journalctl -u vantage-free-relay -f"
else
  warn "Not root (or no systemd) — skipping the service unit."
  warn "Run the sweep manually with: npm run free-relay:daemon"
fi

# --------------------------------------------------------------- summary
cat <<EOF

$(say "Next steps")

1. Background jobs already work. The sweep is outbound-only: it dials your database
   and pulls queued work, so nothing needs to be exposed for it.

2. For interactive team chat, Vercel has to reach this box. Use a tunnel, not a port
   forward — serverless functions call from rotating IPs, so there is no source range
   to allowlist, and a forwarded port puts your home network on the internet.

     cloudflared tunnel login
     cloudflared tunnel create vantage-relay
     cloudflared tunnel route dns vantage-relay relay.yourdomain.com
     cloudflared tunnel run --url http://127.0.0.1:$PROXY_PORT vantage-relay

3. Then set these on the Vantage deployment (Vercel project env):

     FREE_RELAY_BASE_URL=https://relay.yourdomain.com/v1
     FREE_RELAY_API_KEY=$RELAY_KEY
     FREE_RELAY_MODEL=$MODEL
     FREE_RELAY_PROVIDER=freebuff

   Vantage refuses a non-loopback FREE_RELAY_BASE_URL that has no key, so the tunnel
   hostname above must keep FREE_RELAY_API_KEY set.

4. Grant a team a relay window at /admin/ai-grants. Teams without a grant are
   untouched and keep using their own keys.

Full walkthrough: docs/FREE_RELAY_PI.md
EOF
