#!/usr/bin/env bash
# Pi / always-on host setup for the Vantage free relay.
#
# Builds the chain:  Vantage (Vercel) --> tunnel --> Vantage layer --> Freebuff Coder UI /v1
# plus the outbound-only background sweep that drains free_relay_jobs.
# The Coder UI (logged-in session on this box) is the Freebuff client. We do not
# impersonate the official CLI.
#
# Idempotent: safe to re-run. Never overwrites an existing key or .env value.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT"

ENV_FILE="${FREE_RELAY_ENV_FILE:-$REPO_ROOT/.env.free-relay}"
# The layer Vantage talks to. Bound to loopback; the tunnel points here.
LAYER_PORT="${FREE_RELAY_PROXY_PORT:-8080}"
# Freebuff Coder UI local /v1. Only the Vantage layer talks to it.
UPSTREAM_PORT="${FREEBUFF_UPSTREAM_PORT:-3457}"
UPSTREAM_URL="${FREEBUFF_UPSTREAM_URL:-http://127.0.0.1:$UPSTREAM_PORT}"
# Default to an UNMETERED model. Per Codebuff's README, GLM 5.3 Flash and MiMo 2.5 cost
# no session at all, while DeepSeek V4 Flash draws on daily sessions and pauses at peak
# hours — the wrong default for a relay that backs a whole team. Confirm slugs against
# Coder UI /v1/models via `npm run free-relay:verify`.
MODEL="${FREE_RELAY_MODEL:-glm/glm-5.3-flash}"

say() { printf '\n\033[1m== %s\033[0m\n' "$1"; }
warn() { printf '\033[33m!! %s\033[0m\n' "$1" >&2; }
die() { printf '\033[31mxx %s\033[0m\n' "$1" >&2; exit 1; }

say "Vantage free-relay installer"

command -v node >/dev/null 2>&1 || die "Node.js 22+ is required."
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 22 ] || die "Node.js 22+ is required (found $(node -v))."

# ---------------------------------------------------------------- relay secret
# Coder UI holds the FreeBuff session. This key is only for Vantage → Pi layer.
if [ -f "$ENV_FILE" ] && grep -q '^FREE_RELAY_API_KEY=' "$ENV_FILE"; then
  RELAY_KEY="$(grep '^FREE_RELAY_API_KEY=' "$ENV_FILE" | head -n1 | cut -d= -f2-)"
  say "Reusing existing FREE_RELAY_API_KEY from $ENV_FILE"
else
  command -v openssl >/dev/null 2>&1 || die "openssl is required to generate a relay key."
  RELAY_KEY="vr_$(openssl rand -hex 24)"
  say "Generated a new FREE_RELAY_API_KEY"
fi

# ------------------------------------------------------------------ env file
if [ ! -f "$ENV_FILE" ]; then
  umask 077
  cat >"$ENV_FILE" <<EOF
# Vantage Pi layer — generated by scripts/pi/install-free-relay.sh
# Chmod 600. Contains the relay key. Never commit.
# Session lives in the signed-in Freebuff Coder UI, not here.
FREE_RELAY_API_KEY=$RELAY_KEY
FREE_RELAY_BASE_URL=http://127.0.0.1:$LAYER_PORT/v1
FREE_RELAY_MODEL=$MODEL
FREE_RELAY_PROVIDER=freebuff
FREE_RELAY_MAX_CONCURRENT=16
FREE_RELAY_INTERVAL_MS=300000
FREEBUFF_UPSTREAM_URL=$UPSTREAM_URL
FREE_RELAY_DEVICE_NAME=frcvantagefreebuff relay
FREEBUFF_WORKSPACE_ROOT=$HOME/vantage-freebuff/orgs
# Worker role — needed only by the background sweep, not by the layer.
DATABASE_ADMIN_URL=
EOF
  chmod 600 "$ENV_FILE"
  say "Wrote $ENV_FILE (chmod 600)"
else
  say "Keeping existing $ENV_FILE"
fi

# --------------------------------------------------------------- npm install
say "Installing workspace dependencies"
npm install --no-fund --no-audit

# --------------------------------------------------------------- Coder UI
# Keep the official Freebuff Coder UI (or its local /v1) logged in on this box.
# We only probe it. We do not start a CLI-impersonating Docker proxy.
say "Looking for Freebuff Coder UI at $UPSTREAM_URL"
if command -v curl >/dev/null 2>&1 && curl -fsS -m 8 "$UPSTREAM_URL/v1/models" >/dev/null 2>&1; then
  echo "  Coder UI /v1/models answered"
elif command -v curl >/dev/null 2>&1 && curl -fsS -m 8 "$UPSTREAM_URL/v1/models" \
     -H "Authorization: Bearer $RELAY_KEY" >/dev/null 2>&1; then
  echo "  Coder UI /v1/models answered (with Authorization)"
else
  warn "Nothing answered at $UPSTREAM_URL/v1/models."
  warn "Official path: npx --yes @codebuff/cli login on THIS Pi (no laptop)."
  warn "Coder UI /v1 is optional. Credentials stay in ~/.config/manicode/."
fi

# --------------------------------------------------------------- verify
say "Starting services that stay up after you shut the laptop"
if command -v systemctl >/dev/null 2>&1; then
  bash "$REPO_ROOT/scripts/pi/install-autonomous-units.sh"
else
  warn "No systemd — start the layer with: npm run free-relay:serve"
  warn "and put scripts/pi/keep-tunnel.sh on cron so it survives logout."
fi

say "Verifying the layer answers with the relay key"
sleep 4
if command -v curl >/dev/null 2>&1; then
  if curl -fsS -m 20 "http://127.0.0.1:$LAYER_PORT/healthz" >/dev/null; then
    echo "  /healthz OK"
  else
    warn "/healthz did not answer. Check: journalctl -u vantage-pi-layer -n 50"
  fi

  if curl -fsS -m 20 "http://127.0.0.1:$LAYER_PORT/v1/models" \
       -H "Authorization: Bearer $RELAY_KEY" >/dev/null; then
    echo "  /v1/models OK"
  else
    warn "/v1/models did not answer. The layer is up only if /healthz passed."
  fi

  # A keyless request must be refused, or the relay is an open pass-through.
  if curl -fsS -m 20 "http://127.0.0.1:$LAYER_PORT/v1/models" >/dev/null 2>&1; then
    warn "The layer answered WITHOUT a key — it is an open pass-through to your"
    warn "FreeBuff account. FREE_RELAY_API_KEY must be set before exposing it."
  else
    echo "  keyless request correctly refused"
  fi
else
  warn "curl not found — skipping verification."
fi

# Units (layer, sweep, tunnel, linger, cron) were installed above.

# --------------------------------------------------------------- summary
cat <<EOF

$(say "Next steps")

0. This Pi must keep running when your laptop is shut. Sign in once ON THIS BOX:
     npx --yes @codebuff/cli login
   Then: bash scripts/pi/pi-status.sh
   Every line OK means you can close Raspberry Pi Connect and power off the laptop.

1. Background jobs already work. The sweep is outbound-only: it dials your database
   and pulls queued work, so nothing needs to be exposed for it.

2. For interactive team chat, Vercel has to reach this box through cloudflared
   running HERE (systemd + cron), not a process on your laptop.

     cloudflared tunnel login
     cloudflared tunnel create vantage-relay
     cloudflared tunnel route dns vantage-relay relay.yourdomain.com
     # Token goes in .env.free-relay as CLOUDFLARE_TUNNEL_TOKEN, then:
     bash scripts/pi/install-autonomous-units.sh

3. Then set these on the Vantage deployment (Vercel project env):

     FREE_RELAY_BASE_URL=https://relay.yourdomain.com/v1,https://second-pi.yourdomain.com/v1
     FREE_RELAY_API_KEY=$RELAY_KEY
     FREE_RELAY_MODEL=$MODEL
     FREE_RELAY_PROVIDER=freebuff

   Vantage refuses a non-loopback FREE_RELAY_BASE_URL that has no key, so the tunnel
   hostname above must keep FREE_RELAY_API_KEY set.

4. Grant a team a relay window at /admin/ai-grants. Teams without a grant are
   untouched and keep using their own keys.

Full walkthrough: docs/FREE_RELAY_PI.md
EOF
