import type { Metadata } from "next";
import { SITE_URL } from "../site";

const OG_IMAGE = {
  // A PNG generated by app/opengraph-image.tsx: link previews do not render SVG.
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "Vantage — free software for FRC teams",
} as const;

/** Shared defaults for public marketing + legal pages. */
export function marketingPageMetadata(input: {
  title: string;
  description: string;
  path: string;
}): Metadata {
  const title = input.title;
  const url = `${SITE_URL}${input.path === "/" ? "" : input.path}`;
  return {
    title: { absolute: title },
    description: input.description,
    alternates: { canonical: input.path },
    openGraph: {
      title,
      description: input.description,
      url,
      type: "website",
      siteName: "Vantage",
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: input.description,
      images: [OG_IMAGE.url],
    },
  };
}

/** Root layout metadata — metadataBase follows NEXT_PUBLIC_SITE_URL when set. */
export function rootMarketingMetadata(): Metadata {
  return {
    metadataBase: new URL(SITE_URL),
    title: {
      default: "Vantage — your FRC team, connected",
      template: "%s — Vantage",
    },
    description:
      "An FRC team workspace for scouting, strategy, team coordination, robot development and business. Free to use, with optional personal AI connections.",
    manifest: "/manifest.webmanifest",
    alternates: { canonical: "/" },
    openGraph: {
      title: "Vantage — your FRC team, connected",
      description:
        "Scouting, strategy, team coordination, robot development and business in one connected FRC workspace.",
      url: SITE_URL,
      type: "website",
      siteName: "Vantage",
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: "Vantage — your FRC team, connected",
      description:
        "Your FRC team, connected: scouting, team work, robot development and business.",
      images: [OG_IMAGE.url],
    },
    robots: { index: true, follow: true },
    icons: { icon: "/icon.svg", apple: "/icon.svg" },
    appleWebApp: { capable: true, title: "Vantage" },
  };
}

/** Organization + SoftwareApplication JSON-LD — no fake ratings or review counts. */
export function organizationSoftwareJsonLd() {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": `${SITE_URL}/#organization`,
        name: "Vantage",
        alternateName: ["Vantage FRC"],
        url: SITE_URL,
        email: "vantagefrc@gmail.com",
        description:
          "Competition operations platform for FIRST Robotics Competition (FRC) teams.",
        logo: `${SITE_URL}/vantage-logo.svg`,
      },
      {
        "@type": "SoftwareApplication",
        "@id": `${SITE_URL}/#software`,
        name: "Vantage",
        applicationCategory: "BusinessApplication",
        operatingSystem: "Web",
        url: SITE_URL,
        description:
          "An FRC workspace for scouting, strategy, team coordination, robot development and business, with optional personal AI connections.",
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
          description:
            "Vantage has no subscription charge. Optional AI uses personal Codex or a personal or team provider key; external provider charges are separate.",
          url: `${SITE_URL}/pricing`,
        },
        publisher: { "@id": `${SITE_URL}/#organization` },
      },
      {
        "@type": "WebSite",
        "@id": `${SITE_URL}/#website`,
        url: SITE_URL,
        name: "Vantage",
        publisher: { "@id": `${SITE_URL}/#organization` },
        inLanguage: "en-US",
      },
    ],
  };
}
