import { createHash,randomBytes } from "node:crypto";
import { auth } from "@vantage/core";
import { withRls } from "@vantage/db";
import { headers } from "next/headers";
async function current(){const value=await auth.api.getSession({headers:await headers()});if(!value)throw new Error("Authentication required");return value;}
const fail=(error:unknown)=>Response.json({error:error instanceof Error?error.message:"Showcase request failed"},{status:400});
export async function GET(request:Request){try{const session=await current(),url=new URL(request.url),orgId=url.searchParams.get("orgId"),deckId=url.searchParams.get("deckId");if(!orgId)throw new Error("orgId is required");const data=await withRls({userId:session.user.id,orgId},async client=>({decks:(await client.query(`SELECT id,title,subtitle,theme,is_demo AS "isDemo",updated_at AS "updatedAt" FROM showcase_decks WHERE org_id=$1 ORDER BY updated_at DESC`,[orgId])).rows,sections:deckId?(await client.query(`SELECT id,kind,title,student_content AS "studentContent",ai_assisted_draft AS "aiAssistedDraft",approved_content AS "approvedContent",evidence_refs AS "evidenceRefs",sort_order AS "sortOrder",approved_at AS "approvedAt" FROM showcase_sections WHERE org_id=$1 AND deck_id=$2 ORDER BY sort_order`,[orgId,deckId])).rows:[],tokens:deckId?(await client.query(`SELECT id,expires_at AS "expiresAt",revoked_at AS "revokedAt",last_used_at AS "lastUsedAt" FROM showcase_share_tokens WHERE org_id=$1 AND deck_id=$2 ORDER BY created_at DESC`,[orgId,deckId])).rows:[]}));return Response.json(data);}catch(error){return fail(error);}}
export async function POST(request:Request){try{const session=await current(),body=await request.json() as Record<string,unknown>,orgId=String(body.orgId??"");if(!orgId)throw new Error("orgId is required");const result=await withRls({userId:session.user.id,orgId},async client=>{const action=String(body.action??"");if(action==="create"){const deck=await client.query<{id:string}>(`INSERT INTO showcase_decks(org_id,title,subtitle,is_demo,created_by) VALUES($1,$2,$3,$4,$5) RETURNING id`,[orgId,String(body.title??"Season impact"),String(body.subtitle??"Evidence-backed student engineering"),Boolean(body.isDemo),session.user.id]);const kinds:Array<[string,string]>=[["problem","Problem and goals"],["process","Student process and decisions"],["scouting","Scouting and strategy outcomes"],["cad","CAD versions, BOM, and design reviews"],["code","Code changes and tests"],["reliability","Reliability fixes"],["outreach","Outreach and season impact"]];for(const[kind,title,index]of kinds.map((value,index)=>[...value,index] as const)){const evidence=await evidenceFor(client,orgId,kind);await client.query(`INSERT INTO showcase_sections(org_id,deck_id,kind,title,evidence_refs,sort_order) VALUES($1,$2,$3,$4,$5::jsonb,$6)`,[orgId,deck.rows[0]!.id,kind,title,JSON.stringify(evidence),index]);}return{id:deck.rows[0]!.id};}
 if(action==="update"){await client.query(`UPDATE showcase_sections SET student_content=$4,approved_content=CASE WHEN $5 THEN $4 ELSE approved_content END,approved_by=CASE WHEN $5 THEN $3 ELSE approved_by END,approved_at=CASE WHEN $5 THEN now() ELSE approved_at END,updated_at=now() WHERE id=$1 AND org_id=$2`,[body.sectionId,orgId,session.user.id,String(body.studentContent??""),Boolean(body.approve)]);return{success:true};}
 if(action==="share"){const role=await client.query(`SELECT 1 FROM memberships WHERE org_id=$1 AND user_id=$2 AND role IN ('owner','admin')`,[orgId,session.user.id]);if(!role.rowCount)throw new Error("Organization administrator access required to share");const token=randomBytes(32).toString("base64url");await client.query(`INSERT INTO showcase_share_tokens(org_id,deck_id,token_hash,allowed_section_ids,created_by,expires_at) VALUES($1,$2,$3,$4,$5,now()+interval '7 days')`,[orgId,body.deckId,createHash("sha256").update(token).digest("hex"),body.sectionIds,session.user.id]);return{token,url:`/showcase/present?token=${encodeURIComponent(token)}`};}
 if(action==="revoke-share"){await client.query(`UPDATE showcase_share_tokens SET revoked_at=now() WHERE id=$1 AND org_id=$2`,[body.tokenId,orgId]);return{success:true};}
 if(action==="practice"){const sections=await client.query<{id:string;title:string;evidence_refs:Array<{type:string;id:string}>}>(`SELECT id,title,evidence_refs FROM showcase_sections WHERE deck_id=$1 AND org_id=$2 AND approved_at IS NOT NULL ORDER BY sort_order`,[body.deckId,orgId]);if(!sections.rowCount)throw new Error("Approve at least one section before starting reasoning practice");const questions=sections.rows.map(section=>({question:`Explain the reasoning behind “${section.title}” and what evidence changed your decision.`,evidenceRefs:section.evidence_refs}));const practice=await client.query<{id:string}>(`INSERT INTO judge_practice_sessions(org_id,deck_id,user_id,questions) VALUES($1,$2,$3,$4::jsonb) RETURNING id`,[orgId,body.deckId,session.user.id,JSON.stringify(questions)]);return{id:practice.rows[0]!.id,questions};}
 throw new Error("Invalid showcase action");});return Response.json(result,{status:201});}catch(error){return fail(error);}}
async function evidenceFor(client:import("@neondatabase/serverless").PoolClient,orgId:string,kind:string){if(kind==="cad")return(await client.query(`SELECT id,'cad_artifact' AS type,title AS label FROM cad_artifacts WHERE org_id=$1 ORDER BY created_at DESC LIMIT 6`,[orgId])).rows;if(kind==="scouting")return(await client.query(`SELECT id,'scout_entry' AS type,concat(team_key,' ',match_key) AS label FROM match_scout_entries WHERE org_id=$1 ORDER BY created_at DESC LIMIT 6`,[orgId])).rows;if(kind==="process")return(await client.query(`SELECT id,'ai_artifact' AS type,title AS label FROM ai_artifacts WHERE org_id=$1 ORDER BY created_at DESC LIMIT 6`,[orgId])).rows;return[];}
