import { createHash, randomBytes, timingSafeEqual } from "node:crypto";

/**
 * Desktop browser-link primitives (migration 0491_desktop_link.sql).
 *
 * Everything secret is sha256-hashed at rest; the desktop's verifier never
 * reaches the server at all — only its sha256 challenge does, and the exchange
 * proves possession by re-hashing the presented verifier.
 */

/** The user must approve within 10 minutes of the desktop starting the flow. */
export const LINK_REQUEST_TTL_SECONDS = 600;
/** The desktop must exchange the one-time authorization code within 5 minutes. */
export const AUTH_CODE_TTL_SECONDS = 300;
/** Desktop poll cadence hint. */
export const POLL_INTERVAL_SECONDS = 3;

/** Ambiguity-free alphabet (no I/O/0/1) — mirrors CAD + AI-bridge pairing codes. */
export const USER_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";

/** 8 chars in two groups, e.g. "ABCD-EFGH". */
export function generateUserCode(): string {
  return Array.from(
    { length: 8 },
    (_, index) => (index === 4 ? "-" : "") + USER_CODE_ALPHABET[randomBytes(1)[0]! % USER_CODE_ALPHABET.length],
  ).join("");
}

/** Strip separators/case so "abcd efgh" and "ABCD-EFGH" hash identically. */
export function normalizeUserCode(raw: string): string | null {
  const normalized = raw.toUpperCase().replace(/[^A-Z2-9]/g, "");
  if (normalized.length !== 8) return null;
  for (const char of normalized) {
    if (!USER_CODE_ALPHABET.includes(char)) return null;
  }
  return normalized;
}

export function formatUserCode(normalized: string): string {
  return `${normalized.slice(0, 4)}-${normalized.slice(4)}`;
}

export function sha256Hex(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

/** 32 random bytes, base64url — generated by the DESKTOP and kept in its memory. */
export function generateVerifier(): string {
  return randomBytes(32).toString("base64url");
}

export function generateAuthCode(): string {
  return randomBytes(32).toString("base64url");
}

export function generatePollToken(): string {
  return randomBytes(32).toString("base64url");
}

/** sha256 hex of a base64url verifier — what the desktop sends at start. */
export function isChallengeShape(value: unknown): value is string {
  return typeof value === "string" && /^[0-9a-f]{64}$/.test(value);
}

export function isVerifierShape(value: unknown): value is string {
  return typeof value === "string" && /^[A-Za-z0-9_-]{43,128}$/.test(value);
}

export function isAuthCodeShape(value: unknown): value is string {
  return typeof value === "string" && /^[A-Za-z0-9_-]{20,200}$/.test(value);
}

export function isPollTokenShape(value: unknown): value is string {
  return typeof value === "string" && /^[A-Za-z0-9_-]{20,200}$/.test(value);
}

/** Constant-time proof of possession: sha256(verifier) must equal the stored challenge. */
export function verifierMatchesChallenge(verifier: unknown, challenge: unknown): boolean {
  if (!isVerifierShape(verifier) || !isChallengeShape(challenge)) return false;
  const hashed = Buffer.from(sha256Hex(verifier), "hex");
  const expected = Buffer.from(challenge, "hex");
  return hashed.length === expected.length && timingSafeEqual(hashed, expected);
}

/** Trim, collapse whitespace, cap length; null when nothing usable remains. */
export function sanitizeMachineName(raw: unknown): string | null {
  if (typeof raw !== "string") return null;
  const cleaned = raw.replace(/\s+/g, " ").trim().slice(0, 80).trim();
  return cleaned.length > 0 ? cleaned : null;
}
