/**
 * GENERATED from packages/agent/src/tools.ts — do not edit by hand.
 *
 * Regenerate with `npx tsx scripts/generate-known-tools.ts`. The governance UI's tool
 * allowlist (/team/ai-policy) and isToolAllowed read this list; billing cannot import
 * @vantage/agent (agent depends on billing), so the registry's names are copied here and
 * packages/agent/test/tool-names.test.ts asserts the two lists are identical.
 */
export const KNOWN_TOOLS = [
  "alliance_partner_brief.brief",
  "artifacts.related",
  "budget_reconciler.reports",
  "cad.briefs",
  "cad.create_brief",
  "cad.design_context",
  "calendar.upcoming",
  "code_perf.changes",
  "counter_book.reports",
  "decision_critic.reviews",
  "decision_search.search",
  "defense_planner.matchups",
  "finance.create_purchase_request",
  "finance.orders",
  "finance.summary",
  "fmea.open_risks",
  "fmea.repeat",
  "impact_essay.draft",
  "inspection_copilot.checks",
  "inventory.availability",
  "judge_sim.evidence",
  "judge_sim.sessions",
  "kickoff.intelligence",
  "kickoff.rules",
  "knowledge.get_page",
  "knowledge.search",
  "knowledge_gap.scan_summary",
  "match_copilot.brief",
  "media_kit.one_pagers",
  "media_kit.profile",
  "meeting_autopilot.action_items",
  "meeting_autopilot.agenda",
  "mock_judging.prep_notes",
  "mock_judging.sessions",
  "my_day.summary",
  "onboarding_buddy.pairings",
  "overnight_intel.latest_brief",
  "picklist_justifier.entries",
  "pit_repair_triage.reports",
  "prototype_tracker.decisions",
  "readiness_score.index",
  "reference.team",
  "research.findings",
  "retro.postmortem",
  "reuse_advisor.assessments",
  "rule_impact.assessments",
  "rules.compliance",
  "scouting.schema",
  "scouting.team",
  "season_report.snapshots",
  "sketch_to_brief.draft",
  "skills_graph.mentor_matches",
  "spare_robot_kit.checklists",
  "standup_digest.brief",
  "strategy.design",
  "strategy.match",
  "strategy.private_edge",
  "tuning_autopilot.sessions",
  "web.fetch",
  "web.search",
  "wiring_diagnoser.checks",
] as const;

export type KnownToolName = (typeof KNOWN_TOOLS)[number];
